/**
 * Curated subset of the Material Design icon set (ligature names).
 *
 * The whole set holds a few thousand icons, which would be too heavy to bundle: this list covers
 * the icons used on a day to day basis. Use `onlc_icons_material_url` to load the complete list
 * from your own server, or `onlc_icons_material_append` to add your own entries.
 */

export interface RawMaterialIcon {
  readonly name: string;
  readonly keywords: string;
  readonly category: string;
}

const ACTIONS = 'Actions';
const NAVIGATION = 'Navigation';
const CONTENT = 'Contenu';
const COMMUNICATION = 'Communication';
const FILES = 'Fichiers';
const MEDIA = 'Média';
const COMMERCE = 'Commerce';
const SOCIAL = 'Social';
const PLACES = 'Cartes et lieux';
const DEVICES = 'Appareils';
const ALERTS = 'Alertes';
const EDITOR = 'Mise en forme';

export const materialIcons: RawMaterialIcon[] = [
  // Actions
  { name: 'search', keywords: 'recherche rechercher loupe find magnify', category: ACTIONS },
  { name: 'settings', keywords: 'reglages parametres configuration engrenage gear', category: ACTIONS },
  { name: 'done', keywords: 'valider ok coche check termine', category: ACTIONS },
  { name: 'done_all', keywords: 'tout valider coches check all', category: ACTIONS },
  { name: 'close', keywords: 'fermer croix annuler cancel x', category: ACTIONS },
  { name: 'add', keywords: 'ajouter plus nouveau new', category: ACTIONS },
  { name: 'add_circle', keywords: 'ajouter cercle plus rond', category: ACTIONS },
  { name: 'remove', keywords: 'retirer moins minus', category: ACTIONS },
  { name: 'delete', keywords: 'supprimer poubelle corbeille trash bin', category: ACTIONS },
  { name: 'delete_forever', keywords: 'supprimer definitivement poubelle', category: ACTIONS },
  { name: 'edit', keywords: 'modifier crayon editer pencil', category: ACTIONS },
  { name: 'save', keywords: 'enregistrer sauvegarder disquette', category: ACTIONS },
  { name: 'refresh', keywords: 'rafraichir recharger actualiser reload', category: ACTIONS },
  { name: 'autorenew', keywords: 'synchroniser boucle recycler', category: ACTIONS },
  { name: 'sync', keywords: 'synchronisation actualiser', category: ACTIONS },
  { name: 'undo', keywords: 'annuler retour arriere', category: ACTIONS },
  { name: 'redo', keywords: 'retablir refaire', category: ACTIONS },
  { name: 'visibility', keywords: 'voir oeil afficher apercu preview eye', category: ACTIONS },
  { name: 'visibility_off', keywords: 'masquer oeil barre cacher', category: ACTIONS },
  { name: 'lock', keywords: 'cadenas verrouille securite prive', category: ACTIONS },
  { name: 'lock_open', keywords: 'cadenas ouvert deverrouille', category: ACTIONS },
  { name: 'https', keywords: 'securite ssl cadenas certificat', category: ACTIONS },
  { name: 'verified_user', keywords: 'securite bouclier verifie', category: ACTIONS },
  { name: 'favorite', keywords: 'coeur favori aimer like', category: ACTIONS },
  { name: 'favorite_border', keywords: 'coeur contour favori', category: ACTIONS },
  { name: 'star', keywords: 'etoile favori note avis', category: ACTIONS },
  { name: 'star_border', keywords: 'etoile contour note', category: ACTIONS },
  { name: 'star_half', keywords: 'demi etoile note', category: ACTIONS },
  { name: 'bookmark', keywords: 'marque page favori signet', category: ACTIONS },
  { name: 'thumb_up', keywords: 'pouce like jaime', category: ACTIONS },
  { name: 'thumb_down', keywords: 'pouce dislike', category: ACTIONS },
  { name: 'share', keywords: 'partager partage', category: ACTIONS },
  { name: 'print', keywords: 'imprimer imprimante', category: ACTIONS },
  { name: 'search_off', keywords: 'recherche desactivee', category: ACTIONS },
  { name: 'filter_alt', keywords: 'filtrer filtre entonnoir', category: ACTIONS },
  { name: 'sort', keywords: 'trier tri ordre', category: ACTIONS },
  { name: 'swap_horiz', keywords: 'echanger horizontal permuter', category: ACTIONS },
  { name: 'swap_vert', keywords: 'echanger vertical permuter', category: ACTIONS },
  { name: 'zoom_in', keywords: 'zoom avant agrandir', category: ACTIONS },
  { name: 'zoom_out', keywords: 'zoom arriere reduire', category: ACTIONS },
  { name: 'open_in_new', keywords: 'nouvel onglet ouvrir externe', category: ACTIONS },
  { name: 'link', keywords: 'lien chaine url', category: ACTIONS },
  { name: 'link_off', keywords: 'supprimer lien delier', category: ACTIONS },
  { name: 'content_copy', keywords: 'copier duplication duplicate', category: ACTIONS },
  { name: 'content_paste', keywords: 'coller presse papier', category: ACTIONS },
  { name: 'content_cut', keywords: 'couper ciseaux', category: ACTIONS },
  { name: 'drag_indicator', keywords: 'deplacer poignee glisser drag', category: ACTIONS },
  { name: 'more_vert', keywords: 'plus options menu trois points', category: ACTIONS },
  { name: 'more_horiz', keywords: 'plus options menu points', category: ACTIONS },
  { name: 'tune', keywords: 'reglages curseurs options', category: ACTIONS },
  { name: 'build', keywords: 'outil cle maintenance reparer', category: ACTIONS },
  { name: 'power_settings_new', keywords: 'alimentation demarrer eteindre', category: ACTIONS },
  { name: 'login', keywords: 'connexion se connecter entrer', category: ACTIONS },
  { name: 'logout', keywords: 'deconnexion sortir quitter', category: ACTIONS },
  { name: 'download', keywords: 'telecharger descendre', category: ACTIONS },
  { name: 'upload', keywords: 'televerser envoyer monter', category: ACTIONS },
  { name: 'cloud_upload', keywords: 'nuage televerser envoyer', category: ACTIONS },
  { name: 'cloud_download', keywords: 'nuage telecharger', category: ACTIONS },

  // Navigation
  { name: 'home', keywords: 'accueil maison', category: NAVIGATION },
  { name: 'menu', keywords: 'menu burger navigation', category: NAVIGATION },
  { name: 'arrow_back', keywords: 'fleche gauche retour precedent', category: NAVIGATION },
  { name: 'arrow_forward', keywords: 'fleche droite suivant', category: NAVIGATION },
  { name: 'arrow_upward', keywords: 'fleche haut monter', category: NAVIGATION },
  { name: 'arrow_downward', keywords: 'fleche bas descendre', category: NAVIGATION },
  { name: 'chevron_left', keywords: 'chevron gauche precedent', category: NAVIGATION },
  { name: 'chevron_right', keywords: 'chevron droite suivant', category: NAVIGATION },
  { name: 'expand_more', keywords: 'deplier bas chevron', category: NAVIGATION },
  { name: 'expand_less', keywords: 'replier haut chevron', category: NAVIGATION },
  { name: 'first_page', keywords: 'premiere page debut', category: NAVIGATION },
  { name: 'last_page', keywords: 'derniere page fin', category: NAVIGATION },
  { name: 'apps', keywords: 'applications grille', category: NAVIGATION },
  { name: 'dashboard', keywords: 'tableau de bord grille', category: NAVIGATION },
  { name: 'list', keywords: 'liste elements', category: NAVIGATION },
  { name: 'grid_view', keywords: 'grille vignettes mosaique', category: NAVIGATION },
  { name: 'view_module', keywords: 'grille modules colonnes', category: NAVIGATION },
  { name: 'view_carousel', keywords: 'carrousel diaporama', category: NAVIGATION },
  { name: 'fullscreen', keywords: 'plein ecran agrandir', category: NAVIGATION },
  { name: 'fullscreen_exit', keywords: 'quitter plein ecran', category: NAVIGATION },
  { name: 'unfold_more', keywords: 'deplier ouvrir', category: NAVIGATION },
  { name: 'unfold_less', keywords: 'replier fermer', category: NAVIGATION },

  // Contenu
  { name: 'article', keywords: 'article page texte document', category: CONTENT },
  { name: 'description', keywords: 'document fiche texte', category: CONTENT },
  { name: 'subject', keywords: 'texte paragraphe lignes', category: CONTENT },
  { name: 'title', keywords: 'titre heading', category: CONTENT },
  { name: 'label', keywords: 'etiquette tag categorie', category: CONTENT },
  { name: 'category', keywords: 'categorie rubrique', category: CONTENT },
  { name: 'inventory_2', keywords: 'stock carton produit', category: CONTENT },
  { name: 'newspaper', keywords: 'journal actualite presse', category: CONTENT },
  { name: 'menu_book', keywords: 'livre menu carte lecture', category: CONTENT },
  { name: 'auto_stories', keywords: 'livre pages histoire', category: CONTENT },
  { name: 'quiz', keywords: 'faq question quiz', category: CONTENT },
  { name: 'help', keywords: 'aide question support', category: CONTENT },
  { name: 'help_outline', keywords: 'aide contour question', category: CONTENT },
  { name: 'info', keywords: 'information details', category: CONTENT },
  { name: 'lightbulb', keywords: 'idee ampoule astuce conseil', category: CONTENT },
  { name: 'psychology', keywords: 'cerveau reflexion idee', category: CONTENT },
  { name: 'workspace_premium', keywords: 'medaille qualite recompense', category: CONTENT },
  { name: 'emoji_events', keywords: 'trophee gagnant recompense', category: CONTENT },
  { name: 'verified', keywords: 'verifie certifie badge', category: CONTENT },
  { name: 'new_releases', keywords: 'nouveaute badge important', category: CONTENT },
  { name: 'local_offer', keywords: 'promotion etiquette prix', category: CONTENT },

  // Mise en forme
  { name: 'format_bold', keywords: 'gras bold', category: EDITOR },
  { name: 'format_italic', keywords: 'italique italic', category: EDITOR },
  { name: 'format_underlined', keywords: 'souligne underline', category: EDITOR },
  { name: 'format_align_left', keywords: 'aligner gauche', category: EDITOR },
  { name: 'format_align_center', keywords: 'aligner centre', category: EDITOR },
  { name: 'format_align_right', keywords: 'aligner droite', category: EDITOR },
  { name: 'format_align_justify', keywords: 'justifier', category: EDITOR },
  { name: 'format_list_bulleted', keywords: 'liste puces', category: EDITOR },
  { name: 'format_list_numbered', keywords: 'liste numerotee', category: EDITOR },
  { name: 'format_quote', keywords: 'citation guillemets', category: EDITOR },
  { name: 'format_color_fill', keywords: 'remplissage couleur fond', category: EDITOR },
  { name: 'format_size', keywords: 'taille texte police', category: EDITOR },
  { name: 'text_fields', keywords: 'texte champ typographie', category: EDITOR },
  { name: 'horizontal_rule', keywords: 'ligne separateur trait', category: EDITOR },
  { name: 'table_chart', keywords: 'tableau grille donnees', category: EDITOR },
  { name: 'code', keywords: 'code html balises', category: EDITOR },
  { name: 'terminal', keywords: 'console terminal commande', category: EDITOR },
  { name: 'space_bar', keywords: 'espace separateur', category: EDITOR },

  // Communication
  { name: 'mail', keywords: 'email courriel enveloppe message', category: COMMUNICATION },
  { name: 'mail_outline', keywords: 'email contour courriel', category: COMMUNICATION },
  { name: 'alternate_email', keywords: 'arobase email adresse', category: COMMUNICATION },
  { name: 'send', keywords: 'envoyer avion message', category: COMMUNICATION },
  { name: 'phone', keywords: 'telephone appel combine', category: COMMUNICATION },
  { name: 'phone_in_talk', keywords: 'appel en cours telephone', category: COMMUNICATION },
  { name: 'smartphone', keywords: 'mobile telephone portable', category: COMMUNICATION },
  { name: 'chat', keywords: 'discussion message bulle', category: COMMUNICATION },
  { name: 'chat_bubble', keywords: 'bulle message commentaire', category: COMMUNICATION },
  { name: 'forum', keywords: 'forum discussion messages', category: COMMUNICATION },
  { name: 'comment', keywords: 'commentaire avis', category: COMMUNICATION },
  { name: 'question_answer', keywords: 'faq questions reponses', category: COMMUNICATION },
  { name: 'contact_support', keywords: 'support assistance aide', category: COMMUNICATION },
  { name: 'support_agent', keywords: 'service client assistance', category: COMMUNICATION },
  { name: 'headset_mic', keywords: 'casque support hotline', category: COMMUNICATION },
  { name: 'contact_mail', keywords: 'contact courrier carte', category: COMMUNICATION },
  { name: 'call', keywords: 'appeler telephone', category: COMMUNICATION },
  { name: 'rss_feed', keywords: 'flux rss abonnement', category: COMMUNICATION },
  { name: 'notifications', keywords: 'cloche alerte notification', category: COMMUNICATION },
  { name: 'notifications_active', keywords: 'cloche active alerte', category: COMMUNICATION },

  // Fichiers
  { name: 'folder', keywords: 'dossier repertoire', category: FILES },
  { name: 'folder_open', keywords: 'dossier ouvert repertoire', category: FILES },
  { name: 'create_new_folder', keywords: 'nouveau dossier creer', category: FILES },
  { name: 'insert_drive_file', keywords: 'fichier document', category: FILES },
  { name: 'attach_file', keywords: 'piece jointe trombone', category: FILES },
  { name: 'attachment', keywords: 'piece jointe trombone', category: FILES },
  { name: 'picture_as_pdf', keywords: 'pdf document telechargement', category: FILES },
  { name: 'file_download', keywords: 'telecharger fichier', category: FILES },
  { name: 'file_upload', keywords: 'televerser fichier envoyer', category: FILES },
  { name: 'cloud', keywords: 'nuage stockage', category: FILES },
  { name: 'backup', keywords: 'sauvegarde nuage', category: FILES },
  { name: 'archive', keywords: 'archiver boite', category: FILES },
  { name: 'drive_file_move', keywords: 'deplacer fichier dossier', category: FILES },
  { name: 'text_snippet', keywords: 'extrait fichier texte', category: FILES },

  // Média
  { name: 'image', keywords: 'photo illustration visuel', category: MEDIA },
  { name: 'photo_camera', keywords: 'appareil photo camera', category: MEDIA },
  { name: 'photo_library', keywords: 'galerie photos album', category: MEDIA },
  { name: 'collections', keywords: 'galerie collection photos', category: MEDIA },
  { name: 'movie', keywords: 'film video cinema', category: MEDIA },
  { name: 'videocam', keywords: 'camera video film', category: MEDIA },
  { name: 'play_arrow', keywords: 'lecture jouer play', category: MEDIA },
  { name: 'play_circle', keywords: 'lecture cercle video', category: MEDIA },
  { name: 'pause', keywords: 'pause arreter', category: MEDIA },
  { name: 'stop', keywords: 'stop arreter', category: MEDIA },
  { name: 'volume_up', keywords: 'son volume haut parleur', category: MEDIA },
  { name: 'volume_off', keywords: 'muet son coupe', category: MEDIA },
  { name: 'mic', keywords: 'micro enregistrement podcast', category: MEDIA },
  { name: 'headphones', keywords: 'casque audio musique', category: MEDIA },
  { name: 'music_note', keywords: 'musique note audio', category: MEDIA },
  { name: 'slideshow', keywords: 'diaporama presentation', category: MEDIA },
  { name: 'crop', keywords: 'recadrer rogner image', category: MEDIA },
  { name: 'palette', keywords: 'couleurs peinture palette', category: MEDIA },
  { name: 'brush', keywords: 'pinceau dessin peinture', category: MEDIA },
  { name: 'filter', keywords: 'filtre photo effet', category: MEDIA },

  // Commerce
  { name: 'shopping_cart', keywords: 'panier achat caddie', category: COMMERCE },
  { name: 'add_shopping_cart', keywords: 'ajouter au panier achat', category: COMMERCE },
  { name: 'shopping_bag', keywords: 'sac achat boutique', category: COMMERCE },
  { name: 'store', keywords: 'boutique magasin commerce', category: COMMERCE },
  { name: 'storefront', keywords: 'vitrine boutique magasin', category: COMMERCE },
  { name: 'payment', keywords: 'paiement carte bancaire', category: COMMERCE },
  { name: 'credit_card', keywords: 'carte bancaire paiement', category: COMMERCE },
  { name: 'euro', keywords: 'euro prix monnaie', category: COMMERCE },
  { name: 'euro_symbol', keywords: 'euro devise prix', category: COMMERCE },
  { name: 'receipt_long', keywords: 'facture recu ticket', category: COMMERCE },
  { name: 'local_shipping', keywords: 'livraison camion transport', category: COMMERCE },
  { name: 'inventory', keywords: 'stock inventaire', category: COMMERCE },
  { name: 'sell', keywords: 'vendre etiquette prix', category: COMMERCE },
  { name: 'discount', keywords: 'remise promotion solde', category: COMMERCE },
  { name: 'work', keywords: 'travail mallette entreprise', category: COMMERCE },
  { name: 'business_center', keywords: 'affaires entreprise mallette', category: COMMERCE },
  { name: 'trending_up', keywords: 'croissance hausse courbe', category: COMMERCE },
  { name: 'bar_chart', keywords: 'graphique statistiques barres', category: COMMERCE },
  { name: 'pie_chart', keywords: 'camembert statistiques graphique', category: COMMERCE },
  { name: 'analytics', keywords: 'analyse statistiques donnees', category: COMMERCE },

  // Social
  { name: 'person', keywords: 'personne utilisateur profil', category: SOCIAL },
  { name: 'person_add', keywords: 'ajouter utilisateur inscription', category: SOCIAL },
  { name: 'group', keywords: 'groupe equipe utilisateurs', category: SOCIAL },
  { name: 'groups', keywords: 'equipe communaute reunion', category: SOCIAL },
  { name: 'account_circle', keywords: 'compte profil utilisateur', category: SOCIAL },
  { name: 'badge', keywords: 'badge identite carte', category: SOCIAL },
  { name: 'diversity_3', keywords: 'diversite equipe communaute', category: SOCIAL },
  { name: 'handshake', keywords: 'partenariat accord poignee de main', category: SOCIAL },
  { name: 'volunteer_activism', keywords: 'solidarite don aide', category: SOCIAL },
  { name: 'school', keywords: 'ecole formation diplome', category: SOCIAL },
  { name: 'sports_esports', keywords: 'jeu manette gaming', category: SOCIAL },
  { name: 'celebration', keywords: 'fete evenement celebration', category: SOCIAL },

  // Cartes et lieux
  { name: 'place', keywords: 'lieu adresse marqueur carte', category: PLACES },
  { name: 'location_on', keywords: 'localisation adresse marqueur', category: PLACES },
  { name: 'map', keywords: 'carte plan itineraire', category: PLACES },
  { name: 'near_me', keywords: 'itineraire direction navigation', category: PLACES },
  { name: 'directions', keywords: 'itineraire direction route', category: PLACES },
  { name: 'directions_car', keywords: 'voiture route acces', category: PLACES },
  { name: 'directions_bus', keywords: 'bus transport commun', category: PLACES },
  { name: 'train', keywords: 'train gare transport', category: PLACES },
  { name: 'flight', keywords: 'avion vol aeroport', category: PLACES },
  { name: 'directions_walk', keywords: 'marche pieton acces', category: PLACES },
  { name: 'local_parking', keywords: 'parking stationnement', category: PLACES },
  { name: 'restaurant', keywords: 'restaurant repas couverts', category: PLACES },
  { name: 'local_cafe', keywords: 'cafe boisson bar', category: PLACES },
  { name: 'hotel', keywords: 'hotel hebergement lit', category: PLACES },
  { name: 'apartment', keywords: 'immeuble batiment bureau', category: PLACES },
  { name: 'home_work', keywords: 'bureau maison entreprise', category: PLACES },
  { name: 'public', keywords: 'globe monde international web', category: PLACES },
  { name: 'language', keywords: 'langue globe traduction', category: PLACES },
  { name: 'accessible', keywords: 'accessibilite handicap pmr', category: PLACES },

  // Appareils
  { name: 'computer', keywords: 'ordinateur bureau pc', category: DEVICES },
  { name: 'laptop', keywords: 'portable ordinateur', category: DEVICES },
  { name: 'tablet', keywords: 'tablette ecran', category: DEVICES },
  { name: 'devices', keywords: 'appareils responsive multi ecrans', category: DEVICES },
  { name: 'watch', keywords: 'montre connectee', category: DEVICES },
  { name: 'wifi', keywords: 'wifi reseau internet', category: DEVICES },
  { name: 'bluetooth', keywords: 'bluetooth sans fil', category: DEVICES },
  { name: 'battery_full', keywords: 'batterie pleine energie', category: DEVICES },
  { name: 'memory', keywords: 'processeur puce memoire', category: DEVICES },
  { name: 'storage', keywords: 'serveur stockage donnees', category: DEVICES },
  { name: 'router', keywords: 'routeur box reseau', category: DEVICES },
  { name: 'print_disabled', keywords: 'impression desactivee', category: DEVICES },
  { name: 'qr_code_2', keywords: 'qr code scan', category: DEVICES },
  { name: 'keyboard', keywords: 'clavier saisie', category: DEVICES },

  // Alertes
  { name: 'warning', keywords: 'attention alerte danger triangle', category: ALERTS },
  { name: 'error', keywords: 'erreur probleme alerte', category: ALERTS },
  { name: 'error_outline', keywords: 'erreur contour alerte', category: ALERTS },
  { name: 'check_circle', keywords: 'valide succes coche cercle', category: ALERTS },
  { name: 'cancel', keywords: 'annuler refuse croix', category: ALERTS },
  { name: 'report_problem', keywords: 'signaler probleme alerte', category: ALERTS },
  { name: 'priority_high', keywords: 'important priorite exclamation', category: ALERTS },
  { name: 'schedule', keywords: 'horaire heure horloge', category: ALERTS },
  { name: 'event', keywords: 'evenement calendrier date', category: ALERTS },
  { name: 'calendar_month', keywords: 'calendrier mois date', category: ALERTS },
  { name: 'timer', keywords: 'chronometre duree temps', category: ALERTS },
  { name: 'history', keywords: 'historique horloge retour', category: ALERTS },
  { name: 'update', keywords: 'mise a jour horloge', category: ALERTS },
  { name: 'hourglass_empty', keywords: 'sablier attente patience', category: ALERTS },
  { name: 'campaign', keywords: 'annonce megaphone communication', category: ALERTS },
  { name: 'tips_and_updates', keywords: 'astuce conseil nouveaute', category: ALERTS },
  { name: 'eco', keywords: 'ecologie feuille environnement', category: ALERTS },
  { name: 'recycling', keywords: 'recyclage environnement', category: ALERTS },
  { name: 'health_and_safety', keywords: 'securite sante bouclier', category: ALERTS },
  { name: 'gpp_good', keywords: 'securite protege bouclier', category: ALERTS }
];
