/**
 * Paquet de langue « en_CA » — English.
 *
 * Produit par tools/openmoji/build-i18n.js. Le cœur de l'éditeur ne livre pas de paquet pour
 * cette langue ; celui-ci ne porte donc que les chaînes des plugins ONLC.
 */

/* — ONLC : début des chaînes des plugins — */
hugerte.addI18n("en_CA", {
    "— choisir —": "— choose —",
    "— Choisir une ancre —": "— Choose an anchor —",
    "⚠️ DESTRUCTION": "⚠️ DESTRUCTION",
    "1 vue": "1 view",
    "1:1 (carré)": "1:1 (square)",
    "10 rue de la Paix, Paris": "10 Downing Street, London",
    "16:9 (paysage)": "16:9 (landscape)",
    "2 à 3 jours ouvrés": "2 to 3 working days",
    "200 g de farine": "200 g of flour",
    "21:9 (cinéma)": "21:9 (cinema)",
    "240 calories": "240 calories",
    "26 rue de la Roquille": "26 Roquille Street",
    "3000 millisecondes valent trois secondes. En dessous de 2000, la plupart des visiteurs n’ont pas le temps de lire.": "3000 milliseconds is three seconds. Below 2000, most visitors do not have time to read.",
    "4 parts": "4 servings",
    "61 rue du Château d’Eau, 33000 Bordeaux": "1 Market Street, Manchester M1 1AA",
    "9:16 (vertical)": "9:16 (portrait)",
    "À l’emplacement du curseur": "Where the cursor is",
    "À n’activer que sur un diaporama qui occupe l’écran : sinon la molette cesse de faire défiler la page dès qu’on passe dessus.": "Only enable on a slideshow that fills the screen: otherwise the wheel stops scrolling the page as soon as you move over it.",
    "À partir de": "From",
    "À renseigner": "To fill in",
    "Abonnement annuel": "Annual subscription",
    "Accessible sans payer": "Free to access",
    "Acheter": "Buy",
    "Action javascript au clic": "Javascript action on click",
    "Actions": "Actions",
    "Actuelle": "Current",
    "Adresse": "Address",
    "Adresse à laquelle les messages du formulaire seront envoyés.": "Address the form messages will be sent to.",
    "Adresse de l’agenda": "Calendar address",
    "Adresse de l’événement": "Event address",
    "Adresse de l’image": "Image address",
    "Adresse de la page": "Page address",
    "Adresse de la vidéo": "Video address",
    "Adresse du fichier": "File address",
    "Adresse du fichier vidéo": "Video file address",
    "Adresse du lecteur intégré": "Embedded player address",
    "Adresse du lien": "Link address",
    "Adresse du lieu": "Address of the place",
    "Adresse e-mail": "E-mail address",
    "Adresse personnalisée…": "Custom address…",
    "Adresse postale": "Postal address",
    "Affichage": "View",
    "Affiche du code sans le formater": "Shows code exactly as written",
    "Affiche un PDF directement dans la page, page après page": "Shows a PDF right inside the page, page after page",
    "Affiche une autre page web à l’intérieur de la vôtre": "Shows another web page inside yours",
    "Afficher comme un visiteur": "Show as a visitor",
    "Afficher les flèches précédent / suivant": "Show previous / next arrows",
    "Afficher les intitulés sur les vignettes": "Show captions on thumbnails",
    "Afficher les outils de blocs": "Show block tools",
    "Afficher les points de position": "Show position dots",
    "Afficher une barre de défilement": "Show a scrollbar",
    "Agenda": "Calendar",
    "Agenda partagé": "Shared calendar",
    "Agrandir": "Enlarge",
    "Ajoute du vide entre deux blocs, hauteur réglable": "Adds adjustable empty space between two blocks",
    "Ajoutées": "Added",
    "Ajouter": "Add",
    "Ajouter à la page": "Add to the page",
    "Ajouter à mon calendrier": "Add to my calendar",
    "Ajouter des colonnes": "Add columns",
    "Ajouter des colonnes...": "Add columns...",
    "Ajouter des images à la fin…": "Add images at the end…",
    "Ajouter des images au début…": "Add images at the start…",
    "Ajouter des images…": "Add images…",
    "Ajouter un bloc": "Add a block",
    "Ajouter un bloc à la fin": "Add a block at the end",
    "Ajouter un bloc après": "Add a block after",
    "Ajouter un bloc au début": "Add a block at the start",
    "Ajouter un bloc avant": "Add a block before",
    "Ajouter un bloc...": "Add a block...",
    "Ajouter un espace vertical de la hauteur de votre choix": "Add vertical space of the height you choose",
    "Ajouter un palier": "Add a breakpoint",
    "Ajouter un rendez-vous": "Add an appointment",
    "Ajouter une classe": "Add a class",
    "Ajouter une colonne": "Add a column",
    "Ajouter une configuration": "Add a configuration",
    "Ajouter une description pour les moteurs…": "Add a description for search engines…",
    "Ajouter une propriété…": "Add a property…",
    "Ajouter une valeur": "Add a value",
    "Ajouter une vue vide": "Add an empty slide",
    "Ajoutez au moins une image à la galerie": "Add at least one image to the gallery",
    "Ajustée à la taille de l'écran": "Fitted to the screen",
    "Alignement": "Alignment",
    "Ancre dans la page": "Anchor on this page",
    "Angle (°)": "Angle (°)",
    "Année précédente": "Previous year",
    "Année suivante": "Next year",
    "Annulé": "Cancelled",
    "Annuler": "Cancel",
    "Aperçu comme un visiteur": "Preview as a visitor",
    "Aperçu comme un visiteur...": "Preview as a visitor...",
    "Aperçu de la page": "Page preview",
    "Apparence": "Appearance",
    "Application": "Application",
    "Arrondi": "Rounded",
    "Article": "Article",
    "Article de presse": "News article",
    "Article non renseigné": "Item not filled in",
    "Assistance technique": "Technical support",
    "Au format international, indicatif compris.": "In international format, country code included.",
    "Au format ISO 8601 : PT20M vaut 20 minutes, PT1H30M une heure et demie.": "In ISO 8601 format: PT20M means 20 minutes, PT1H30M an hour and a half.",
    "Au format ISO 8601 : PT2M30S vaut 2 minutes 30.": "In ISO 8601 format: PT2M30S means 2 minutes 30 seconds.",
    "Au-delà de cette date, les moteurs cessent d’afficher le prix.": "Past this date, search engines stop showing the price.",
    "Aucun code pour le moment.": "No code yet.",
    "Aucun fichier choisi.": "No file chosen.",
    "Aucun fichier ne correspond à cette recherche.": "No file matches this search.",
    "Aucun lieu ne correspond. Essayez une adresse plus simple, ou entrez les coordonnées à la main.": "No place matches. Try a simpler address, or enter the coordinates by hand.",
    "Aucun palier : le diaporama montre le même nombre de vues sur tous les écrans.": "No breakpoints: the slideshow shows the same number of slides on every screen.",
    "Aucun rendez-vous pour ce mois. Ajoutez-en un pour le voir apparaître dans la grille.": "No appointments this month. Add one to see it appear in the grid.",
    "Aucune": "None",
    "Aucune — visible par tous": "None — visible to everyone",
    "Aucune adresse renseignée": "No address given",
    "Aucune classe du site ne commence ainsi. Vous pouvez tout de même l’ajouter.": "No class of the site starts like this. You can add it anyway.",
    "Aucune classe pour l’instant.": "No class yet.",
    "Aucune description": "No description",
    "Aucune feuille de style de site n’est déclarée : écrivez le nom de la classe à la main.": "No site stylesheet is declared: write the class name by hand.",
    "Aucune image choisie.": "No image chosen.",
    "Aucune image pour l’instant. Cliquez sur « Ajouter des images… » pour en choisir.": "No images yet. Click “Add images…” to choose some.",
    "Aucune propriété renseignée pour l’instant.": "No property filled in yet.",
    "Auteur": "Author",
    "Autre nom": "Other name",
    "autres : continuez à écrire pour les filtrer.": "more: keep typing to filter them.",
    "Autres pages qui parlent de cette chose": "Other pages about this thing",
    "Avancé": "Advanced",
    "Avancer à la molette de la souris": "Advance with the mouse wheel",
    "Avancer avec les flèches du clavier": "Move with the keyboard arrows",
    "Avancer tout seul": "Advance on its own",
    "Avant retouche": "Before editing",
    "Avec empattement": "Serif",
    "Avis": "Review",
    "Balise « div ». L’identifiant et les classes voyagent avec le bloc : ils sont écrits tels quels dans la page publiée.": "“div” tag. The identifier and the classes travel with the block: they are written as they are in the published page.",
    "Bandeau d’introduction avec titre, texte et bouton": "Opening banner with a heading, text and a button",
    "Barre de progression": "Progress bar",
    "Bas centre": "Bottom centre",
    "Bas droite": "Bottom right",
    "Bas gauche": "Bottom left",
    "Billet de blog": "Blog post",
    "Billetterie": "Tickets",
    "Bloc de texte": "Text block",
    "Bloc prédéfini": "Ready-made block",
    "Blocs et éléments": "Blocks and elements",
    "Blocs et éléments du site": "Blocks and site elements",
    "Blocs et éléments du site...": "Blocks and site elements...",
    "Blocs prédéfinis": "Ready-made blocks",
    "Blocs prédéfinis...": "Ready-made blocks...",
    "boulangerie, pain bio, Bordeaux": "bakery, organic bread, Manchester",
    "Bouton": "Button",
    "Bouton d’appel à l’action": "Call-to-action button",
    "Bouton de paiement PayPal": "PayPal payment button",
    "Bouton ombré": "Shadowed button",
    "Bouton, vidéo, carte…": "Button, video, map…",
    "Bouton, vidéo, menu, contact…": "Button, video, menu, contact…",
    "Boutons de partage": "Sharing buttons",
    "Boutons de partage (minuscules)": "Sharing buttons (tiny)",
    "Boutons de partage (petits)": "Sharing buttons (small)",
    "Calendrier du mois": "Month calendar",
    "Calories": "Calories",
    "Candidatures jusqu’au": "Applications until",
    "Carte": "Map",
    "Carte déplaçable (Leaflet)": "Pannable map (Leaflet)",
    "Carte déplaçable par le visiteur": "Visitors can pan and zoom the map",
    "Cartes empilées": "Stacked cards",
    "Cascade (rangées justifiées)": "Cascade (justified rows)",
    "Catégorie": "Category",
    "Ce diaporama n’a aucune vue. Ajoutez-en une pour qu’il montre quelque chose.": "This slideshow has no slides. Add one so that it shows something.",
    "Ce diaporama n’a pas de réglages dans la page : aucun appel « new Swiper(…) » ne le désigne. Ses images restent modifiables.": "This slideshow has no settings in the page: no “new Swiper(…)” call points at it. Its images remain editable.",
    "Ce dossier est vide. Déposez des fichiers ici, ou utilisez « Téléverser… ».": "This folder is empty. Drop files here, or use “Upload…”.",
    "Ce qu’il faut faire": "What to do",
    "Ce que contient une portion.": "What one serving contains.",
    "Ce que le produit coûte et s’il est en stock. C’est ce bloc qui fait apparaître le prix dans Google.": "What the product costs and whether it is in stock. This block is what makes the price appear in Google.",
    "Ce que montre l’image, en une phrase": "What the image shows, in one sentence",
    "Ce qui est évalué": "What is reviewed",
    "Ce type de fichier n’est pas accepté": "This file type is not accepted",
    "Centre": "Centre",
    "Centré": "Centred",
    "Centrer la vue courante": "Centre the current slide",
    "Ces propriétés sont exigées et restent vides :": "These properties are required and remain empty:",
    "Cet élément n’est pas reconnu par l’éditeur : il sera réécrit tel quel dans la page.": "The editor does not recognise this item: it will be written back to the page unchanged.",
    "Cette action est définitive.": "This cannot be undone.",
    "Cette action ne peut pas être annulée.": "This cannot be undone.",
    "Cette page contenait plusieurs fiches de référencement. Une seule a été conservée : les moteurs de recherche n’en lisent qu’une, et choisissent au hasard quand il y en a plusieurs.": "This page contained several search-engine records. Only one was kept: search engines read a single one, and pick at random when there are several.",
    "Cette valeur est publiée dans toutes les langues. Choisissez une langue pour en écrire une version qui ne paraîtra que dans celle-là.": "This value is published in every language. Choose a language to write a version that appears only in that one.",
    "Cette vue contient autre chose que des images. Elle se modifie directement dans la page.": "This slide contains something other than images. It is edited directly in the page.",
    "Cette vue ne contient pas qu’une image — plusieurs images, ou une mise en page. Elle est déplaçable, mais son contenu n’est pas réécrit.": "This view holds more than a single image — several images, or a layout. It can be moved, but its content is never rewritten.",
    "Changer cet emoji": "Change this emoji",
    "Changer cette icône": "Change this icon",
    "Changer cette image": "Change this image",
    "Changer de type de contenu…": "Change the content type…",
    "Chaque palier s’applique à partir de la largeur indiquée, et jusqu’au palier suivant. En dessous du premier palier, ce sont les réglages de l’onglet « Affichage » qui s’appliquent.": "Each breakpoint applies from the given width up to the next one. Below the first breakpoint, the settings of the “Display” tab apply.",
    "Chaque version d’un fichier compte pour un fichier.": "Every version of a file counts as one file.",
    "Chaque vue est une image du diaporama. L’ordre de la liste est celui du défilement.": "Each slide is an image of the slideshow. The order of the list is the order of the scrolling.",
    "Chargement asynchrone (async)": "Asynchronous loading (async)",
    "Chargement du dossier…": "Loading the folder…",
    "Chasse fixe": "Monospace",
    "Chemin du dossier": "Folder path",
    "Choisir cette image dans la médiathèque": "Choose this image from the media library",
    "Choisir la disposition des colonnes": "Choose the column layout",
    "Choisir ou téléverser un média…": "Choose or upload a file…",
    "Choisir un fichier dans l’explorateur de médias": "Choose a file from the media library",
    "Choisir un fichier…": "Choose a file…",
    "Choisir une image dans la médiathèque ou en téléverser une": "Choose an image from the library or upload one",
    "Choisir une image…": "Choose an image…",
    "Choisir…": "Choose…",
    "Choisissez d’abord ce que décrit cette page : sans type de contenu, les moteurs ne savent pas quoi faire de la fiche.": "First choose what this page describes: without a content type, search engines do not know what to do with the record.",
    "Choisissez l’élément à insérer": "Choose the item to insert",
    "Choisissez le bloc à ajouter": "Choose the block to add",
    "Choisissez le bloc à insérer": "Choose the block to insert",
    "Choisissez le bon lieu dans la liste :": "Choose the right place from the list:",
    "Choisissez le fichier PDF à afficher": "Choose the PDF file to show",
    "Choisissez le mois dans la grille, ou laissez « Mois en cours » pour un calendrier qui se met à jour tout seul.": "Pick the month in the grid, or leave “Current month” for a calendar that keeps itself up to date.",
    "Choisissez un pdf dans votre médiathèque, ou donnez l’adresse d’un fichier hébergé ailleurs.": "Choose a pdf from your media library, or give the address of a file hosted elsewhere.",
    "Choisissez une image": "Choose an image",
    "Choisissez une image avant d'enregistrer.": "Choose an image before saving.",
    "Choisissez une image dans votre médiathèque, ou donnez l’adresse d’une image hébergée ailleurs.": "Choose an image from your media library, or give the address of an image hosted elsewhere.",
    "Chose": "Thing",
    "Cinq par défaut. À préciser si votre échelle est différente.": "Five by default. Set it if your scale is different.",
    "Citation": "Quotation",
    "Classe ajoutée à la page en cours de consultation.": "Class added to the page being viewed.",
    "Classe CSS contenant": "Wrapper CSS class",
    "Classe CSS du bouton": "Button CSS class",
    "Classe CSS élément": "Item CSS class",
    "Classe CSS élément actif": "Current item CSS class",
    "Classe posée sur chaque page du menu.": "Class set on every page of the menu.",
    "Classe posée sur la liste qui entoure les pages.": "Class set on the list wrapping the pages.",
    "Classes CSS": "CSS classes",
    "Classes de la feuille de style du site et des autres blocs de la page.": "Classes from the site stylesheet and from the other blocks of the page.",
    "Classes du site.": "Site classes.",
    "Cliquez pour sélectionner ce bloc, puis « Modifier le bloc » pour le régler.": "Click to select this block, then “Edit the block” to set it up.",
    "Cliquez sur un emoji pour l’insérer. Les dessins sont ceux d’OpenMoji : ils s’affichent de la même façon sur tous les appareils.": "Click an emoji to insert it. The drawings come from OpenMoji: they look the same on every device.",
    "Cliquez sur un fichier pour voir ses informations et les actions possibles. Un double clic le choisit directement.": "Click a file to see its details and what you can do with it. A double click picks it straight away.",
    "Cliquez sur une icône pour l’insérer. Elle prend la taille et la couleur du texte qui l’entoure.": "Click an icon to insert it. It takes the size and colour of the surrounding text.",
    "Cochez les réseaux à proposer. Si vous n’en cochez aucun, tous seront affichés.": "Tick the networks to offer. If you tick none, all of them are shown.",
    "Code court": "Shortcode",
    "Code de la formation": "Course code",
    "Code HTML": "HTML code",
    "Code JavaScript": "JavaScript code",
    "Code non reconnu : il sera réécrit tel quel dans la page.": "Unrecognised code: it will be written back to the page unchanged.",
    "Code postal": "Postcode",
    "Code source": "Source code",
    "Code source HTML": "HTML source code",
    "Code source HTML...": "HTML source code...",
    "Code-barres (EAN 13)": "Barcode (EAN 13)",
    "Colle un code d’intégration fourni par un service tiers": "Paste an embed code given by another service",
    "Comment passer commande ?": "How do I place an order?",
    "Commerce": "Commerce",
    "Commerce de proximité": "Local business",
    "Commercial": "Sales",
    "Compléter les langues manquantes": "Add the missing languages",
    "Compte PayPal du vendeur": "Seller’s PayPal account",
    "Conditions de livraison": "Delivery terms",
    "Conseillées": "Recommended",
    "Construction de l’aperçu…": "Building the preview…",
    "Contenu": "Content",
    "Contenu libre :": "Free content:",
    "Contenus": "Content",
    "Contour": "Outline",
    "Coordonnées géographiques": "Geographic coordinates",
    "Copie…": "Copying…",
    "Copier": "Copy",
    "Copier vers": "Copy to",
    "Copier vers…": "Copy to…",
    "Coque de carte Renault": "Renault key card cover",
    "Couleur": "Colour",
    "Couleur d’accentuation": "Accent colour",
    "Couleur de fond": "Background colour",
    "Couleur de l’ombre": "Shadow colour",
    "Couleur du filet": "Rule colour",
    "Couleur du texte": "Text colour",
    "Création…": "Creating…",
    "Créer": "Create",
    "Créer une image": "Create an image",
    "CSS personnalisé (appliqué au bloc image)": "Custom CSS (applied to the image block)",
    "Cube": "Cube",
    "Cuisine": "Cuisine",
    "Date": "Date",
    "Date de création": "Founding date",
    "Date de début": "Start date",
    "Date de dernière mise à jour": "Last updated on",
    "Date de fin": "End date",
    "Date de mise en ligne": "Upload date",
    "Date de publication": "Publication date",
    "De « € » à « €€€€ », ou une fourchette : « 15 € – 40 € ».": "From “€” to “€€€€”, or a range: “€15 – €40”.",
    "Début": "Start",
    "Débutant": "Beginner",
    "Décrire la page pour les moteurs (microdonnées)…": "Describe the page for search engines (microdata)…",
    "Décrivent le contenu de cette page pour les moteurs de recherche. Rien n’en paraît sur le site.": "Describe the content of this page for search engines. None of it appears on the site.",
    "Décrivez votre offre en une phrase.": "Describe what you offer in one sentence.",
    "Défilement": "Scrolling",
    "Défilement libre, sans s’aligner sur une vue": "Free scrolling, without snapping to a slide",
    "Définir la langue": "Set the language",
    "Définir la langue de ce bloc": "Set this block’s language",
    "Définir la langue de la sélection": "Set the selection’s language",
    "Dégradé : angle (°)": "Gradient: angle (°)",
    "Dégradé : arrivée": "Gradient: end",
    "Dégradé : couleur d’arrivée": "Gradient: end colour",
    "Dégradé : couleur de départ": "Gradient: start colour",
    "Dégradé : départ": "Gradient: start",
    "Délai annoncé": "Announced delay",
    "Déplacé en ligne": "Moved online",
    "Déplacement…": "Moving…",
    "Déplacer": "Move",
    "Déplacer cette vue": "Move this view",
    "Déplacer le bloc": "Move the block",
    "Déplacer vers": "Move to",
    "Déplacer vers…": "Move to…",
    "Déplié au chargement de la page": "Open when the page loads",
    "Déplier": "Expand",
    "Déposez vos fichiers pour les téléverser": "Drop your files to upload them",
    "Dernière vérification": "Last reviewed",
    "Descendre": "Move down",
    "Descendre cette vue": "Move this slide down",
    "Descendre le bloc": "Move block down",
    "Description": "Description",
    "Description de la page": "Page description",
    "Description pour les moteurs de recherche": "Description for search engines",
    "Dessert": "Dessert",
    "Dessiner une image…": "Draw an image…",
    "Devise": "Currency",
    "Diaporama": "Slideshow",
    "Diaporama...": "Slideshow...",
    "Dimanche": "Sunday",
    "Dimension": "Sizing",
    "Disponibilité": "Availability",
    "Disposition": "Layout",
    "Disposition des colonnes": "Column layout",
    "Document PDF": "PDF document",
    "Dollar américain (USD)": "US dollar (USD)",
    "Dollar canadien (CAD)": "Canadian dollar (CAD)",
    "Dossier de destination": "Destination folder",
    "Dossier parent": "Parent folder",
    "Droite": "Right",
    "Dupliquer cet élément": "Duplicate this item",
    "Dupliquer la ligne": "Duplicate the row",
    "Dupliquer le bloc": "Duplicate the block",
    "Durée": "Duration",
    "Durée totale": "Total duration",
    "E-mail destinataire": "Recipient e-mail",
    "Écrans": "Screens",
    "Écrire dans toutes les langues": "Write in every language",
    "Éditeur": "Publisher",
    "Effet de transition": "Transition effect",
    "Élargir la colonne": "Widen the column",
    "élément": "item",
    "Élément de liste": "List item",
    "éléments": "items",
    "Éléments du site": "Site elements",
    "Éléments du site...": "Site elements...",
    "Emoji ou icône": "Emoji or icon",
    "Emojis": "Emojis",
    "Emojis et icônes": "Emojis and icons",
    "Emojis et icônes...": "Emojis and icons...",
    "Emojis seuls": "Emojis only",
    "Emojis seuls...": "Emojis only...",
    "Emplacement dans la page": "Position in the page",
    "Emplacements": "Places",
    "Employeur": "Employer",
    "En ligne": "Online",
    "En rupture": "Out of stock",
    "En savoir plus": "Find out more",
    "En stock": "In stock",
    "En-tête de la page (<head>)": "Page head (<head>)",
    "Encadré": "Boxed",
    "Endommagé": "Damaged",
    "Enregistrer": "Save",
    "Énumération dont l’ordre compte : étapes, classement": "A list where the order matters: steps, rankings",
    "Énumération sans ordre particulier": "A list in no particular order",
    "Épuisé": "Discontinued",
    "Espace": "Space",
    "Espace entre les vignettes (px)": "Gap between thumbnails (px)",
    "Espace entre les vues (pixels)": "Space between slides (pixels)",
    "Espace vertical": "Vertical space",
    "Étape": "Step",
    "Étapes": "Steps",
    "Étapes du chemin": "Steps of the path",
    "État": "Condition",
    "État du produit": "Condition of the product",
    "Euro (EUR)": "Euro (EUR)",
    "Événement": "Event",
    "Événement non renseigné": "Event not filled in",
    "Événements": "Events",
    "Exécution différée (defer)": "Deferred execution (defer)",
    "Exigé": "Required",
    "Explorateur de fichiers": "File browser",
    "Explorateur de fichiers...": "File browser...",
    "Facturation": "Billing",
    "Faire glisser au doigt ou à la souris": "Drag with a finger or the mouse",
    "Fermer": "Close",
    "Fermeture": "Closing",
    "Fichier": "File",
    "Fichier de l’image": "Image file",
    "Fichier externe (src)": "External file (src)",
    "Fichier PDF": "PDF file",
    "fichier(s)": "file(s)",
    "fichiers": "files",
    "fichiers sélectionnés": "files selected",
    "Fil d’Ariane": "Breadcrumb",
    "Filet": "Rule",
    "Filet simple": "Plain rule",
    "Fin": "End",
    "Fin de la page (avant </body>)": "End of the page (before </body>)",
    "Fonction": "Job title",
    "Fondu": "Fade",
    "Format proportionnel": "Proportional ratio",
    "Formation": "Course",
    "Forme des points": "Shape of the dots",
    "Formulaire de contact": "Contact form",
    "Formulaire de réservation": "Booking form",
    "Formulaires": "Forms",
    "Fourchette de prix": "Price range",
    "Fournitures": "Supplies",
    "Frais de port": "Shipping cost",
    "Frais, délais et zone de livraison.": "Cost, delay and delivery area.",
    "Franc suisse (CHF)": "Swiss franc (CHF)",
    "Français": "French",
    "Française": "French",
    "Fuseau horaire": "Time zone",
    "Galerie d’images": "Image gallery",
    "Gauche": "Left",
    "Général": "General",
    "Gérant": "Manager",
    "Glissement (par défaut)": "Slide (default)",
    "Grande": "Large",
    "Grille de cellules pour présenter des données": "A grid of cells for presenting data",
    "Haut centre": "Top centre",
    "Haut droite": "Top right",
    "Haut gauche": "Top left",
    "Hauteur": "Height",
    "Hauteur (pixels)": "Height (pixels)",
    "Hauteur de la carte": "Map height",
    "Hauteur de la zone de lecture": "Height of the reading area",
    "Hauteur du séparateur": "Spacer height",
    "Hauteur fixe": "Fixed height",
    "Hauteur maximale (px)": "Maximum height (px)",
    "Hero": "Hero",
    "Heure": "Time",
    "Heure de début": "Start time",
    "Heure de fin": "End time",
    "Horaires d’ouverture": "Opening hours",
    "Horizontal": "Horizontal",
    "https://exemple.tld/photo.jpg": "https://example.tld/photo.jpg",
    "Icônes": "Icons",
    "Icônes seules": "Icons only",
    "Icônes seules...": "Icons only...",
    "Identifiant (ancre)": "Identifier (anchor)",
    "Identifiant du bloc, utilisable comme ancre": "Identifier of the block, usable as an anchor",
    "Identifiant et classes du bloc": "Identifier and classes of the block",
    "Identité": "Identity",
    "Il ne reste de la place que pour": "There is only room left for",
    "Image": "Image",
    "Image d’aperçu": "Preview image",
    "Image de fond": "Background image",
    "Image de la bibliothèque": "Image from the library",
    "Image principale": "Main image",
    "Image...": "Image...",
    "Images": "Images",
    "Images de la galerie": "Gallery images",
    "Indiquez l’adresse de l’agenda": "Enter the calendar address",
    "Indiquez l’adresse de la page à intégrer": "Enter the address of the page to embed",
    "Indiquez l’adresse de la vidéo": "Enter the video address",
    "Indre-et-Loire": "Indre-et-Loire",
    "Ingrédients": "Ingredients",
    "Insérer des colonnes": "Insert columns",
    "Insérer ou modifier un lien": "Insert or edit a link",
    "Insérer ou modifier une image": "Insert or edit an image",
    "Insérer un emoji Unicode ou une icône Material Design": "Insert a Unicode emoji or an icon",
    "Intègre un agenda public existant (Google Agenda, ICS…)": "Embeds an existing public calendar (Google Calendar, ICS…)",
    "Intérim": "Temporary",
    "Intervenant": "Performer",
    "Intitulé": "Caption",
    "Intitulé affiché": "Caption shown",
    "Intitulé du poste": "Job title",
    "Jeudi": "Thursday",
    "Jour": "Day",
    "Jour du mois": "Day of the month",
    "L’adresse à laquelle cette chose est présentée. Le plus souvent, la page courante.": "The address where this thing is presented. Most often, the current page.",
    "L’adresse à laquelle l’événement se tient à distance.": "The address where the event takes place remotely.",
    "L’adresse des conditions de réutilisation du contenu.": "The address of the reuse terms of the content.",
    "L’adresse du compte PayPal qui recevra le paiement.": "The PayPal account the payment will go to.",
    "L’adresse que l’on met dans un cadre intégré, par exemple celle d’un lecteur YouTube.": "The address put in an embedded frame, for example that of a YouTube player.",
    "L’aperçu n’a pas pu être construit": "The preview could not be built",
    "L’avis d’un client, avec sa note et son texte.": "A customer review, with its rating and its text.",
    "l’élément": "the element",
    "L’image montrée avant la lecture.": "The image shown before playback.",
    "La chose dont ce contenu parle.": "The thing this content is about.",
    "La grille d’un mois, avec vos rendez-vous inscrits jour par jour": "A month grid, with your appointments written in day by day",
    "La latitude et la longitude du lieu.": "The latitude and longitude of the place.",
    "La marque sous laquelle le produit est vendu.": "The brand the product is sold under.",
    "La mise en forme simple est acceptée : gras, liens, listes.": "Simple formatting is accepted: bold, links, lists.",
    "La moyenne des avis et leur nombre.": "The average of the reviews and how many there are.",
    "La moyenne des avis. Ce sont les étoiles affichées sous le résultat.": "The average of the reviews. These are the stars shown under the result.",
    "La recherche d’adresse n’a pas abouti. Entrez les coordonnées à la main.": "The address search failed. Enter the coordinates by hand.",
    "La seconde ligne décrit l’image : elle est lue à voix haute par les lecteurs d’écran et reprise par les moteurs de recherche.": "The second line describes the image: it is read aloud by screen readers and picked up by search engines.",
    "La section du site où l’article paraît : Actualités, Recettes, Juridique.": "The section of the site the article appears in: News, Recipes, Legal.",
    "La semaine commence le": "The week starts on",
    "Lâchez pour annuler.": "Release to cancel.",
    "Laissez vide pour afficher le bouton officiel de PayPal.": "Leave empty to show PayPal’s own button.",
    "Langue": "Language",
    "Langue du bloc": "Block language",
    "Langue du visiteur": "Visitor’s language",
    "Langues": "Languages",
    "Langues de la page": "Page languages",
    "Langues parlées": "Languages spoken",
    "Largeur": "Width",
    "Largeur (%, rem, vw...)": "Width (%, rem, vw...)",
    "Largeur (pixels)": "Width (pixels)",
    "Largeur du filet": "Rule width",
    "Largeur en pixels": "Width in pixels",
    "Largeur maximale": "Maximum width",
    "Largeur maximale (px)": "Maximum width (px)",
    "Latitude": "Latitude",
    "le bloc": "the block",
    "Le bouton « Ajouter une configuration » en pose une, à la fin de la page, avec les commandes que son html contient déjà.": "The “Add a configuration” button places one at the end of the page, with the controls its html already contains.",
    "Le chemin qui mène à cette page depuis l’accueil.": "The path leading to this page from the home page.",
    "Le chemin qui mène à la page depuis l’accueil.": "The path leading to the page from the home page.",
    "Le code ci-dessus est affiché tel quel dans l’éditeur ; il est publié sous sa forme active sur la page.": "The code above is shown as-is in the editor; it is published in working form on the page.",
    "Le code de l’unité : GRM pour un gramme, KGM pour un kilogramme, CMT pour un centimètre.": "The unit code: GRM for a gram, KGM for a kilogram, CMT for a centimetre.",
    "Le code de la langue du contenu : fr, en, nl.": "The language code of the content: fr, en, nl.",
    "Le code du pays livré : FR, BE, NL.": "The code of the delivered country: FR, BE, NL.",
    "Le code du pays sur deux lettres : FR, BE, NL.": "The two-letter country code: FR, BE, NL.",
    "Le contenu des colonnes est conservé. Une disposition qui en compte moins ramène le contenu des colonnes en trop dans la dernière.": "The content of the columns is kept. A layout with fewer of them moves the content of the extra columns into the last one.",
    "Le corps de l’article. Facultatif : les moteurs le lisent déjà dans la page.": "The body of the article. Optional: search engines already read it in the page.",
    "le dossier": "the folder",
    "le fichier": "the file",
    "Le fichier dépasse la taille maximale autorisée": "The file exceeds the maximum allowed size",
    "Le fichier dépasse le poids autorisé par votre offre": "The file exceeds the size allowed by your plan",
    "Le fuseau dans lequel les heures ci-dessus sont exprimées.": "The time zone the times above are given in.",
    "Le jour de la dernière modification. Les moteurs s’en servent pour juger de la fraîcheur.": "The day of the last change. Search engines use it to judge freshness.",
    "Le jour où le contenu a été mis en ligne.": "The day the content was published.",
    "Le jour où le contenu a été relu et confirmé exact.": "The day the content was reviewed and confirmed accurate.",
    "Le logo affiché dans les résultats de recherche. Au moins 112 pixels de côté.": "The logo shown in search results. At least 112 pixels on each side.",
    "Le logo enregistré dans les réglages de votre site": "The logo saved in your site settings",
    "Le mois en cours, quel qu’il soit au moment de l’affichage.": "The current month, whatever it is when the page is displayed.",
    "Le nom déposé, tel qu’il figure au registre du commerce.": "The registered name, as it appears in the trade register.",
    "Le nom du site, affiché par-dessus le logo": "The site name, shown over the logo",
    "Le nom sous lequel cette chose est connue. C’est ce que les moteurs affichent en titre.": "The name this thing is known by. This is what search engines show as the title.",
    "Le plugin des scripts n’est pas chargé : la configuration ne peut pas être ajoutée depuis ici. Écrivez-la dans le gabarit du site.": "The scripts plugin is not loaded: the configuration cannot be added from here. Write it in the site template.",
    "Le résumé et les mots-clés affichés par Google — invisible sur la page": "The summary and keywords shown by Google — invisible on the page",
    "le script": "the script",
    "Le site dans son ensemble. À poser sur la page d’accueil.": "The site as a whole. To be placed on the home page.",
    "Le texte d’une réponse.": "The text of an answer.",
    "Le texte décrit l’image : il est lu à voix haute par les lecteurs d’écran et repris par les moteurs de recherche.": "The text describes the image: screen readers read it aloud and search engines pick it up.",
    "Le titre du contenu. Restez sous 110 caractères : au-delà, les moteurs le coupent.": "The title of the content. Stay under 110 characters: past that, search engines cut it.",
    "Le type le plus général : à n’employer que si aucun autre ne convient.": "The most general type: to be used only if no other fits.",
    "Lecture automatique": "Play automatically",
    "Lecture en boucle": "Loop",
    "Légende": "Caption",
    "Les classes de la feuille de style du site n’ont pas pu être lues : elle est servie par un autre domaine, qui n’en autorise pas la lecture. Écrivez le nom de la classe à la main.": "The classes of the site stylesheet could not be read: it is served by another domain, which does not allow reading it. Write the class name by hand.",
    "Les classes décident de l’allure du bloc. Celles qui sont proposées viennent de la feuille de style de votre site et des autres blocs de la page.": "The classes decide the look of the block. Those offered come from the stylesheet of your site and from the other blocks of the page.",
    "Les deux": "Both",
    "Les effets autres que le glissement demandent leur module dans la page. Si le diaporama se fige après un changement d’effet, revenez au glissement.": "Effects other than slide need their module in the page. If the slideshow freezes after an effect change, go back to slide.",
    "les microdonnées de cette page": "the microdata of this page",
    "Les moteurs de recherche affichent un prix, des étoiles ou une date de concert quand la page le leur dit dans un langage qu’ils connaissent. Choisissez ce qui correspond le mieux — vous pourrez en changer.": "Search engines show a price, stars or a concert date when the page tells them so in a language they know. Choose what fits best — you can change it later.",
    "Les moteurs de recherche mettent à disposition un outil qui lit une page publiée et dit ce qu’ils y comprennent. Publiez d’abord la page, puis donnez-lui son adresse.": "Search engines provide a tool that reads a published page and says what they understand from it. Publish the page first, then give it its address.",
    "Les moteurs ignoreront la fiche tant qu’elles manqueront. L’enregistrer quand même ?": "Search engines will ignore the record while they are missing. Save it anyway?",
    "Les propriétés marquées « Exigé » doivent être remplies pour que les moteurs acceptent la fiche. Les autres l’enrichissent.": "The properties marked “Required” must be filled in for search engines to accept the record. The others enrich it.",
    "Les propriétés marquées « Obligatoire » doivent être remplies pour que les moteurs acceptent la fiche. Les autres l’enrichissent.": "The properties marked “Required” must be filled in for search engines to accept the record. The others enrich it.",
    "Les rendez-vous d’avril": "April’s appointments",
    "Licence": "Licence",
    "Lien": "Link",
    "Lien du bouton": "Button link",
    "Lien du site": "Site link",
    "Lien...": "Link...",
    "Lieu": "Place",
    "Lieu affiché": "Place shown",
    "Lieu choisi. Ajustez le zoom si nécessaire.": "Place chosen. Adjust the zoom if needed.",
    "Lieu de travail": "Place of work",
    "Lieu en ligne": "Online location",
    "Lieu et date de rédaction": "Place and date of writing",
    "Liste à puces": "Bulleted list",
    "Liste des pages de votre site": "The list of your site’s pages",
    "Liste numérotée": "Numbered list",
    "Livraison": "Delivery",
    "Livre sterling (GBP)": "Pound sterling (GBP)",
    "Logo": "Logo",
    "Logo du site": "Site logo",
    "Longitude": "Longitude",
    "Lundi": "Monday",
    "Maçonnerie (colonnes)": "Masonry (columns)",
    "Maintenez enfoncé pendant {0} secondes.": "Press and hold for {0} seconds.",
    "Maintenez le bouton enfoncé pour supprimer": "Press and hold the button to delete",
    "Maintenu": "Scheduled",
    "Mardi": "Tuesday",
    "Marge extérieure (ex : 0 0 1rem)": "Outer margin (e.g. 0 0 1rem)",
    "Marge intérieure (ex : .5rem 1rem)": "Inner padding (e.g. .5rem 1rem)",
    "Marque": "Brand",
    "Matière": "Material",
    "Matières grasses": "Fat content",
    "maximum": "maximum",
    "Médias": "Media",
    "Médiathèque": "Media library",
    "Même onglet": "Same tab",
    "Menu": "Menu",
    "menu, contact, partage…": "menu, contact, sharing…",
    "Mercredi": "Wednesday",
    "Mesure": "Measurement",
    "Met en avant une phrase, avec un filet sur le côté": "Highlights a sentence, with a rule down the side",
    "Mettre à jour": "Update",
    "Microdonnées": "Microdata",
    "Microdonnées de la page": "Microdata of the page",
    "Microdonnées incomplètes": "Incomplete microdata",
    "Milieu droite": "Middle right",
    "Milieu gauche": "Middle left",
    "Mise en avant": "Highlights",
    "Mode d’emploi": "How-to",
    "Mode de participation": "Attendance mode",
    "Modifier cet élément": "Edit this item",
    "Modifier dans Pixel•OnlineCreation": "Edit in Pixel•OnlineCreation",
    "Modifier la description pour les moteurs…": "Edit the description for search engines…",
    "Modifier le bloc": "Edit the block",
    "Modifier le diaporama": "Edit the slideshow",
    "Modifier le lien": "Edit the link",
    "Modifier le script": "Edit the script",
    "Modifier les microdonnées": "Edit the microdata",
    "Modifier les microdonnées de la page…": "Edit the microdata of the page…",
    "Modifier…": "Edit…",
    "Mois": "Month",
    "Mois affiché": "Month shown",
    "Mois en cours": "Current month",
    "Montant": "Amount",
    "Monter": "Move up",
    "Monter cette vue": "Move this slide up",
    "Monter le bloc": "Move block up",
    "Mosaïque carrée": "Square mosaic",
    "Mots-clés": "Keywords",
    "Nature de la prestation": "Kind of service",
    "Navigation": "Navigation",
    "Ne pas supprimer": "Do not delete",
    "Neuf": "New",
    "Neuf, d’occasion, reconditionné. Les moteurs l’affichent à côté du prix, et une place de marché peut le refuser s’il manque.": "New, used, refurbished. Search engines show it next to the price, and a marketplace may reject the listing without it.",
    "Niveau": "Level",
    "Niveau de prix": "Price level",
    "Nom": "Name",
    "Nom d’une classe, par exemple text-center": "Name of a class, for example text-center",
    "Nom de famille": "Family name",
    "Nom de l’article": "Item name",
    "Nom de l’événement": "Event name",
    "Nom du dossier": "Folder name",
    "Nom du widget": "Widget name",
    "Nom exact de la propriété schema.org, par exemple award :": "Exact name of the schema.org property, for example award:",
    "Nombre d’avis": "Number of reviews",
    "Nombre d’offres": "Number of offers",
    "Nombre de mots": "Word count",
    "Nombre de pages affichées (0 = toutes)": "Number of pages shown (0 = all)",
    "Non": "No",
    "Non pour un contenu réservé aux abonnés.": "No for content reserved for subscribers.",
    "Normale": "Normal",
    "Nos bureaux": "Our offices",
    "Note": "Rating",
    "Note donnée": "Rating given",
    "Note maximale": "Best rating",
    "Note minimale": "Worst rating",
    "Note moyenne": "Average rating",
    "Nouveau dossier": "New folder",
    "Nouveau nom": "New name",
    "Nouvel onglet": "New tab",
    "Numéro d’identification": "Tax identification number",
    "Numéro de TVA": "VAT number",
    "Numéro de vue": "Slide number",
    "Numéro et rue": "Number and street",
    "Occasion": "Used",
    "Œuvre": "Creative work",
    "Offre": "Offer",
    "Offre d’emploi": "Job posting",
    "Ombre : couleur": "Shadow: colour",
    "Ombre : décalage horizontal": "Shadow: horizontal offset",
    "Ombre : décalage vertical": "Shadow: vertical offset",
    "Ombre : flou": "Shadow: blur",
    "Ombre : X": "Shadow: X",
    "Ombre : Y": "Shadow: Y",
    "Ordinateur": "Desktop",
    "Organisateur": "Organiser",
    "Organisation": "Organisation",
    "Organisme": "Provider",
    "Ou adresse d’une image en ligne (https://…)": "Or the address of an online image (https://…)",
    "Oui": "Yes",
    "Outil de test des moteurs…": "Search engine test tool…",
    "Outils de blocs": "Block tools",
    "Outils nécessaires": "Tools needed",
    "Ouverture": "Opening",
    "Ouvrir dans": "Open in",
    "Ouvrir le lien": "Open the link",
    "Page actuelle (ancres)": "This page (anchors)",
    "Page intégrée": "Embedded page",
    "Page intégrée (iframe)": "Embedded page (iframe)",
    "Page web": "Web page",
    "Page Wikipédia, profil Facebook, fiche Google : les adresses qui désignent la même chose ailleurs.": "Wikipedia page, Facebook profile, Google listing: the addresses that name the same thing elsewhere.",
    "panier, téléphone, flèche…": "basket, phone, arrow…",
    "Paragraphe": "Paragraph",
    "Paragraphe, image, colonnes…": "Paragraph, image, columns…",
    "Parallaxe": "Parallax",
    "Pays": "Country",
    "Peintre carrossier": "Vehicle paint sprayer",
    "Peinture automobile": "Vehicle paint spraying",
    "Personnalisé (adresse)": "Custom (address)",
    "Personnalisées": "Custom",
    "Personne": "Person",
    "Perspective": "Coverflow",
    "Petite": "Small",
    "Pixel•OnlineCreation, l’éditeur d’images": "Pixel•OnlineCreation, the image editor",
    "Pixels": "Pixels",
    "Plage d’ouverture": "Opening period",
    "Plan OpenStreetMap": "OpenStreetMap plan",
    "Planning": "Schedule",
    "Plein écran": "Full screen",
    "Pleine largeur": "Full width",
    "Plusieurs offres pour le même produit : du moins cher au plus cher.": "Several offers for the same product: from the cheapest to the dearest.",
    "Plusieurs photos présentées en mosaïque, avec agrandissement au clic": "Several photos shown as a mosaic, enlarged on click",
    "Poids": "Weight",
    "Point de contact": "Contact point",
    "Points": "Dots",
    "Police du site": "Site font",
    "Portes ouvertes": "Open day",
    "Position sur l’image": "Position on the image",
    "Pour combien de personnes": "For how many people",
    "Précommande": "Pre-order",
    "Prénom": "Given name",
    "Présentation": "Presentation",
    "Presse": "Press",
    "Prestataire": "Provider",
    "Prestation": "Service",
    "Principal": "Primary",
    "Prix": "Price",
    "Prix et disponibilité": "Price and availability",
    "Prix le plus bas": "Lowest price",
    "Prix le plus haut": "Highest price",
    "Prix valable jusqu’au": "Price valid until",
    "Produit": "Product",
    "Proportions": "Aspect ratio",
    "Proposer le téléchargement du fichier": "Offer the file for download",
    "propriété": "property",
    "Propriété écrite à la main : l’éditeur ne la connaît pas et ne peut donc pas la vérifier.": "Property written by hand: the editor does not know it and therefore cannot check it.",
    "propriétés": "properties",
    "Propriétés de l’image": "Image properties",
    "Propriétés du bloc": "Block properties",
    "Protéines": "Protein content",
    "Que décrit cette page ?": "What does this page describe?",
    "Quelques phrases qui décrivent la chose. Souvent reprise sous le titre dans les résultats.": "A few sentences describing the thing. Often shown under the title in results.",
    "Question": "Question",
    "Questions": "Questions",
    "Questions fréquentes": "Frequently asked questions",
    "Qui a écrit ce contenu : une personne, ou l’entreprise elle-même.": "Who wrote this content: a person, or the company itself.",
    "Qui publie ce contenu — le plus souvent votre entreprise.": "Who publishes this content — most often your company.",
    "Quitter le plein écran": "Leave full screen",
    "Raison sociale": "Legal name",
    "Rang": "Position",
    "Rapport": "Ratio",
    "Rapport largeur / hauteur": "Width / height ratio",
    "Recette": "Recipe",
    "Recherche en cours…": "Searching…",
    "Rechercher": "Search",
    "Rechercher dans ce dossier": "Search in this folder",
    "Rechercher dans ce dossier…": "Search in this folder…",
    "Rechercher un bloc": "Search for a block",
    "Recommandé : un diaporama qui repart tout seul pendant qu’on le regarde est pénible, et empêche de revenir en arrière.": "Recommended: a slideshow that starts again on its own while you are looking at it is annoying, and prevents going back.",
    "Reconditionné": "Refurbished",
    "Réduire": "Shrink",
    "Référence": "Identifier",
    "Référence (SKU)": "Reference (SKU)",
    "Référence du fabricant": "Manufacturer reference",
    "Référencement": "Search engines",
    "Référencement de la page": "Search-engine settings of the page",
    "Région ou département": "Region or county",
    "Réglages": "Settings",
    "réglages retrouvés": "settings found",
    "Relation (rel)": "Relationship (rel)",
    "Rémunération": "Salary",
    "Rendez-vous du mois": "This month’s appointments",
    "Renommage…": "Renaming…",
    "Renommer": "Rename",
    "Renommer le fichier": "Rename the file",
    "Renommer…": "Rename…",
    "Repartir au début après la dernière vue": "Start again after the last slide",
    "Replier": "Collapse",
    "Réponse": "Answer",
    "Reporté": "Postponed",
    "Réseaux sociaux": "Social networks",
    "Restauration…": "Restoring…",
    "Restaurer": "Restore",
    "Retirer": "Remove",
    "Retirer ce palier": "Remove this breakpoint",
    "Retirer cette image": "Remove this image",
    "Retirer cette valeur": "Remove this value",
    "Retirer cette vue": "Remove this slide",
    "Retoucher cette image…": "Retouch this image…",
    "Retoucher l’image…": "Retouch the image…",
    "Retour à": "Back to",
    "Retournement": "Flip",
    "Rétrécir la colonne": "Narrow the column",
    "return confirm('Quitter la page ?')": "return confirm('Leave the page?')",
    "Rien de renseigné": "Nothing filled in",
    "Rubrique": "Section",
    "Rubrique de l’édition papier": "Print section",
    "S’arrêter dès que le visiteur y touche": "Stop as soon as the visitor touches it",
    "Saisissez d’abord une adresse.": "Type an address first.",
    "Saisissez une adresse et cliquez sur « Rechercher », ou entrez directement des coordonnées.": "Type an address and click “Search”, or enter coordinates directly.",
    "Samedi": "Saturday",
    "Sans bordure": "Borderless",
    "Sans empattement": "Sans serif",
    "Sans le son": "Muted",
    "sans réglages dans la page": "no settings in the page",
    "Sans symbole ni espace : 28 ou 28.50. La devise est indiquée à côté.": "Without a symbol or a space: 28 or 28.50. The currency is set alongside.",
    "Script JavaScript": "JavaScript script",
    "Script JavaScript...": "JavaScript script...",
    "script vide": "empty script",
    "Secondaire": "Secondary",
    "Section de langue": "Language section",
    "Sélectionner le bloc parent": "Select the parent block",
    "Sélectionnez du texte pour lui donner une langue": "Select some text to give it a language",
    "Semaine": "Week",
    "Sens du défilement": "Scrolling direction",
    "Séparateur": "Spacer",
    "Séparateur réglable": "Adjustable spacer",
    "Séparateur vertical": "Vertical spacer",
    "Séparateur vertical...": "Vertical spacer...",
    "Sépare visuellement deux parties de la page": "Visually separates two parts of the page",
    "Séparés par des virgules.": "Separated by commas.",
    "Séparés par des virgules. Ils décrivent le sujet, pas la page.": "Separated by commas. They describe the subject, not the page.",
    "Service": "Service",
    "Service à contacter": "Service to contact",
    "Service client": "Customer service",
    "Site web": "Web site",
    "Situe une adresse sur un plan OpenStreetMap": "Pinpoints an address on an OpenStreetMap map",
    "Sorte de lien": "Kind of link",
    "Souligné": "Underlined",
    "Source (lien)": "Source (link)",
    "sourire, cœur, drapeau…": "smile, heart, flag…",
    "Sous-titre": "Subtitle",
    "Sous-titre à l’intérieur d’une section": "A subheading inside a section",
    "Stage": "Internship",
    "Style": "Style",
    "Style CSS écrit à même le lien": "CSS style written on the link itself",
    "Style du lien": "Link style",
    "Style du texte": "Text style",
    "Style prédéfini": "Ready-made style",
    "Sujet": "Subject",
    "Suppression dans {0} secondes": "Deleting in {0} seconds",
    "Suppression…": "Deleting…",
    "Supprimer": "Delete",
    "Supprimer ce dossier": "Delete this folder",
    "Supprimer cet élément": "Delete this item",
    "Supprimer la colonne": "Delete the column",
    "Supprimer la fiche": "Delete the record",
    "Supprimer la ligne et ses colonnes": "Delete the row and its columns",
    "Supprimer le bloc": "Delete the block",
    "Supprimer le lien": "Remove the link",
    "Supprimer le script": "Delete the script",
    "Supprimer le séparateur": "Delete the spacer",
    "Supprimer les microdonnées": "Delete the microdata",
    "Sur commande": "On back order",
    "Sur place": "On site",
    "Survolez le bloc puis cliquez sur « Modifier le diaporama » pour changer les vues et le défilement.": "Hover over the block, then click “Edit the slideshow” to change the views and the scrolling.",
    "Système": "Operating system",
    "Tableau": "Table",
    "Tablette": "Tablet",
    "Taille": "Size",
    "Taille d’une portion": "Serving size",
    "Taille des vignettes (px)": "Thumbnail size (px)",
    "Taille du texte (ex : 1.5rem)": "Text size (e.g. 1.5rem)",
    "Tailles rapides": "Quick sizes",
    "Tarif": "Price",
    "tarifs": "prices",
    "Téléphone": "Phone",
    "Téléversement…": "Uploading…",
    "Téléverser…": "Upload…",
    "Temps d’arrêt sur chaque vue (millisecondes)": "Pause on each slide (milliseconds)",
    "Temps de cuisson": "Cooking time",
    "Temps de préparation": "Preparation time",
    "Temps partiel": "Part time",
    "Temps plein": "Full time",
    "Texte": "Text",
    "Texte à afficher": "Text to show",
    "Texte affiché par-dessus l’image": "Text shown over the image",
    "Texte alternatif": "Alternative text",
    "Texte alternatif (lu par les lecteurs d’écran)": "Alternative text (read by screen readers)",
    "Texte de l’article": "Article body",
    "Texte de l’avis": "Review body",
    "Texte de l’épingle": "Pin text",
    "Texte de la réponse": "Text of the answer",
    "Texte de remplacement": "Alternative text",
    "Texte déplié": "Text revealed",
    "Texte déployable": "Expandable text",
    "Texte du bouton": "Button text",
    "Texte par-dessus": "Text on top",
    "Titre": "Title",
    "Titre (accessibilité)": "Title (accessibility)",
    "Titre affiché": "Title shown",
    "Titre affiché au survol": "Title shown on hover",
    "Titre cliquable": "Clickable heading",
    "Titre de niveau 2": "Heading level 2",
    "Titre de niveau 3": "Heading level 3",
    "Titre du lien": "Link title",
    "Titre du lien (bulle d’aide au survol)": "Link title (tooltip on hover)",
    "Titre du site avec son logo": "Site name with its logo",
    "Titre principal d’une section": "The main heading of a section",
    "Tours, 14 mars 2026": "Tours, 14 March 2026",
    "Tous": "All",
    "Tous les réseaux": "All networks",
    "Tout ce qu’il contient sera perdu.": "Everything it contains will be lost.",
    "Tout détruire": "Destroy everything",
    "Toutes": "All",
    "Toutes les langues": "All languages",
    "Toutes ses versions seront perdues.": "All of its versions will be lost.",
    "Trait horizontal": "Horizontal rule",
    "Travailler dans une seule langue": "Work in a single language",
    "Type": "Type",
    "Type de contrat": "Employment type",
    "Type de cuisine": "Cuisine served",
    "type inconnu": "unknown type",
    "Type MIME": "MIME type",
    "Types acceptés": "Accepted types",
    "Typographie": "Typeface",
    "Un article à vendre : son prix, sa disponibilité, ses avis.": "An item for sale: its price, its availability, its reviews.",
    "Un article d’actualité, daté et signé.": "A news article, dated and signed.",
    "Un article publié au fil de l’eau sur un blog.": "An article published as it comes on a blog.",
    "Un bloc de texte courant": "A plain block of text",
    "Un bouton « Acheter » qui ouvre le paiement PayPal": "A “Buy” button that opens PayPal checkout",
    "Un bouton qui enregistre votre événement dans l’agenda du visiteur": "A button that saves your event to the visitor’s calendar",
    "Un bouton qui met en avant l’action principale": "A button that highlights the main action",
    "Un code qui désigne cette chose sans ambiguïté : référence interne, numéro de catalogue.": "A code that names this thing unambiguously: internal reference, catalogue number.",
    "Un contenu créé : texte, image, vidéo, logiciel.": "Created content: text, image, video, software.",
    "Un cours ou une formation proposée.": "A course or a training offered.",
    "Un endroit : salle, monument, parking.": "A place: venue, monument, car park.",
    "Un espace vertical ou un filet de séparation": "Vertical space, or a separating rule",
    "Un établissement où l’on se rend : boutique, cabinet, restaurant.": "A place people go to: shop, practice, restaurant.",
    "Un formulaire dont les messages arrivent dans votre boîte mail": "A form whose messages land in your mailbox",
    "Un identifiant commence par une lettre et ne contient ni espace ni accent. Par exemple : tarifs, nos-services, contact2.": "An identifier starts with a letter and contains neither space nor accent. For example: prices, our-services, contact2.",
    "Un jour ou un groupe de jours, avec l’heure d’ouverture et de fermeture.": "A day or a group of days, with the opening and closing time.",
    "Un logiciel ou une application mobile.": "A piece of software or a mobile application.",
    "Un mot sans espace, unique dans la page. Un lien pourra y conduire avec « #tarifs », et les scripts du site s’en servent pour retrouver ce bloc.": "One word without a space, unique in the page. A link can lead to it with “#prices”, and the scripts of the site use it to find this block.",
    "Un nombre entier (3), un nombre décimal pour laisser deviner la suivante (1.15), ou « auto » pour suivre la largeur de chaque vue.": "A whole number (3), a decimal to hint at the next one (1.15), or “auto” to follow the width of each slide.",
    "Un poste à pourvoir.": "A position to fill.",
    "Un pour l’accueil, deux pour la rubrique, et ainsi de suite.": "One for the home page, two for the section, and so on.",
    "Un prix, une devise et une disponibilité.": "A price, a currency and an availability.",
    "Un second nom sous lequel la chose est aussi connue.": "A second name the thing is also known by.",
    "Un service et la façon de le joindre.": "A department and how to reach it.",
    "Un service proposé plutôt qu’un objet vendu.": "A service offered rather than an object sold.",
    "Un texte de fond : billet, dossier, tribune.": "An in-depth text: post, feature, opinion piece.",
    "Un titre accrocheur": "A headline that catches the eye",
    "Un titre cliquable qui déplie un texte : idéal pour une foire aux questions": "A clickable heading that reveals text: ideal for a FAQ",
    "Un titre et un texte éditables directement dans la page": "A heading and text edited straight in the page",
    "Une à deux phrases, environ 160 caractères : c’est le texte affiché sous le titre dans les résultats de recherche.": "One or two sentences, about 160 characters: this is the text shown under the title in search results.",
    "Une adresse complète, telle qu’on l’écrit sur une enveloppe.": "A full address, as written on an envelope.",
    "Une autre propriété, écrite à la main…": "Another property, written by hand…",
    "Une citation mise en avant avec son auteur": "A highlighted quotation with its author",
    "Une date à retenir : concert, portes ouvertes, formation.": "A date to remember: concert, open day, training.",
    "Une entreprise, une association, une administration.": "A company, an association, a public body.",
    "Une étape du fil d’Ariane : sa position, son nom et son adresse.": "A step of the breadcrumb: its position, its name and its address.",
    "Une étape du mode d’emploi.": "A step of the how-to.",
    "Une image avec sa légende et un lien optionnel": "An image with its caption and an optional link",
    "Une image décrite pour elle-même : auteur, licence, dimensions.": "An image described for itself: author, licence, dimensions.",
    "Une ligne de colonnes côte à côte, qui s’empilent sur mobile": "A row of side-by-side columns that stack on mobile",
    "Une marche à suivre, étape par étape.": "A procedure, step by step.",
    "Une note isolée, celle d’un avis.": "A single rating, that of one review.",
    "Une page de questions-réponses. Les moteurs les affichent dépliables.": "A question and answer page. Search engines show them as expandable.",
    "Une page ordinaire du site : présentation, mentions légales, contact.": "An ordinary page of the site: about, legal notice, contact.",
    "Une personne : auteur, dirigeant, artisan.": "A person: author, director, craftsperson.",
    "Une photo qui représente la chose. Les moteurs préfèrent une image large, d’au moins 1200 pixels.": "A photo that represents the thing. Search engines prefer a wide image, at least 1200 pixels.",
    "Une phrase qui marque les esprits.": "A sentence people remember.",
    "Une question et sa réponse.": "A question and its answer.",
    "Une recette de cuisine, avec ses ingrédients et ses étapes.": "A cooking recipe, with its ingredients and its steps.",
    "Une somme et sa devise.": "An amount and its currency.",
    "Une valeur avec son unité : un poids, une longueur.": "A value with its unit: a weight, a length.",
    "Une vidéo hébergée ou intégrée dans la page.": "A video hosted or embedded in the page.",
    "Unité": "Unit",
    "Utiliser ce fichier": "Use this file",
    "Utiliser ces fichiers": "Use these files",
    "Valeur": "Value",
    "Valeurs nutritionnelles": "Nutrition information",
    "Veigné": "Veigné",
    "Vendeur": "Seller",
    "Vendredi": "Friday",
    "Vérification des quotas…": "Checking quotas…",
    "Vérifier la fiche": "Check the record",
    "Version": "Version",
    "Version enregistrée": "Saved version",
    "Version publiée uniquement en": "Version published only in",
    "Versions": "Versions",
    "Vertical": "Vertical",
    "Vidéo": "Video",
    "Vider": "Clear",
    "Videz ce champ pour la retirer.": "Empty this field to remove it.",
    "Ville": "Town",
    "Vintage": "Vintage",
    "Voile sombre (0 à 100)": "Dark overlay (0 to 100)",
    "Votre médiathèque est pleine. Supprimez des fichiers ou d’anciennes versions pour en ajouter.": "Your library is full. Delete files or old versions to add more.",
    "Votre référence interne, celle du bon de commande.": "Your internal reference, the one on the order form.",
    "Vous modifiez": "You are editing",
    "Vue": "Slide",
    "vue n’a pas d’image et ne montrerait rien sur le site. La retirer ?": "slide has no image and would show nothing on the site. Remove it?",
    "Vues affichées en même temps": "Slides shown at the same time",
    "vues n’ont pas d’image et ne montreraient rien sur le site. Les retirer ?": "slides have no image and would show nothing on the site. Remove them?",
    "Widget HTML": "HTML widget",
    "YouTube, Vimeo, Dailymotion ou toute autre adresse intégrable": "YouTube, Vimeo, Dailymotion or any other embeddable address",
    "Zone desservie": "Area served",
    "Zone livrée": "Delivery area",
    "Zoom (1 = monde, 19 = rue)": "Zoom (1 = world, 19 = street)",
    "Zoom à la molette de la souris": "Zoom with the mouse wheel"
});
/* — ONLC : fin des chaînes des plugins — */
