/**
 * Paquet de langue « es_MX » de l'interface HugeRTE.
 *
 * Produit par tools/i18n/build-langs.js à partir des traductions de TinyMCE 6 (licence MIT,
 * © Tiny Technologies Inc. et les contributeurs). Ne pas modifier à la main : reprenez le
 * générateur, ou surchargez les chaînes voulues avec hugerte.addI18n() dans votre page.
 */
hugerte.addI18n("es_MX", {
    "Redo": "Rehacer",
    "Undo": "Deshacer",
    "Cut": "Cortar",
    "Copy": "Copiar",
    "Paste": "Pegar",
    "Select all": "Seleccionar todo",
    "New document": "Nuevo documento",
    "Ok": "Aceptar",
    "Cancel": "Cancelar",
    "Visual aids": "Ayudas visuales",
    "Bold": "Negrita",
    "Italic": "Cursiva",
    "Underline": "Subrayado",
    "Strikethrough": "Tachado",
    "Superscript": "Super\xedndice",
    "Subscript": "Sub\xedndice",
    "Clear formatting": "Borrar formato",
    "Remove": "Quitar",
    "Align left": "Alinear a la izquierda",
    "Align center": "Alinear al centro",
    "Align right": "Alinear a la derecha",
    "No alignment": "Sin alineaci\xf3n",
    "Justify": "Justificar",
    "Bullet list": "Lista de vi\xf1etas",
    "Numbered list": "Lista numerada",
    "Decrease indent": "Reducir sangr\xeda",
    "Increase indent": "Aumentar sangr\xeda",
    "Close": "Cerrar",
    "Formats": "Formatos",
    "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "Su navegador no admite el acceso directo al portapapeles. En su lugar, use los m\xe9todos abreviados Ctrl+X/C/V del teclado",
    "Headings": "Encabezados",
    "Heading 1": "Encabezado 1",
    "Heading 2": "Encabezado 2",
    "Heading 3": "Encabezado 3",
    "Heading 4": "Encabezado 4",
    "Heading 5": "Encabezado 5",
    "Heading 6": "Encabezado 6",
    "Preformatted": "Con formato previo",
    "Div": "Div",
    "Pre": "Pre",
    "Code": "C\xf3digo",
    "Paragraph": "P\xe1rrafo",
    "Blockquote": "Cita en bloque",
    "Inline": "En l\xednea",
    "Blocks": "Bloques",
    "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Pegar ahora est\xe1 en modo de texto sin formato. El contenido ahora se pegar\xe1 como texto sin formato hasta que desactive esta opci\xf3n",
    "Fonts": "Fuentes",
    "Font sizes": "Tama\xf1os de fuente",
    "Class": "Clase",
    "Browse for an image": "Buscar una imagen",
    "OR": "O",
    "Drop an image here": "Soltar una imagen aqu\xed",
    "Upload": "Subir",
    "Uploading image": "Subiendo imagen",
    "Block": "Bloque",
    "Align": "Alinear",
    "Default": "Predeterminado",
    "Circle": "C\xedrculo",
    "Disc": "Disco",
    "Square": "Cuadrado",
    "Lower Alpha": "Alfab\xe9tico en min\xfasculas",
    "Lower Greek": "Griego en min\xfasculas",
    "Lower Roman": "Romano en min\xfasculas",
    "Upper Alpha": "Alfab\xe9tico en may\xfasculas",
    "Upper Roman": "Romano en may\xfasculas",
    "Anchor...": "Ancla...",
    "Anchor": "Ancla",
    "Name": "Nombre",
    "ID": "ID",
    "ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "El ID debe comenzar con una letra, seguido solo de letras, n\xfameros, guiones, puntos, dos puntos o guiones bajos",
    "You have unsaved changes are you sure you want to navigate away?": "No se han guardado los cambios. \xbfSeguro que desea abandonar la p\xe1gina?",
    "Restore last draft": "Restaurar el \xfaltimo borrador",
    "Special character...": "Car\xe1cter especial...",
    "Special Character": "Car\xe1cter especial",
    "Source code": "C\xf3digo fuente",
    "Insert/Edit code sample": "Insertar/editar ejemplo de c\xf3digo",
    "Language": "Idioma",
    "Code sample...": "Ejemplo de c\xf3digo...",
    "Left to right": "De izquierda a derecha",
    "Right to left": "De derecha a izquierda",
    "Title": "T\xedtulo",
    "Fullscreen": "Pantalla completa",
    "Action": "Acci\xf3n",
    "Shortcut": "Atajo",
    "Help": "Ayuda",
    "Address": "Direcci\xf3n",
    "Focus to menubar": "Llevar el foco a la barra de men\xfas",
    "Focus to toolbar": "Llevar el foco a la barra de herramientas",
    "Focus to element path": "Llevar el foco a la ruta de acceso del elemento",
    "Focus to contextual toolbar": "Llevar el foco a la barra de herramientas contextual",
    "Insert link (if link plugin activated)": "Insertar v\xednculo (si el complemento de v\xednculos est\xe1 activado)",
    "Save (if save plugin activated)": "Guardar (si el complemento de guardar est\xe1 activado)",
    "Find (if searchreplace plugin activated)": "Buscar (si el complemento de buscar y reemplazar est\xe1 activado)",
    "Plugins installed ({0}):": "Complementos instalados ({0}):",
    "Premium plugins:": "Complementos premium:",
    "Learn more...": "M\xe1s informaci\xf3n...",
    "You are using {0}": "Est\xe1 usando {0}",
    "Plugins": "Complementos",
    "Handy Shortcuts": "Atajos \xfatiles",
    "Horizontal line": "L\xednea horizontal",
    "Insert/edit image": "Insertar/editar imagen",
    "Alternative description": "Descripci\xf3n alternativa",
    "Accessibility": "Accesibilidad",
    "Image is decorative": "La imagen es decorativa",
    "Source": "Origen",
    "Dimensions": "Dimensiones",
    "Constrain proportions": "Restringir proporciones",
    "General": "General",
    "Advanced": "Avanzado",
    "Style": "Estilo",
    "Vertical space": "Espacio vertical",
    "Horizontal space": "Espacio horizontal",
    "Border": "Borde",
    "Insert image": "Insertar imagen",
    "Image...": "Imagen...",
    "Image list": "Lista de im\xe1genes",
    "Resize": "Cambiar tama\xf1o",
    "Insert date/time": "Insertar fecha/hora",
    "Date/time": "Fecha/hora",
    "Insert/edit link": "Insertar/editar v\xednculo",
    "Text to display": "Texto a mostrar",
    "Url": "Url",
    "Open link in...": "Abrir enlace en...",
    "Current window": "Ventana actual",
    "None": "Ninguno",
    "New window": "Nueva ventana",
    "Open link": "Abrir enlace",
    "Remove link": "Eliminar v\xednculo",
    "Anchors": "Anclajes",
    "Link...": "Enlace...",
    "Paste or type a link": "Pegar o escribir un enlace",
    "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "La URL que introdujo parece ser una direcci\xf3n de correo electr\xf3nico. \xbfDesea a\xf1adir el prefijo mailto: correspondiente?",
    "The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "La URL que introdujo parece ser un v\xednculo externo. \xbfDesea a\xf1adir el prefijo http:// correspondiente?",
    "The URL you entered seems to be an external link. Do you want to add the required https:// prefix?": "La URL que ingres\xf3 parece ser un enlace externo. Desea agregar el prefijo requerido https://?",
    "Link list": "Lista de enlaces",
    "Insert video": "Insertar video",
    "Insert/edit video": "Insertar/editar video",
    "Insert/edit media": "Insertar/editar elemento multimedia",
    "Alternative source": "Origen alternativo",
    "Alternative source URL": "URL de origen alternativo",
    "Media poster (Image URL)": "P\xf3ster multimedia (URL de la imagen)",
    "Paste your embed code below:": "Pegue el c\xf3digo para insertar debajo:",
    "Embed": "Insertar",
    "Media...": "Elemento multimedia...",
    "Nonbreaking space": "Espacio de no separaci\xf3n",
    "Page break": "Salto de p\xe1gina",
    "Paste as text": "Pegar como texto",
    "Preview": "Vista previa",
    "Print": "Imprimir",
    "Print...": "Imprimir...",
    "Save": "Guardar",
    "Find": "Buscar",
    "Replace with": "Remplazar con",
    "Replace": "Remplazar",
    "Replace all": "Remplazar todo",
    "Previous": "Anterior",
    "Next": "Siguiente",
    "Find and Replace": "Buscar y reemplazar",
    "Find and replace...": "Buscar y reemplazar...",
    "Could not find the specified string.": "No se ha encontrado la cadena indicada.",
    "Match case": "Coincidir may\xfasculas y min\xfasculas",
    "Find whole words only": "Buscar solo palabras completas",
    "Find in selection": "Buscar en la selecci\xf3n",
    "Insert table": "Insertar tabla",
    "Table properties": "Propiedades de tabla",
    "Delete table": "Eliminar tabla",
    "Cell": "Celda",
    "Row": "Fila",
    "Column": "Columna",
    "Cell properties": "Propiedades de celda",
    "Merge cells": "Combinar celdas",
    "Split cell": "Dividir celdas",
    "Insert row before": "Insertar fila antes",
    "Insert row after": "Insertar fila despu\xe9s",
    "Delete row": "Eliminar fila",
    "Row properties": "Propiedades de fila",
    "Cut row": "Cortar fila",
    "Cut column": "Cortar columna",
    "Copy row": "Copiar fila",
    "Copy column": "Copiar columna",
    "Paste row before": "Pegar fila antes",
    "Paste column before": "Pegar columna antes",
    "Paste row after": "Pegar fila despu\xe9s",
    "Paste column after": "Pegar columna despu\xe9s",
    "Insert column before": "Insertar columna antes",
    "Insert column after": "Insertar columna despu\xe9s",
    "Delete column": "Eliminar columna",
    "Cols": "Cols",
    "Rows": "Filas",
    "Width": "Ancho",
    "Height": "Alto",
    "Cell spacing": "Espaciado entre celdas",
    "Cell padding": "Espaciado entre borde y texto",
    "Row clipboard actions": "Acciones de fila del portapapeles",
    "Column clipboard actions": "Acciones de columna del portapapeles",
    "Table styles": "Estilos de tabla",
    "Cell styles": "Estilos de celda",
    "Column header": "Encabezado de columna",
    "Row header": "Encabezado de fila",
    "Table caption": "Subt\xedtulo de tabla",
    "Caption": "Subt\xedtulo",
    "Show caption": "Mostrar subt\xedtulo",
    "Left": "Izquierda",
    "Center": "Centro",
    "Right": "Derecha",
    "Cell type": "Tipo de celda",
    "Scope": "Alcance",
    "Alignment": "Alineaci\xf3n",
    "Horizontal align": "Alineaci\xf3n horizontal",
    "Vertical align": "Alineaci\xf3n vertical",
    "Top": "Arriba",
    "Middle": "Centro",
    "Bottom": "Inferior",
    "Header cell": "Celda de encabezado",
    "Row group": "Grupo de filas",
    "Column group": "Grupo de columnas",
    "Row type": "Tipo de fila",
    "Header": "Encabezado",
    "Body": "Cuerpo",
    "Footer": "Pie de p\xe1gina",
    "Border color": "Color del borde",
    "Solid": "S\xf3lido",
    "Dotted": "Punteado",
    "Dashed": "Discontinuo",
    "Double": "Doble",
    "Groove": "Ranura",
    "Ridge": "Rugosidad",
    "Inset": "Recuadro",
    "Outset": "Inicial",
    "Hidden": "Oculto",
    "Insert template...": "Insertar plantilla...",
    "Templates": "Plantillas",
    "Template": "Plantilla",
    "Insert Template": "Insertar plantilla",
    "Text color": "Color del texto",
    "Background color": "Color de fondo",
    "Custom...": "Personalizado...",
    "Custom color": "Color personalizado",
    "No color": "Sin color",
    "Remove color": "Remover color",
    "Show blocks": "Mostrar bloques",
    "Show invisible characters": "Mostrar caracteres invisibles",
    "Word count": "Contar palabras",
    "Count": "Cantidad",
    "Document": "Documento",
    "Selection": "Selecci\xf3n",
    "Words": "Palabras",
    "Words: {0}": "Palabras: {0}",
    "{0} words": "{0} palabras",
    "File": "Archivo",
    "Edit": "Editar",
    "Insert": "Insertar",
    "View": "Vista",
    "Format": "Formato",
    "Table": "Tabla",
    "Tools": "Herramientas",
    "Powered by {0}": "Con tecnolog\xeda de {0}",
    "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "\xc1rea de texto enriquecido. Pulse ALT-F9 para el men\xfa. Pulse ALT-F10 para la barra de herramientas. Pulse ALT-0 para obtener ayuda.",
    "Image title": "T\xedtulo de la imagen",
    "Border width": "Ancho del borde",
    "Border style": "Estilo del borde",
    "Error": "Error",
    "Warn": "Advertencia",
    "Valid": "V\xe1lido",
    "To open the popup, press Shift+Enter": "Para abrir la ventana emergente, presione May\xfas+Intro",
    "Rich Text Area": "\xc1rea de texto enriquecido",
    "Rich Text Area. Press ALT-0 for help.": "\xc1rea de texto enriquecido. Pulse ALT-0 para obtener ayuda.",
    "System Font": "Fuente del sistema",
    "Failed to upload image: {0}": "Error al cargar la imagen: {0}",
    "Failed to load plugin: {0} from url {1}": "Error al cargar el complemento: {0} desde la url {1}",
    "Failed to load plugin url: {0}": "Error al cargar la url del complemento: {0}",
    "Failed to initialize plugin: {0}": "Error al inicializar el complemento: {0}",
    "example": "ejemplo",
    "Search": "Buscar",
    "All": "Todo",
    "Currency": "Divisa",
    "Text": "Texto",
    "Quotations": "Comillas",
    "Mathematical": "Matem\xe1ticos",
    "Extended Latin": "Lat\xedn extendido",
    "Symbols": "S\xedmbolos",
    "Arrows": "Flechas",
    "User Defined": "Definido por el usuario",
    "dollar sign": "signo de d\xf3lar",
    "currency sign": "signo de divisa",
    "euro-currency sign": "signo de euro",
    "colon sign": "signo de dos puntos",
    "cruzeiro sign": "signo del cruzeiro",
    "french franc sign": "signo del franco franc\xe9s",
    "lira sign": "signo de la lira",
    "mill sign": "signo de mil",
    "naira sign": "signo del naira",
    "peseta sign": "signo de la peseta",
    "rupee sign": "signo de la rupia",
    "won sign": "signo del won",
    "new sheqel sign": "signo de nuevo shequel",
    "dong sign": "signo del dong",
    "kip sign": "signo del kip",
    "tugrik sign": "signo del tugrik",
    "drachma sign": "signo del dracma",
    "german penny symbol": "signo del penique alem\xe1n",
    "peso sign": "signo del peso",
    "guarani sign": "signo del guaran\xed",
    "austral sign": "signo del austral",
    "hryvnia sign": "signo de hryvnia",
    "cedi sign": "signo de cedi",
    "livre tournois sign": "signo de livre tournois",
    "spesmilo sign": "signo de spesmilo",
    "tenge sign": "signo de tenge",
    "indian rupee sign": "signo de la rupia india",
    "turkish lira sign": "signo de la lira turca",
    "nordic mark sign": "signo del marco n\xf3rdico",
    "manat sign": "signo de manat",
    "ruble sign": "signo de rublo",
    "yen character": "car\xe1cter del yen",
    "yuan character": "car\xe1cter del yuan",
    "yuan character, in hong kong and taiwan": "car\xe1cter del yuan, en Hong Kong y Taiw\xe1n",
    "yen/yuan character variant one": "variante uno del car\xe1cter del yen/yuan",
    "Emojis": "Emojis",
    "Emojis...": "Emojis...",
    "Loading emojis...": "Cargando emojis...",
    "Could not load emojis": "No se pudieron cargar los emojis",
    "People": "Personas",
    "Animals and Nature": "Animales y naturaleza",
    "Food and Drink": "Comida y bebida",
    "Activity": "Actividad",
    "Travel and Places": "Viajes y lugares",
    "Objects": "Objetos",
    "Flags": "Banderas",
    "Characters": "Caracteres",
    "Characters (no spaces)": "Caracteres (sin espacios)",
    "{0} characters": "{0} caracteres",
    "Error: Form submit field collision.": "Error: colisi\xf3n del campo para el env\xedo de formulario",
    "Error: No form element found.": "Error: no se encontr\xf3 ning\xfan elemento de formulario.",
    "Color swatch": "Muestrario de colores",
    "Color Picker": "Selector de colores",
    "Invalid hex color code: {0}": "El c\xf3digo de color hexadecimal {0} no es v\xe1lido",
    "Invalid input": "Entrada no v\xe1lida",
    "R": "R",
    "Red component": "Componente rojo",
    "G": "V",
    "Green component": "Componente verde",
    "B": "A",
    "Blue component": "Componente azul",
    "#": "#",
    "Hex color code": "C\xf3digo de color hexadecimal",
    "Range 0 to 255": "Range 0 al 255",
    "Turquoise": "Turquesa",
    "Green": "Verde",
    "Blue": "Azul",
    "Purple": "Morado",
    "Navy Blue": "Azul marino",
    "Dark Turquoise": "Turquesa oscuro",
    "Dark Green": "Verde oscuro",
    "Medium Blue": "Azul medio",
    "Medium Purple": "Morado medio",
    "Midnight Blue": "Azul medianoche",
    "Yellow": "Amarillo",
    "Orange": "Anaranjado",
    "Red": "Rojo",
    "Light Gray": "Gris claro",
    "Gray": "Gris",
    "Dark Yellow": "Amarillo oscuro",
    "Dark Orange": "Anaranjado oscuro",
    "Dark Red": "Rojo oscuro",
    "Medium Gray": "Gris medio",
    "Dark Gray": "Gris oscuro",
    "Light Green": "Verde claro",
    "Light Yellow": "Amarillo claro",
    "Light Red": "Rojo claro",
    "Light Purple": "Morado claro",
    "Light Blue": "Azul claro",
    "Dark Purple": "Morado oscuro",
    "Dark Blue": "Azul oscuro",
    "Black": "Negro",
    "White": "Blanco",
    "Switch to or from fullscreen mode": "Cambiar a o desde el modo de pantalla completa",
    "Open help dialog": "Abrir di\xe1logo de ayuda",
    "history": "historial",
    "styles": "estilos",
    "formatting": "formato",
    "alignment": "alineaci\xf3n",
    "indentation": "sangr\xeda",
    "Font": "Fuente",
    "Size": "Tama\xf1o",
    "More...": "M\xe1s...",
    "Select...": "Seleccionar...",
    "Preferences": "Preferencias",
    "Yes": "S\xed",
    "No": "No",
    "Keyboard Navigation": "Navegaci\xf3n con el teclado",
    "Version": "Versi\xf3n",
    "Code view": "Vista de c\xf3digo",
    "Open popup menu for split buttons": "Abrir men\xfa emergente para botones divididos",
    "List Properties": "Propiedades de lista",
    "List properties...": "Propiedades de lista...",
    "Start list at number": "Comenzar la lista en el n\xfamero",
    "Line height": "Altura de la l\xednea",
    "Dropped file type is not supported": "No se soporta el archivo arrastrado",
    "Loading...": "Cargando...",
    "ImageProxy HTTP error: Rejected request": "Error HTTP de ImageProxy, solicitud rechazada",
    "ImageProxy HTTP error: Could not find Image Proxy": "Error HTTP de ImageProxy. No se pudo encontrar el proxy de imagen",
    "ImageProxy HTTP error: Incorrect Image Proxy URL": "Error HTTP de ImageProxy. La URL de proxy de imagen es incorrecta",
    "ImageProxy HTTP error: Unknown ImageProxy error": "Error de ImageProxy HTTP. Error de ImageProxy desconocido"
});

/* — ONLC : début des chaînes des plugins — */
hugerte.addI18n("es_MX", {
    "— choisir —": "— elegir —",
    "— Choisir une ancre —": "— Elegir un ancla —",
    "⚠️ DESTRUCTION": "⚠️ DESTRUCCIÓN",
    "1 vue": "1 vista",
    "1:1 (carré)": "1:1 (cuadrado)",
    "10 rue de la Paix, Paris": "Calle Mayor 10, Madrid",
    "16:9 (paysage)": "16:9 (horizontal)",
    "2 à 3 jours ouvrés": "2 a 3 días laborables",
    "200 g de farine": "200 g de harina",
    "21:9 (cinéma)": "21:9 (cine)",
    "240 calories": "240 calorías",
    "26 rue de la Roquille": "Calle de la Roquille, 26",
    "3000 millisecondes valent trois secondes. En dessous de 2000, la plupart des visiteurs n’ont pas le temps de lire.": "3000 milisegundos son tres segundos. Por debajo de 2000, la mayoría de los visitantes no tiene tiempo de leer.",
    "4 parts": "4 raciones",
    "61 rue du Château d’Eau, 33000 Bordeaux": "Calle Mayor 1, 28013 Madrid",
    "9:16 (vertical)": "9:16 (vertical)",
    "À l’emplacement du curseur": "En la posición del cursor",
    "À n’activer que sur un diaporama qui occupe l’écran : sinon la molette cesse de faire défiler la page dès qu’on passe dessus.": "Actívelo solo en un carrusel que ocupe la pantalla: si no, la rueda deja de desplazar la página en cuanto se pasa por encima.",
    "À partir de": "A partir de",
    "À renseigner": "Por rellenar",
    "Abonnement annuel": "Suscripción anual",
    "Accessible sans payer": "Acceso gratuito",
    "Acheter": "Comprar",
    "Action javascript au clic": "Acción javascript al hacer clic",
    "Actions": "Acciones",
    "Actuelle": "Actual",
    "Adresse": "Dirección",
    "Adresse à laquelle les messages du formulaire seront envoyés.": "Dirección a la que se enviarán los mensajes del formulario.",
    "Adresse de l’agenda": "Dirección de la agenda",
    "Adresse de l’événement": "Dirección del evento",
    "Adresse de l’image": "Dirección de la imagen",
    "Adresse de la page": "Dirección de la página",
    "Adresse de la vidéo": "Dirección del vídeo",
    "Adresse du fichier": "Dirección del archivo",
    "Adresse du fichier vidéo": "Dirección del archivo de vídeo",
    "Adresse du lecteur intégré": "Dirección del reproductor integrado",
    "Adresse du lien": "Dirección del enlace",
    "Adresse du lieu": "Dirección del lugar",
    "Adresse e-mail": "Correo electrónico",
    "Adresse personnalisée…": "Dirección personalizada…",
    "Adresse postale": "Dirección postal",
    "Affichage": "Vista",
    "Affiche du code sans le formater": "Muestra código tal cual está escrito",
    "Affiche un PDF directement dans la page, page après page": "Muestra un PDF dentro de la página, página tras página",
    "Affiche une autre page web à l’intérieur de la vôtre": "Muestra otra página web dentro de la suya",
    "Afficher comme un visiteur": "Ver como un visitante",
    "Afficher les flèches précédent / suivant": "Mostrar las flechas anterior / siguiente",
    "Afficher les intitulés sur les vignettes": "Mostrar los títulos en las miniaturas",
    "Afficher les outils de blocs": "Mostrar las herramientas de bloques",
    "Afficher les points de position": "Mostrar los puntos de posición",
    "Afficher une barre de défilement": "Mostrar una barra de desplazamiento",
    "Agenda": "Agenda",
    "Agenda partagé": "Agenda compartida",
    "Agrandir": "Ampliar",
    "Ajoute du vide entre deux blocs, hauteur réglable": "Añade un espacio vacío ajustable entre dos bloques",
    "Ajoutées": "Añadidas",
    "Ajouter": "Añadir",
    "Ajouter à la page": "Añadir a la página",
    "Ajouter à mon calendrier": "Añadir a mi calendario",
    "Ajouter des colonnes": "Añadir columnas",
    "Ajouter des colonnes...": "Añadir columnas...",
    "Ajouter des images à la fin…": "Añadir imágenes al final…",
    "Ajouter des images au début…": "Añadir imágenes al principio…",
    "Ajouter des images…": "Añadir imágenes…",
    "Ajouter un bloc": "Añadir un bloque",
    "Ajouter un bloc à la fin": "Añadir un bloque al final",
    "Ajouter un bloc après": "Añadir un bloque después",
    "Ajouter un bloc au début": "Añadir un bloque al principio",
    "Ajouter un bloc avant": "Añadir un bloque antes",
    "Ajouter un bloc...": "Añadir un bloque...",
    "Ajouter un espace vertical de la hauteur de votre choix": "Añadir un espacio vertical de la altura que elija",
    "Ajouter un palier": "Añadir un umbral",
    "Ajouter un rendez-vous": "Añadir una cita",
    "Ajouter une classe": "Añadir una clase",
    "Ajouter une colonne": "Añadir una columna",
    "Ajouter une configuration": "Añadir una configuración",
    "Ajouter une description pour les moteurs…": "Añadir una descripción para los buscadores…",
    "Ajouter une propriété…": "Añadir una propiedad…",
    "Ajouter une valeur": "Añadir un valor",
    "Ajouter une vue vide": "Añadir una vista vacía",
    "Ajoutez au moins une image à la galerie": "Añada al menos una imagen a la galería",
    "Ajustée à la taille de l'écran": "Ajustada al tamaño de la pantalla",
    "Alignement": "Alineación",
    "Ancre dans la page": "Ancla en la página",
    "Angle (°)": "Ángulo (°)",
    "Année précédente": "Año anterior",
    "Année suivante": "Año siguiente",
    "Annulé": "Cancelado",
    "Annuler": "Cancelar",
    "Aperçu comme un visiteur": "Vista previa como visitante",
    "Aperçu comme un visiteur...": "Vista previa como visitante...",
    "Aperçu de la page": "Vista previa de la página",
    "Apparence": "Apariencia",
    "Application": "Aplicación",
    "Arrondi": "Redondeado",
    "Article": "Artículo",
    "Article de presse": "Artículo de prensa",
    "Article non renseigné": "Artículo sin indicar",
    "Assistance technique": "Asistencia técnica",
    "Au format international, indicatif compris.": "En formato internacional, con prefijo del país.",
    "Au format ISO 8601 : PT20M vaut 20 minutes, PT1H30M une heure et demie.": "En formato ISO 8601: PT20M son 20 minutos, PT1H30M una hora y media.",
    "Au format ISO 8601 : PT2M30S vaut 2 minutes 30.": "En formato ISO 8601: PT2M30S son 2 minutos y 30 segundos.",
    "Au-delà de cette date, les moteurs cessent d’afficher le prix.": "Pasada esta fecha, los buscadores dejan de mostrar el precio.",
    "Aucun code pour le moment.": "Todavía no hay código.",
    "Aucun fichier choisi.": "Ningún archivo elegido.",
    "Aucun fichier ne correspond à cette recherche.": "Ningún archivo coincide con esta búsqueda.",
    "Aucun lieu ne correspond. Essayez une adresse plus simple, ou entrez les coordonnées à la main.": "Ningún lugar coincide. Pruebe una dirección más sencilla o introduzca las coordenadas a mano.",
    "Aucun palier : le diaporama montre le même nombre de vues sur tous les écrans.": "Sin umbrales: el carrusel muestra el mismo número de vistas en todas las pantallas.",
    "Aucun rendez-vous pour ce mois. Ajoutez-en un pour le voir apparaître dans la grille.": "No hay citas este mes. Añada una para verla aparecer en la cuadrícula.",
    "Aucune": "Ninguna",
    "Aucune — visible par tous": "Ninguno — visible para todos",
    "Aucune adresse renseignée": "Sin dirección indicada",
    "Aucune classe du site ne commence ainsi. Vous pouvez tout de même l’ajouter.": "Ninguna clase del sitio empieza así. Puede añadirla igualmente.",
    "Aucune classe pour l’instant.": "Ninguna clase por ahora.",
    "Aucune description": "Sin descripción",
    "Aucune feuille de style de site n’est déclarée : écrivez le nom de la classe à la main.": "No hay ninguna hoja de estilo del sitio declarada: escriba el nombre de la clase a mano.",
    "Aucune image choisie.": "Ninguna imagen elegida.",
    "Aucune image pour l’instant. Cliquez sur « Ajouter des images… » pour en choisir.": "Todavía no hay imágenes. Pulse «Añadir imágenes…» para elegirlas.",
    "Aucune propriété renseignée pour l’instant.": "Ninguna propiedad rellenada por ahora.",
    "Auteur": "Autor",
    "Autre nom": "Otro nombre",
    "autres : continuez à écrire pour les filtrer.": "más: siga escribiendo para filtrarlas.",
    "Autres pages qui parlent de cette chose": "Otras páginas que hablan de esta cosa",
    "Avancé": "Avanzado",
    "Avancer à la molette de la souris": "Avanzar con la rueda del ratón",
    "Avancer avec les flèches du clavier": "Avanzar con las flechas del teclado",
    "Avancer tout seul": "Avanzar solo",
    "Avant retouche": "Antes de editar",
    "Avec empattement": "Con serifa",
    "Avis": "Reseña",
    "Balise « div ». L’identifiant et les classes voyagent avec le bloc : ils sont écrits tels quels dans la page publiée.": "Etiqueta «div». El identificador y las clases viajan con el bloque: se escriben tal cual en la página publicada.",
    "Bandeau d’introduction avec titre, texte et bouton": "Banner de presentación con título, texto y botón",
    "Barre de progression": "Barra de progreso",
    "Bas centre": "Abajo centro",
    "Bas droite": "Abajo derecha",
    "Bas gauche": "Abajo izquierda",
    "Billet de blog": "Entrada de blog",
    "Billetterie": "Entradas",
    "Bloc de texte": "Bloque de texto",
    "Bloc prédéfini": "Bloque predefinido",
    "Blocs et éléments": "Bloques y elementos",
    "Blocs et éléments du site": "Bloques y elementos del sitio",
    "Blocs et éléments du site...": "Bloques y elementos del sitio...",
    "Blocs prédéfinis": "Bloques predefinidos",
    "Blocs prédéfinis...": "Bloques predefinidos...",
    "boulangerie, pain bio, Bordeaux": "panadería, pan ecológico, Madrid",
    "Bouton": "Botón",
    "Bouton d’appel à l’action": "Botón de llamada a la acción",
    "Bouton de paiement PayPal": "Botón de pago PayPal",
    "Bouton ombré": "Botón con sombra",
    "Bouton, vidéo, carte…": "Botón, vídeo, mapa…",
    "Bouton, vidéo, menu, contact…": "Botón, vídeo, menú, contacto…",
    "Boutons de partage": "Botones para compartir",
    "Boutons de partage (minuscules)": "Botones para compartir (diminutos)",
    "Boutons de partage (petits)": "Botones para compartir (pequeños)",
    "Calendrier du mois": "Calendario del mes",
    "Calories": "Calorías",
    "Candidatures jusqu’au": "Candidaturas hasta el",
    "Carte": "Mapa",
    "Carte déplaçable (Leaflet)": "Mapa desplazable (Leaflet)",
    "Carte déplaçable par le visiteur": "El visitante puede mover y ampliar el mapa",
    "Cartes empilées": "Tarjetas apiladas",
    "Cascade (rangées justifiées)": "Cascada (filas justificadas)",
    "Catégorie": "Categoría",
    "Ce diaporama n’a aucune vue. Ajoutez-en une pour qu’il montre quelque chose.": "Este carrusel no tiene vistas. Añada una para que muestre algo.",
    "Ce diaporama n’a pas de réglages dans la page : aucun appel « new Swiper(…) » ne le désigne. Ses images restent modifiables.": "Este carrusel no tiene ajustes en la página: ninguna llamada «new Swiper(…)» lo designa. Sus imágenes siguen siendo editables.",
    "Ce dossier est vide. Déposez des fichiers ici, ou utilisez « Téléverser… ».": "Esta carpeta está vacía. Suelte archivos aquí o use «Subir…».",
    "Ce qu’il faut faire": "Lo que hay que hacer",
    "Ce que contient une portion.": "Lo que contiene una porción.",
    "Ce que le produit coûte et s’il est en stock. C’est ce bloc qui fait apparaître le prix dans Google.": "Lo que cuesta el producto y si hay existencias. Este bloque es el que hace aparecer el precio en Google.",
    "Ce que montre l’image, en une phrase": "Lo que muestra la imagen, en una frase",
    "Ce qui est évalué": "Lo que se evalúa",
    "Ce type de fichier n’est pas accepté": "Este tipo de archivo no se acepta",
    "Centre": "Centro",
    "Centré": "Centrado",
    "Centrer la vue courante": "Centrar la vista actual",
    "Ces propriétés sont exigées et restent vides :": "Estas propiedades son obligatorias y están vacías:",
    "Cet élément n’est pas reconnu par l’éditeur : il sera réécrit tel quel dans la page.": "El editor no reconoce este elemento: se escribirá tal cual en la página.",
    "Cette action est définitive.": "Esta acción es definitiva.",
    "Cette action ne peut pas être annulée.": "Esta acción no se puede deshacer.",
    "Cette page contenait plusieurs fiches de référencement. Une seule a été conservée : les moteurs de recherche n’en lisent qu’une, et choisissent au hasard quand il y en a plusieurs.": "Esta página contenía varias fichas de posicionamiento. Solo se ha conservado una: los buscadores leen una sola y eligen al azar cuando hay varias.",
    "Cette valeur est publiée dans toutes les langues. Choisissez une langue pour en écrire une version qui ne paraîtra que dans celle-là.": "Este valor se publica en todos los idiomas. Elija un idioma para escribir una versión que solo aparezca en ese.",
    "Cette vue contient autre chose que des images. Elle se modifie directement dans la page.": "Esta vista contiene algo distinto de imágenes. Se modifica directamente en la página.",
    "Cette vue ne contient pas qu’une image — plusieurs images, ou une mise en page. Elle est déplaçable, mais son contenu n’est pas réécrit.": "Esta vista no contiene solo una imagen: son varias imágenes o una maquetación. Se puede mover, pero su contenido nunca se reescribe.",
    "Changer cet emoji": "Cambiar este emoji",
    "Changer cette icône": "Cambiar este icono",
    "Changer cette image": "Cambiar esta imagen",
    "Changer de type de contenu…": "Cambiar el tipo de contenido…",
    "Chaque palier s’applique à partir de la largeur indiquée, et jusqu’au palier suivant. En dessous du premier palier, ce sont les réglages de l’onglet « Affichage » qui s’appliquent.": "Cada umbral se aplica desde el ancho indicado hasta el siguiente. Por debajo del primer umbral se aplican los ajustes de la pestaña «Visualización».",
    "Chaque version d’un fichier compte pour un fichier.": "Cada versión de un archivo cuenta como un archivo.",
    "Chaque vue est une image du diaporama. L’ordre de la liste est celui du défilement.": "Cada vista es una imagen del carrusel. El orden de la lista es el del desplazamiento.",
    "Chargement asynchrone (async)": "Carga asíncrona (async)",
    "Chargement du dossier…": "Cargando la carpeta…",
    "Chasse fixe": "Monoespaciada",
    "Chemin du dossier": "Ruta de la carpeta",
    "Choisir cette image dans la médiathèque": "Elegir esta imagen en la mediateca",
    "Choisir la disposition des colonnes": "Elegir la disposición de las columnas",
    "Choisir ou téléverser un média…": "Elegir o subir un archivo…",
    "Choisir un fichier dans l’explorateur de médias": "Elegir un archivo de la biblioteca",
    "Choisir un fichier…": "Elegir un archivo…",
    "Choisir une image dans la médiathèque ou en téléverser une": "Elegir una imagen de la biblioteca o subir una",
    "Choisir une image…": "Elegir una imagen…",
    "Choisir…": "Elegir…",
    "Choisissez d’abord ce que décrit cette page : sans type de contenu, les moteurs ne savent pas quoi faire de la fiche.": "Elija primero qué describe esta página: sin tipo de contenido, los buscadores no saben qué hacer con la ficha.",
    "Choisissez l’élément à insérer": "Elija el elemento que desea insertar",
    "Choisissez le bloc à ajouter": "Elija el bloque que desea añadir",
    "Choisissez le bloc à insérer": "Elija el bloque que desea insertar",
    "Choisissez le bon lieu dans la liste :": "Elija el lugar correcto en la lista:",
    "Choisissez le fichier PDF à afficher": "Elija el archivo PDF que desea mostrar",
    "Choisissez le mois dans la grille, ou laissez « Mois en cours » pour un calendrier qui se met à jour tout seul.": "Elija el mes en la cuadrícula, o deje «Mes actual» para un calendario que se actualiza solo.",
    "Choisissez un pdf dans votre médiathèque, ou donnez l’adresse d’un fichier hébergé ailleurs.": "Elija un pdf de su mediateca, o indique la dirección de un archivo alojado en otro sitio.",
    "Choisissez une image": "Elija una imagen",
    "Choisissez une image avant d'enregistrer.": "Elija una imagen antes de guardar.",
    "Choisissez une image dans votre médiathèque, ou donnez l’adresse d’une image hébergée ailleurs.": "Elija una imagen de su mediateca, o indique la dirección de una imagen alojada en otro sitio.",
    "Chose": "Cosa",
    "Cinq par défaut. À préciser si votre échelle est différente.": "Cinco por defecto. Indíquelo si su escala es distinta.",
    "Citation": "Cita",
    "Classe ajoutée à la page en cours de consultation.": "Clase añadida a la página que se está viendo.",
    "Classe CSS contenant": "Clase CSS contenedora",
    "Classe CSS du bouton": "Clase CSS del botón",
    "Classe CSS élément": "Clase CSS del elemento",
    "Classe CSS élément actif": "Clase CSS del elemento activo",
    "Classe posée sur chaque page du menu.": "Clase aplicada a cada página del menú.",
    "Classe posée sur la liste qui entoure les pages.": "Clase aplicada a la lista que envuelve las páginas.",
    "Classes CSS": "Clases CSS",
    "Classes de la feuille de style du site et des autres blocs de la page.": "Clases de la hoja de estilo del sitio y de los demás bloques de la página.",
    "Classes du site.": "Clases del sitio.",
    "Clignotant": "Parpadeante",
    "Cliquez pour sélectionner ce bloc, puis « Modifier le bloc » pour le régler.": "Pulse para seleccionar este bloque y después «Editar el bloque» para configurarlo.",
    "Cliquez sur un emoji pour l’insérer. Les dessins sont ceux d’OpenMoji : ils s’affichent de la même façon sur tous les appareils.": "Pulse un emoji para insertarlo. Los dibujos son de OpenMoji: se ven igual en todos los dispositivos.",
    "Cliquez sur un fichier pour voir ses informations et les actions possibles. Un double clic le choisit directement.": "Pulse un archivo para ver sus datos y las acciones posibles. Una doble pulsación lo elige directamente.",
    "Cliquez sur une icône pour l’insérer. Elle prend la taille et la couleur du texte qui l’entoure.": "Pulse un icono para insertarlo. Toma el tamaño y el color del texto que lo rodea.",
    "Cochez les réseaux à proposer. Si vous n’en cochez aucun, tous seront affichés.": "Marque las redes que desea ofrecer. Si no marca ninguna, se mostrarán todas.",
    "Code court": "Código corto",
    "Code de la formation": "Código del curso",
    "Code HTML": "Código HTML",
    "Code JavaScript": "Código JavaScript",
    "Code non reconnu : il sera réécrit tel quel dans la page.": "Código no reconocido: se escribirá tal cual en la página.",
    "Code postal": "Código postal",
    "Code source": "Código fuente",
    "Code source HTML": "Código fuente HTML",
    "Code source HTML...": "Código fuente HTML...",
    "Code-barres (EAN 13)": "Código de barras (EAN 13)",
    "Colle un code d’intégration fourni par un service tiers": "Pegue un código de inserción de otro servicio",
    "Comment passer commande ?": "¿Cómo hago un pedido?",
    "Commerce": "Comercio",
    "Commerce de proximité": "Comercio local",
    "Commercial": "Comercial",
    "Compléter les langues manquantes": "Añadir los idiomas que faltan",
    "Compte PayPal du vendeur": "Cuenta PayPal del vendedor",
    "Conditions de livraison": "Condiciones de entrega",
    "Conseillées": "Recomendadas",
    "Construction de l’aperçu…": "Construyendo la vista previa…",
    "Contenu": "Contenido",
    "Contenu libre :": "Contenido libre:",
    "Contenus": "Contenidos",
    "Contour": "Contorno",
    "Coordonnées géographiques": "Coordenadas geográficas",
    "Copie…": "Copiando…",
    "Copier": "Copiar",
    "Copier vers": "Copiar a",
    "Copier vers…": "Copiar a…",
    "Coque de carte Renault": "Funda de tarjeta Renault",
    "Couleur": "Color",
    "Couleur d’accentuation": "Color de acento",
    "Couleur de fond": "Color de fondo",
    "Couleur de l’ombre": "Color de la sombra",
    "Couleur du filet": "Color de la línea",
    "Couleur du texte": "Color del texto",
    "Création…": "Creando…",
    "Créer": "Crear",
    "Créer une image": "Crear una imagen",
    "CSS personnalisé (appliqué au bloc image)": "CSS personalizado (aplicado al bloque de imagen)",
    "Cube": "Cubo",
    "Cuisine": "Cocina",
    "Date": "Fecha",
    "Date de création": "Fecha de creación",
    "Date de début": "Fecha de inicio",
    "Date de dernière mise à jour": "Fecha de última actualización",
    "Date de fin": "Fecha de fin",
    "Date de mise en ligne": "Fecha de publicación",
    "Date de publication": "Fecha de publicación",
    "De « € » à « €€€€ », ou une fourchette : « 15 € – 40 € ».": "De «€» a «€€€€», o un intervalo: «15 € – 40 €».",
    "Début": "Inicio",
    "Débutant": "Principiante",
    "Décrire la page pour les moteurs (microdonnées)…": "Describir la página para los buscadores (microdatos)…",
    "Décrivent le contenu de cette page pour les moteurs de recherche. Rien n’en paraît sur le site.": "Describen el contenido de esta página para los buscadores. Nada de ello aparece en el sitio.",
    "Décrivez votre offre en une phrase.": "Describa su oferta en una frase.",
    "Défilant": "Desplazándose",
    "Défilement": "Desplazamiento",
    "Défilement libre, sans s’aligner sur une vue": "Desplazamiento libre, sin alinearse con una vista",
    "Définir la langue": "Definir el idioma",
    "Définir la langue de ce bloc": "Definir el idioma de este bloque",
    "Définir la langue de la sélection": "Definir el idioma de la selección",
    "Dégradé : angle (°)": "Degradado: ángulo (°)",
    "Dégradé : arrivée": "Degradado: fin",
    "Dégradé : couleur d’arrivée": "Degradado: color final",
    "Dégradé : couleur de départ": "Degradado: color inicial",
    "Dégradé : départ": "Degradado: inicio",
    "Délai annoncé": "Plazo anunciado",
    "Déplacé en ligne": "Trasladado a internet",
    "Déplacement…": "Moviendo…",
    "Déplacer": "Mover",
    "Déplacer cette vue": "Mover esta vista",
    "Déplacer le bloc": "Mover el bloque",
    "Déplacer vers": "Mover a",
    "Déplacer vers…": "Mover a…",
    "Déplié au chargement de la page": "Desplegado al cargar la página",
    "Déplier": "Desplegar",
    "Déposez vos fichiers pour les téléverser": "Suelte sus archivos para subirlos",
    "Dernière vérification": "Última verificación",
    "Descendre": "Bajar",
    "Descendre cette vue": "Bajar esta vista",
    "Descendre le bloc": "Bajar el bloque",
    "Description": "Descripción",
    "Description de la page": "Descripción de la página",
    "Description pour les moteurs de recherche": "Descripción para los buscadores",
    "Dessert": "Postre",
    "Dessiner une image…": "Dibujar una imagen…",
    "Devise": "Moneda",
    "Diaporama": "Carrusel",
    "Diaporama...": "Carrusel...",
    "Dimanche": "Domingo",
    "Dimension": "Dimensión",
    "Disponibilité": "Disponibilidad",
    "Disposition": "Disposición",
    "Disposition des colonnes": "Disposición de las columnas",
    "Document PDF": "Documento PDF",
    "Dollar américain (USD)": "Dólar estadounidense (USD)",
    "Dollar canadien (CAD)": "Dólar canadiense (CAD)",
    "Dossier de destination": "Carpeta de destino",
    "Dossier parent": "Carpeta superior",
    "Droite": "Derecha",
    "Dupliquer cet élément": "Duplicar este elemento",
    "Dupliquer la ligne": "Duplicar la fila",
    "Dupliquer le bloc": "Duplicar el bloque",
    "Durée": "Duración",
    "Durée d’un cycle (secondes)": "Duración de un ciclo (segundos)",
    "Durée totale": "Duración total",
    "E-mail destinataire": "Correo del destinatario",
    "Écrans": "Pantallas",
    "Écrire dans toutes les langues": "Escribir en todos los idiomas",
    "Éditeur": "Editor",
    "Effet de transition": "Efecto de transición",
    "Élargir la colonne": "Ensanchar la columna",
    "élément": "elemento",
    "Élément de liste": "Elemento de lista",
    "éléments": "elementos",
    "Éléments du site": "Elementos del sitio",
    "Éléments du site...": "Elementos del sitio...",
    "Emoji ou icône": "Emoji o icono",
    "Emojis et icônes": "Emojis e iconos",
    "Emojis et icônes...": "Emojis e iconos...",
    "Emojis seuls": "Solo emojis",
    "Emojis seuls...": "Solo emojis...",
    "Emplacement dans la page": "Ubicación en la página",
    "Emplacements": "Ubicaciones",
    "Employeur": "Empleador",
    "En ligne": "En línea",
    "En rupture": "Sin existencias",
    "En savoir plus": "Saber más",
    "En stock": "En existencias",
    "En-tête de la page (<head>)": "Cabecera de la página (<head>)",
    "Encadré": "Enmarcado",
    "Endommagé": "Dañado",
    "Enregistrer": "Guardar",
    "Énumération dont l’ordre compte : étapes, classement": "Una lista donde el orden importa: pasos, clasificación",
    "Énumération sans ordre particulier": "Una lista sin orden particular",
    "Épuisé": "Agotado",
    "Espace": "Espacio",
    "Espace entre les vignettes (px)": "Espacio entre miniaturas (px)",
    "Espace entre les vues (pixels)": "Espacio entre vistas (píxeles)",
    "Espace vertical": "Espacio vertical",
    "Étape": "Paso",
    "Étapes": "Pasos",
    "Étapes du chemin": "Pasos de la ruta",
    "État": "Estado",
    "État du produit": "Estado del producto",
    "Euro (EUR)": "Euro (EUR)",
    "Événement": "Evento",
    "Événement non renseigné": "Evento sin indicar",
    "Événements": "Eventos",
    "Exécution différée (defer)": "Ejecución diferida (defer)",
    "Exigé": "Obligatorio",
    "Explorateur de fichiers": "Explorador de archivos",
    "Explorateur de fichiers...": "Explorador de archivos...",
    "Facturation": "Facturación",
    "Faire glisser au doigt ou à la souris": "Arrastrar con el dedo o el ratón",
    "Fermer": "Cerrar",
    "Fermeture": "Cierre",
    "Fichier": "Archivo",
    "Fichier de l’image": "Archivo de la imagen",
    "Fichier externe (src)": "Archivo externo (src)",
    "Fichier PDF": "Archivo PDF",
    "fichier(s)": "archivo(s)",
    "fichiers": "archivos",
    "fichiers sélectionnés": "archivos seleccionados",
    "Fil d’Ariane": "Ruta de navegación",
    "Filet": "Línea",
    "Filet simple": "Línea simple",
    "Fin": "Fin",
    "Fin de la page (avant </body>)": "Final de la página (antes de </body>)",
    "Fonction": "Cargo",
    "Fondu": "Fundido",
    "Format proportionnel": "Formato proporcional",
    "Formation": "Formación",
    "Forme des points": "Forma de los puntos",
    "Formulaire de contact": "Formulario de contacto",
    "Formulaire de réservation": "Formulario de reserva",
    "Formulaires": "Formularios",
    "Fourchette de prix": "Rango de precios",
    "Fournitures": "Materiales",
    "Frais de port": "Gastos de envío",
    "Frais, délais et zone de livraison.": "Coste, plazo y zona de entrega.",
    "Franc suisse (CHF)": "Franco suizo (CHF)",
    "Français": "Francés",
    "Française": "Francesa",
    "Fuseau horaire": "Zona horaria",
    "Galerie d’images": "Galería de imágenes",
    "Gauche": "Izquierda",
    "Général": "General",
    "Gérant": "Gerente",
    "Glissement (par défaut)": "Deslizamiento (por defecto)",
    "Grande": "Grande",
    "Grille de cellules pour présenter des données": "Una cuadrícula de celdas para presentar datos",
    "Haut centre": "Arriba centro",
    "Haut droite": "Arriba derecha",
    "Haut gauche": "Arriba izquierda",
    "Hauteur": "Altura",
    "Hauteur (pixels)": "Alto (píxeles)",
    "Hauteur de la carte": "Altura del mapa",
    "Hauteur de la zone de lecture": "Altura de la zona de lectura",
    "Hauteur du séparateur": "Altura del separador",
    "Hauteur fixe": "Altura fija",
    "Hauteur maximale (px)": "Altura máxima (px)",
    "Hero": "Hero",
    "Heure": "Hora",
    "Heure de début": "Hora de inicio",
    "Heure de fin": "Hora de fin",
    "Horaires d’ouverture": "Horario de apertura",
    "Horizontal": "Horizontal",
    "https://exemple.tld/photo.jpg": "https://ejemplo.tld/foto.jpg",
    "Icônes": "Iconos",
    "Icônes seules": "Solo iconos",
    "Icônes seules...": "Solo iconos...",
    "Identifiant (ancre)": "Identificador (ancla)",
    "Identifiant du bloc, utilisable comme ancre": "Identificador del bloque, utilizable como ancla",
    "Identifiant et classes du bloc": "Identificador y clases del bloque",
    "Identité": "Identidad",
    "Il ne reste de la place que pour": "Solo queda espacio para",
    "Image": "Imagen",
    "Image d’aperçu": "Imagen de vista previa",
    "Image de fond": "Imagen de fondo",
    "Image de la bibliothèque": "Imagen de la biblioteca",
    "Image principale": "Imagen principal",
    "Images": "Imágenes",
    "Images de la galerie": "Imágenes de la galería",
    "Indiquez l’adresse de l’agenda": "Indique la dirección de la agenda",
    "Indiquez l’adresse de la page à intégrer": "Indique la dirección de la página que desea integrar",
    "Indiquez l’adresse de la vidéo": "Indique la dirección del vídeo",
    "Indre-et-Loire": "Indre y Loira",
    "Ingrédients": "Ingredientes",
    "Insérer des colonnes": "Insertar columnas",
    "Insérer ou modifier un lien": "Insertar o editar un enlace",
    "Insérer ou modifier une image": "Insertar o editar una imagen",
    "Insérer un emoji Unicode ou une icône Material Design": "Insertar un emoji Unicode o un icono",
    "Insérer un texte animé": "Insertar un texto animado",
    "Intègre un agenda public existant (Google Agenda, ICS…)": "Integra una agenda pública existente (Google Calendar, ICS…)",
    "Intérim": "Temporal",
    "Intervenant": "Participante",
    "Intitulé": "Título",
    "Intitulé affiché": "Título mostrado",
    "Intitulé du poste": "Título del puesto",
    "Jeudi": "Jueves",
    "Jour": "Día",
    "Jour du mois": "Día del mes",
    "L’adresse à laquelle cette chose est présentée. Le plus souvent, la page courante.": "La dirección donde se presenta esta cosa. Casi siempre, la página actual.",
    "L’adresse à laquelle l’événement se tient à distance.": "La dirección donde se celebra el evento a distancia.",
    "L’adresse des conditions de réutilisation du contenu.": "La dirección de las condiciones de reutilización del contenido.",
    "L’adresse du compte PayPal qui recevra le paiement.": "La cuenta PayPal que recibirá el pago.",
    "L’adresse que l’on met dans un cadre intégré, par exemple celle d’un lecteur YouTube.": "La dirección que se pone en un marco integrado, por ejemplo la de un reproductor de YouTube.",
    "L’aperçu n’a pas pu être construit": "No se pudo construir la vista previa",
    "L’avis d’un client, avec sa note et son texte.": "La reseña de un cliente, con su valoración y su texto.",
    "l’élément": "el elemento",
    "L’image montrée avant la lecture.": "La imagen que se muestra antes de la reproducción.",
    "La chose dont ce contenu parle.": "Aquello de lo que trata este contenido.",
    "La grille d’un mois, avec vos rendez-vous inscrits jour par jour": "La cuadrícula de un mes, con sus citas anotadas día a día",
    "La latitude et la longitude du lieu.": "La latitud y la longitud del lugar.",
    "La marque sous laquelle le produit est vendu.": "La marca bajo la que se vende el producto.",
    "La mise en forme simple est acceptée : gras, liens, listes.": "Se acepta formato sencillo: negrita, enlaces, listas.",
    "La moyenne des avis et leur nombre.": "La media de las reseñas y su número.",
    "La moyenne des avis. Ce sont les étoiles affichées sous le résultat.": "La media de las reseñas. Son las estrellas que se muestran bajo el resultado.",
    "La recherche d’adresse n’a pas abouti. Entrez les coordonnées à la main.": "La búsqueda de dirección no funcionó. Introduzca las coordenadas a mano.",
    "La seconde ligne décrit l’image : elle est lue à voix haute par les lecteurs d’écran et reprise par les moteurs de recherche.": "La segunda línea describe la imagen: los lectores de pantalla la leen en voz alta y los buscadores la recogen.",
    "La section du site où l’article paraît : Actualités, Recettes, Juridique.": "La sección del sitio donde aparece el artículo: Noticias, Recetas, Jurídico.",
    "La semaine commence le": "La semana empieza el",
    "Lâchez pour annuler.": "Suelte para cancelar.",
    "Laissez vide pour afficher le bouton officiel de PayPal.": "Déjelo vacío para mostrar el botón oficial de PayPal.",
    "Langue": "Idioma",
    "Langue du bloc": "Idioma del bloque",
    "Langue du visiteur": "Idioma del visitante",
    "Langues": "Idiomas",
    "Langues de la page": "Idiomas de la página",
    "Langues parlées": "Idiomas hablados",
    "Largeur": "Anchura",
    "Largeur (%, rem, vw...)": "Anchura (%, rem, vw...)",
    "Largeur (pixels)": "Ancho (píxeles)",
    "Largeur du filet": "Anchura de la línea",
    "Largeur en pixels": "Ancho en píxeles",
    "Largeur maximale": "Anchura máxima",
    "Largeur maximale (px)": "Anchura máxima (px)",
    "Latitude": "Latitud",
    "le bloc": "el bloque",
    "Le bouton « Ajouter une configuration » en pose une, à la fin de la page, avec les commandes que son html contient déjà.": "El botón «Añadir una configuración» coloca una al final de la página, con los controles que ya contiene su html.",
    "Le chemin qui mène à cette page depuis l’accueil.": "La ruta que lleva a esta página desde la portada.",
    "Le chemin qui mène à la page depuis l’accueil.": "La ruta que lleva a la página desde la portada.",
    "Le code ci-dessus est affiché tel quel dans l’éditeur ; il est publié sous sa forme active sur la page.": "El código anterior se muestra tal cual en el editor; se publica en su forma activa en la página.",
    "Le code de l’unité : GRM pour un gramme, KGM pour un kilogramme, CMT pour un centimètre.": "El código de la unidad: GRM para un gramo, KGM para un kilogramo, CMT para un centímetro.",
    "Le code de la langue du contenu : fr, en, nl.": "El código del idioma del contenido: fr, en, nl.",
    "Le code du pays livré : FR, BE, NL.": "El código del país de entrega: FR, BE, NL.",
    "Le code du pays sur deux lettres : FR, BE, NL.": "El código del país de dos letras: FR, BE, NL.",
    "Le contenu des colonnes est conservé. Une disposition qui en compte moins ramène le contenu des colonnes en trop dans la dernière.": "Se conserva el contenido de las columnas. Una disposición con menos columnas lleva el contenido de las sobrantes a la última.",
    "Le corps de l’article. Facultatif : les moteurs le lisent déjà dans la page.": "El cuerpo del artículo. Opcional: los buscadores ya lo leen en la página.",
    "le dossier": "la carpeta",
    "le fichier": "el archivo",
    "Le fichier dépasse la taille maximale autorisée": "El archivo supera el tamaño máximo permitido",
    "Le fichier dépasse le poids autorisé par votre offre": "El archivo supera el peso permitido por su plan",
    "Le fuseau dans lequel les heures ci-dessus sont exprimées.": "La zona horaria en la que se expresan las horas anteriores.",
    "Le jour de la dernière modification. Les moteurs s’en servent pour juger de la fraîcheur.": "El día de la última modificación. Los buscadores lo usan para juzgar la actualidad.",
    "Le jour où le contenu a été mis en ligne.": "El día en que se publicó el contenido.",
    "Le jour où le contenu a été relu et confirmé exact.": "El día en que se revisó el contenido y se confirmó su exactitud.",
    "Le logo affiché dans les résultats de recherche. Au moins 112 pixels de côté.": "El logotipo que se muestra en los resultados de búsqueda. Al menos 112 píxeles de lado.",
    "Le logo enregistré dans les réglages de votre site": "El logotipo guardado en los ajustes de su sitio",
    "Le mois en cours, quel qu’il soit au moment de l’affichage.": "El mes en curso, sea cual sea al mostrarse la página.",
    "Le nom déposé, tel qu’il figure au registre du commerce.": "El nombre registrado, tal como figura en el registro mercantil.",
    "Le nom du site, affiché par-dessus le logo": "El nombre del sitio, mostrado sobre el logotipo",
    "Le nom sous lequel cette chose est connue. C’est ce que les moteurs affichent en titre.": "El nombre por el que se conoce esta cosa. Es lo que los buscadores muestran como título.",
    "Le passage apparaît et disparaît. À employer avec mesure : un texte qui clignote se lit mal, et se remarque partout ailleurs sur la page.": "El pasaje aparece y desaparece. Úselo con moderación: un texto que parpadea se lee mal y distrae del resto de la página.",
    "Le passage traverse son cadre, de droite à gauche. Il occupe alors toute la largeur disponible, comme un paragraphe.": "El pasaje atraviesa su marco, de derecha a izquierda. Ocupa entonces todo el ancho disponible, como un párrafo.",
    "Le plugin des scripts n’est pas chargé : la configuration ne peut pas être ajoutée depuis ici. Écrivez-la dans le gabarit du site.": "El complemento de scripts no está cargado: la configuración no puede añadirse desde aquí. Escríbala en la plantilla del sitio.",
    "Le résumé et les mots-clés affichés par Google — invisible sur la page": "El resumen y las palabras clave que muestra Google — invisible en la página",
    "le script": "el script",
    "Le site dans son ensemble. À poser sur la page d’accueil.": "El sitio en su conjunto. Se coloca en la portada.",
    "Le texte d’une réponse.": "El texto de una respuesta.",
    "Le texte décrit l’image : il est lu à voix haute par les lecteurs d’écran et repris par les moteurs de recherche.": "El texto describe la imagen: los lectores de pantalla lo leen en voz alta y los motores de búsqueda lo recogen.",
    "Le titre du contenu. Restez sous 110 caractères : au-delà, les moteurs le coupent.": "El título del contenido. No pase de 110 caracteres: más allá, los buscadores lo cortan.",
    "Le type le plus général : à n’employer que si aucun autre ne convient.": "El tipo más general: solo si ningún otro sirve.",
    "Lecture automatique": "Reproducción automática",
    "Lecture en boucle": "Reproducción en bucle",
    "Légende": "Leyenda",
    "Les classes de la feuille de style du site n’ont pas pu être lues : elle est servie par un autre domaine, qui n’en autorise pas la lecture. Écrivez le nom de la classe à la main.": "No se han podido leer las clases de la hoja de estilo del sitio: la sirve otro dominio que no autoriza su lectura. Escriba el nombre de la clase a mano.",
    "Les classes décident de l’allure du bloc. Celles qui sont proposées viennent de la feuille de style de votre site et des autres blocs de la page.": "Las clases deciden el aspecto del bloque. Las que se proponen provienen de la hoja de estilo de su sitio y de los demás bloques de la página.",
    "Les deux": "Ambos",
    "Les effets autres que le glissement demandent leur module dans la page. Si le diaporama se fige après un changement d’effet, revenez au glissement.": "Los efectos distintos del deslizamiento necesitan su módulo en la página. Si el carrusel se congela tras cambiar de efecto, vuelva al deslizamiento.",
    "les microdonnées de cette page": "los microdatos de esta página",
    "Les moteurs de recherche affichent un prix, des étoiles ou une date de concert quand la page le leur dit dans un langage qu’ils connaissent. Choisissez ce qui correspond le mieux — vous pourrez en changer.": "Los buscadores muestran un precio, estrellas o la fecha de un concierto cuando la página se lo dice en un lenguaje que conocen. Elija lo que mejor encaje: podrá cambiarlo.",
    "Les moteurs de recherche mettent à disposition un outil qui lit une page publiée et dit ce qu’ils y comprennent. Publiez d’abord la page, puis donnez-lui son adresse.": "Los buscadores ofrecen una herramienta que lee una página publicada y dice lo que entienden de ella. Publique primero la página y después indíquele su dirección.",
    "Les moteurs ignoreront la fiche tant qu’elles manqueront. L’enregistrer quand même ?": "Los buscadores ignorarán la ficha mientras falten. ¿Guardarla de todos modos?",
    "Les mots se relaient à la même place. La place réservée est celle du plus long : le texte qui suit ne bouge pas quand ils changent.": "Las palabras se alternan en el mismo sitio. El espacio reservado es el de la más larga: el texto que sigue no se mueve cuando cambian.",
    "Les propriétés marquées « Exigé » doivent être remplies pour que les moteurs acceptent la fiche. Les autres l’enrichissent.": "Las propiedades marcadas «Obligatorio» deben rellenarse para que los buscadores acepten la ficha. Las demás la enriquecen.",
    "Les propriétés marquées « Obligatoire » doivent être remplies pour que les moteurs acceptent la fiche. Les autres l’enrichissent.": "Las propiedades marcadas «Obligatorio» deben rellenarse para que los buscadores acepten la ficha. Las demás la enriquecen.",
    "Les rendez-vous d’avril": "Las citas de abril",
    "Licence": "Licencia",
    "Lien": "Enlace",
    "Lien du bouton": "Enlace del botón",
    "Lien du site": "Enlace del sitio",
    "Lien...": "Enlace...",
    "Lieu": "Lugar",
    "Lieu affiché": "Lugar mostrado",
    "Lieu choisi. Ajustez le zoom si nécessaire.": "Lugar elegido. Ajuste el zoom si es necesario.",
    "Lieu de travail": "Lugar de trabajo",
    "Lieu en ligne": "Ubicación en línea",
    "Lieu et date de rédaction": "Lugar y fecha de redacción",
    "Liste à puces": "Lista con viñetas",
    "Liste des pages de votre site": "La lista de páginas de su sitio",
    "Liste numérotée": "Lista numerada",
    "Livraison": "Entrega",
    "Livre sterling (GBP)": "Libra esterlina (GBP)",
    "Logo": "Logotipo",
    "Logo du site": "Logotipo del sitio",
    "Longitude": "Longitud",
    "Lundi": "Lunes",
    "Maçonnerie (colonnes)": "Mampostería (columnas)",
    "Maintenez enfoncé pendant {0} secondes.": "Mantenga pulsado {0} segundos.",
    "Maintenez le bouton enfoncé pour supprimer": "Mantenga pulsado el botón para eliminar",
    "Maintenu": "Mantenido",
    "Mardi": "Martes",
    "Marge extérieure (ex : 0 0 1rem)": "Margen exterior (p. ej. 0 0 1rem)",
    "Marge intérieure (ex : .5rem 1rem)": "Relleno interior (p. ej. .5rem 1rem)",
    "Marque": "Marca",
    "Matière": "Material",
    "Matières grasses": "Grasas",
    "maximum": "máximo",
    "Médias": "Medios",
    "Médiathèque": "Biblioteca de medios",
    "Même onglet": "Misma pestaña",
    "Menu": "Menú",
    "menu, contact, partage…": "menú, contacto, compartir…",
    "Mercredi": "Miércoles",
    "Mesure": "Medida",
    "Met en avant une phrase, avec un filet sur le côté": "Destaca una frase, con una línea al lado",
    "Mettre à jour": "Actualizar",
    "Microdonnées": "Microdatos",
    "Microdonnées de la page": "Microdatos de la página",
    "Microdonnées incomplètes": "Microdatos incompletos",
    "Milieu droite": "Centro derecha",
    "Milieu gauche": "Centro izquierda",
    "Mise en avant": "Destacados",
    "Mode d’emploi": "Instrucciones",
    "Mode de participation": "Modo de participación",
    "Modifier cet élément": "Editar este elemento",
    "Modifier dans Pixel•OnlineCreation": "Editar en Pixel•OnlineCreation",
    "Modifier la description pour les moteurs…": "Modificar la descripción para los buscadores…",
    "Modifier le bloc": "Editar el bloque",
    "Modifier le diaporama": "Modificar el carrusel",
    "Modifier le lien": "Editar el enlace",
    "Modifier le script": "Editar el script",
    "Modifier le texte animé": "Editar el texto animado",
    "Modifier les microdonnées": "Modificar los microdatos",
    "Modifier les microdonnées de la page…": "Modificar los microdatos de la página…",
    "Modifier…": "Modificar…",
    "Mois": "Mes",
    "Mois affiché": "Mes mostrado",
    "Mois en cours": "Mes en curso",
    "Montant": "Importe",
    "Monter": "Subir",
    "Monter cette vue": "Subir esta vista",
    "Monter le bloc": "Subir el bloque",
    "Mosaïque carrée": "Mosaico cuadrado",
    "Mots qui se relaient": "Palabras que se alternan",
    "Mots qui se relaient (un par ligne)": "Palabras que se alternan (una por línea)",
    "Mots-clés": "Palabras clave",
    "Nature de la prestation": "Naturaleza del servicio",
    "Navigation": "Navegación",
    "Ne pas supprimer": "No eliminar",
    "Neuf": "Nuevo",
    "Neuf, d’occasion, reconditionné. Les moteurs l’affichent à côté du prix, et une place de marché peut le refuser s’il manque.": "Nuevo, usado, reacondicionado. Los buscadores lo muestran junto al precio, y un marketplace puede rechazar la ficha si falta.",
    "Niveau": "Nivel",
    "Niveau de prix": "Nivel de precios",
    "Nom": "Nombre",
    "Nom d’une classe, par exemple text-center": "Nombre de una clase, por ejemplo text-center",
    "Nom de famille": "Apellidos",
    "Nom de l’article": "Nombre del artículo",
    "Nom de l’événement": "Nombre del evento",
    "Nom du dossier": "Nombre de la carpeta",
    "Nom du widget": "Nombre del widget",
    "Nom exact de la propriété schema.org, par exemple award :": "Nombre exacto de la propiedad schema.org, por ejemplo award:",
    "Nombre d’avis": "Número de reseñas",
    "Nombre d’offres": "Número de ofertas",
    "Nombre de mots": "Número de palabras",
    "Nombre de pages affichées (0 = toutes)": "Número de páginas mostradas (0 = todas)",
    "Non": "No",
    "Non pour un contenu réservé aux abonnés.": "No para un contenido reservado a los suscriptores.",
    "Normale": "Normal",
    "Nos bureaux": "Nuestras oficinas",
    "Note": "Valoración",
    "Note donnée": "Valoración dada",
    "Note maximale": "Valoración máxima",
    "Note minimale": "Valoración mínima",
    "Note moyenne": "Valoración media",
    "Nouveau dossier": "Nueva carpeta",
    "Nouveau nom": "Nuevo nombre",
    "Nouvel onglet": "Nueva pestaña",
    "Numéro d’identification": "Número de identificación",
    "Numéro de TVA": "Número de IVA",
    "Numéro de vue": "Número de vista",
    "Numéro et rue": "Número y calle",
    "Occasion": "Usado",
    "Œuvre": "Obra",
    "Offre": "Oferta",
    "Offre d’emploi": "Oferta de empleo",
    "Ombre : couleur": "Sombra: color",
    "Ombre : décalage horizontal": "Sombra: desplazamiento horizontal",
    "Ombre : décalage vertical": "Sombra: desplazamiento vertical",
    "Ombre : flou": "Sombra: desenfoque",
    "Ombre : X": "Sombra: X",
    "Ombre : Y": "Sombra: Y",
    "Ordinateur": "Ordenador",
    "Organisateur": "Organizador",
    "Organisation": "Organización",
    "Organisme": "Organismo",
    "Ou adresse d’une image en ligne (https://…)": "O la dirección de una imagen en línea (https://…)",
    "Oui": "Sí",
    "Outil de test des moteurs…": "Herramienta de prueba de los buscadores…",
    "Outils de blocs": "Herramientas de bloques",
    "Outils nécessaires": "Herramientas necesarias",
    "Ouverture": "Apertura",
    "Ouvrir dans": "Abrir en",
    "Ouvrir le lien": "Abrir el enlace",
    "Page actuelle (ancres)": "Esta página (anclas)",
    "Page intégrée": "Página integrada",
    "Page intégrée (iframe)": "Página integrada (iframe)",
    "Page web": "Página web",
    "Page Wikipédia, profil Facebook, fiche Google : les adresses qui désignent la même chose ailleurs.": "Página de Wikipedia, perfil de Facebook, ficha de Google: las direcciones que designan la misma cosa en otros sitios.",
    "panier, téléphone, flèche…": "cesta, teléfono, flecha…",
    "Paragraphe": "Párrafo",
    "Paragraphe, image, colonnes…": "Párrafo, imagen, columnas…",
    "Parallaxe": "Paralaje",
    "Pays": "País",
    "Peintre carrossier": "Pintor de carrocería",
    "Peinture automobile": "Pintura de automóviles",
    "Personnalisé (adresse)": "Personalizado (dirección)",
    "Personnalisées": "Personalizadas",
    "Personne": "Persona",
    "Perspective": "Perspectiva",
    "Petite": "Pequeña",
    "Pixel•OnlineCreation, l’éditeur d’images": "Pixel•OnlineCreation, el editor de imágenes",
    "Pixels": "Píxeles",
    "Plage d’ouverture": "Franja de apertura",
    "Plan OpenStreetMap": "Plano de OpenStreetMap",
    "Planning": "Planificación",
    "Plein écran": "Pantalla completa",
    "Pleine largeur": "Ancho completo",
    "Plusieurs offres pour le même produit : du moins cher au plus cher.": "Varias ofertas para el mismo producto: de la más barata a la más cara.",
    "Plusieurs photos présentées en mosaïque, avec agrandissement au clic": "Varias fotos en mosaico, que se amplían al pulsarlas",
    "Poids": "Peso",
    "Point de contact": "Punto de contacto",
    "Points": "Puntos",
    "Police du site": "Tipografía del sitio",
    "Portes ouvertes": "Jornada de puertas abiertas",
    "Position sur l’image": "Posición sobre la imagen",
    "Pour combien de personnes": "Para cuántas personas",
    "Précommande": "Reserva",
    "Prénom": "Nombre de pila",
    "Présentation": "Presentación",
    "Presse": "Prensa",
    "Prestataire": "Proveedor",
    "Prestation": "Servicio",
    "Principal": "Principal",
    "Prix": "Precio",
    "Prix et disponibilité": "Precio y disponibilidad",
    "Prix le plus bas": "Precio más bajo",
    "Prix le plus haut": "Precio más alto",
    "Prix valable jusqu’au": "Precio válido hasta el",
    "Produit": "Producto",
    "Proportions": "Proporción",
    "Proposer le téléchargement du fichier": "Ofrecer la descarga del archivo",
    "propriété": "propiedad",
    "Propriété écrite à la main : l’éditeur ne la connaît pas et ne peut donc pas la vérifier.": "Propiedad escrita a mano: el editor no la conoce y por tanto no puede comprobarla.",
    "propriétés": "propiedades",
    "Propriétés de l’image": "Propiedades de la imagen",
    "Propriétés du bloc": "Propiedades del bloque",
    "Protéines": "Proteínas",
    "Que décrit cette page ?": "¿Qué describe esta página?",
    "Quelques phrases qui décrivent la chose. Souvent reprise sous le titre dans les résultats.": "Unas frases que describen la cosa. A menudo se muestra bajo el título en los resultados.",
    "Question": "Pregunta",
    "Questions": "Preguntas",
    "Questions fréquentes": "Preguntas frecuentes",
    "Qui a écrit ce contenu : une personne, ou l’entreprise elle-même.": "Quién escribió este contenido: una persona o la propia empresa.",
    "Qui publie ce contenu — le plus souvent votre entreprise.": "Quién publica este contenido, normalmente su empresa.",
    "Quitter le plein écran": "Salir de pantalla completa",
    "Raison sociale": "Razón social",
    "Rang": "Posición",
    "Rapport": "Relación",
    "Rapport largeur / hauteur": "Relación ancho / alto",
    "Recette": "Receta",
    "Recherche en cours…": "Buscando…",
    "Rechercher": "Buscar",
    "Rechercher dans ce dossier": "Buscar en esta carpeta",
    "Rechercher dans ce dossier…": "Buscar en esta carpeta…",
    "Rechercher un bloc": "Buscar un bloque",
    "Recommandé : un diaporama qui repart tout seul pendant qu’on le regarde est pénible, et empêche de revenir en arrière.": "Recomendado: un carrusel que vuelve a arrancar solo mientras se mira resulta molesto e impide retroceder.",
    "Reconditionné": "Reacondicionado",
    "Réduire": "Reducir",
    "Référence": "Referencia",
    "Référence (SKU)": "Referencia (SKU)",
    "Référence du fabricant": "Referencia del fabricante",
    "Référencement": "Posicionamiento",
    "Référencement de la page": "Posicionamiento de la página",
    "Région ou département": "Región o provincia",
    "Réglages": "Ajustes",
    "réglages retrouvés": "ajustes encontrados",
    "Relation (rel)": "Relación (rel)",
    "Rémunération": "Remuneración",
    "Rendez-vous du mois": "Citas del mes",
    "Renommage…": "Renombrando…",
    "Renommer": "Renombrar",
    "Renommer le fichier": "Renombrar el archivo",
    "Renommer…": "Renombrar…",
    "Repartir au début après la dernière vue": "Volver al principio tras la última vista",
    "Replier": "Plegar",
    "Réponse": "Respuesta",
    "Reporté": "Aplazado",
    "Réseaux sociaux": "Redes sociales",
    "Restauration…": "Restaurando…",
    "Restaurer": "Restaurar",
    "Retirer": "Quitar",
    "Retirer ce palier": "Quitar este umbral",
    "Retirer cette image": "Quitar esta imagen",
    "Retirer cette valeur": "Quitar este valor",
    "Retirer cette vue": "Quitar esta vista",
    "Retoucher cette image…": "Retocar esta imagen…",
    "Retoucher l’image…": "Retocar la imagen…",
    "Retour à": "Volver a",
    "Retournement": "Volteo",
    "Rétrécir la colonne": "Estrechar la columna",
    "return confirm('Quitter la page ?')": "return confirm('¿Salir de la página?')",
    "Rien de renseigné": "Nada rellenado",
    "Rien ne bouge pour qui a demandé à son système de réduire les animations : le texte reste alors lisible, arrêté.": "Nada se mueve para quien haya pedido a su sistema reducir las animaciones: el texto permanece legible, detenido.",
    "Rubrique": "Sección",
    "Rubrique de l’édition papier": "Sección de la edición impresa",
    "S’arrêter dès que le visiteur y touche": "Detenerse en cuanto el visitante lo toca",
    "Saisissez d’abord une adresse.": "Escriba primero una dirección.",
    "Saisissez une adresse et cliquez sur « Rechercher », ou entrez directement des coordonnées.": "Escriba una dirección y pulse «Buscar», o introduzca directamente las coordenadas.",
    "Samedi": "Sábado",
    "Sans bordure": "Sin borde",
    "Sans empattement": "Sin serifa",
    "Sans le son": "Sin sonido",
    "sans réglages dans la page": "sin ajustes en la página",
    "Sans symbole ni espace : 28 ou 28.50. La devise est indiquée à côté.": "Sin símbolo ni espacio: 28 o 28.50. La moneda se indica al lado.",
    "Script JavaScript": "Script JavaScript",
    "Script JavaScript...": "Script JavaScript...",
    "script vide": "script vacío",
    "Secondaire": "Secundario",
    "Section de langue": "Sección de idioma",
    "Sélectionner le bloc parent": "Seleccionar el bloque contenedor",
    "Sélectionnez du texte pour lui donner une langue": "Seleccione un texto para asignarle un idioma",
    "Semaine": "Semana",
    "Sens du défilement": "Sentido del desplazamiento",
    "Séparateur": "Separador",
    "Séparateur réglable": "Separador ajustable",
    "Séparateur vertical": "Separador vertical",
    "Séparateur vertical...": "Separador vertical...",
    "Sépare visuellement deux parties de la page": "Separa visualmente dos partes de la página",
    "Séparés par des virgules.": "Separadas por comas.",
    "Séparés par des virgules. Ils décrivent le sujet, pas la page.": "Separadas por comas. Describen el tema, no la página.",
    "Service": "Servicio",
    "Service à contacter": "Servicio de contacto",
    "Service client": "Atención al cliente",
    "Site web": "Sitio web",
    "Situe une adresse sur un plan OpenStreetMap": "Sitúa una dirección en un mapa de OpenStreetMap",
    "Sorte d’animation": "Tipo de animación",
    "Sorte de lien": "Tipo de enlace",
    "Souligné": "Subrayado",
    "Source (lien)": "Fuente (enlace)",
    "sourire, cœur, drapeau…": "sonrisa, corazón, bandera…",
    "Sous-titre": "Subtítulo",
    "Sous-titre à l’intérieur d’une section": "Un subtítulo dentro de una sección",
    "Stage": "Prácticas",
    "Style CSS écrit à même le lien": "Estilo CSS escrito en el propio enlace",
    "Style du lien": "Estilo del enlace",
    "Style du texte": "Estilo del texto",
    "Style prédéfini": "Estilo predefinido",
    "Sujet": "Tema",
    "Suppression dans {0} secondes": "Eliminando en {0} segundos",
    "Suppression…": "Eliminando…",
    "Supprimer": "Eliminar",
    "Supprimer ce dossier": "Eliminar esta carpeta",
    "Supprimer cet élément": "Eliminar este elemento",
    "Supprimer la colonne": "Eliminar la columna",
    "Supprimer la fiche": "Eliminar la ficha",
    "Supprimer la ligne et ses colonnes": "Eliminar la fila y sus columnas",
    "Supprimer le bloc": "Eliminar el bloque",
    "Supprimer le lien": "Quitar el enlace",
    "Supprimer le script": "Eliminar el script",
    "Supprimer le séparateur": "Eliminar el separador",
    "Supprimer les microdonnées": "Eliminar los microdatos",
    "Sur commande": "Bajo pedido",
    "Sur place": "Presencial",
    "Survolez le bloc puis cliquez sur « Modifier le diaporama » pour changer les vues et le défilement.": "Pase el ratón por el bloque y haga clic en «Editar el carrusel» para cambiar las vistas y el desplazamiento.",
    "Système": "Sistema",
    "Tableau": "Tabla",
    "Tablette": "Tableta",
    "Taille": "Tamaño",
    "Taille d’une portion": "Tamaño de una porción",
    "Taille des vignettes (px)": "Tamaño de las miniaturas (px)",
    "Taille du texte (ex : 1.5rem)": "Tamaño del texto (p. ej. 1.5rem)",
    "Tailles rapides": "Tamaños rápidos",
    "Tarif": "Tarifa",
    "tarifs": "tarifas",
    "Téléphone": "Teléfono",
    "Téléversement…": "Subiendo…",
    "Téléverser…": "Subir…",
    "Temps d’arrêt sur chaque vue (millisecondes)": "Pausa en cada vista (milisegundos)",
    "Temps de cuisson": "Tiempo de cocción",
    "Temps de préparation": "Tiempo de preparación",
    "Temps partiel": "Tiempo parcial",
    "Temps plein": "Tiempo completo",
    "Texte": "Texto",
    "Texte à afficher": "Texto que se mostrará",
    "Texte affiché par-dessus l’image": "Texto mostrado sobre la imagen",
    "Texte alternatif": "Texto alternativo",
    "Texte alternatif (lu par les lecteurs d’écran)": "Texto alternativo (leído por los lectores de pantalla)",
    "Texte animé": "Texto animado",
    "Texte animé...": "Texto animado...",
    "Texte de l’article": "Texto del artículo",
    "Texte de l’avis": "Texto de la reseña",
    "Texte de l’épingle": "Texto del marcador",
    "Texte de la réponse": "Texto de la respuesta",
    "Texte de remplacement": "Texto alternativo",
    "Texte déplié": "Texto desplegado",
    "Texte déployable": "Texto desplegable",
    "Texte du bouton": "Texto del botón",
    "Texte par-dessus": "Texto superpuesto",
    "Titre": "Título",
    "Titre (accessibilité)": "Título (accesibilidad)",
    "Titre affiché": "Título mostrado",
    "Titre affiché au survol": "Título mostrado al pasar el ratón",
    "Titre cliquable": "Título en el que se puede pulsar",
    "Titre de niveau 2": "Título de nivel 2",
    "Titre de niveau 3": "Título de nivel 3",
    "Titre du lien": "Título del enlace",
    "Titre du lien (bulle d’aide au survol)": "Título del enlace (información al pasar el ratón)",
    "Titre du site avec son logo": "Nombre del sitio con su logotipo",
    "Titre principal d’une section": "El título principal de una sección",
    "Tours, 14 mars 2026": "Tours, 14 de marzo de 2026",
    "Tous": "Todos",
    "Tous les réseaux": "Todas las redes",
    "Tout ce qu’il contient sera perdu.": "Se perderá todo su contenido.",
    "Tout détruire": "Destruirlo todo",
    "Toutes": "Todas",
    "Toutes les langues": "Todos los idiomas",
    "Toutes ses versions seront perdues.": "Se perderán todas sus versiones.",
    "Trait horizontal": "Línea horizontal",
    "Travailler dans une seule langue": "Trabajar en un solo idioma",
    "Type": "Tipo",
    "Type de contrat": "Tipo de contrato",
    "Type de cuisine": "Tipo de cocina",
    "type inconnu": "tipo desconocido",
    "Type MIME": "Tipo MIME",
    "Types acceptés": "Tipos aceptados",
    "Typographie": "Tipografía",
    "Un article à vendre : son prix, sa disponibilité, ses avis.": "Un artículo a la venta: su precio, su disponibilidad, sus reseñas.",
    "Un article d’actualité, daté et signé.": "Un artículo de actualidad, fechado y firmado.",
    "Un article publié au fil de l’eau sur un blog.": "Un artículo publicado sobre la marcha en un blog.",
    "Un bloc de texte courant": "Un bloque de texto normal",
    "Un bouton « Acheter » qui ouvre le paiement PayPal": "Un botón «Comprar» que abre el pago con PayPal",
    "Un bouton qui enregistre votre événement dans l’agenda du visiteur": "Un botón que guarda su evento en la agenda del visitante",
    "Un bouton qui met en avant l’action principale": "Un botón que destaca la acción principal",
    "Un code qui désigne cette chose sans ambiguïté : référence interne, numéro de catalogue.": "Un código que designa esta cosa sin ambigüedad: referencia interna, número de catálogo.",
    "Un contenu créé : texte, image, vidéo, logiciel.": "Un contenido creado: texto, imagen, vídeo, software.",
    "Un cours ou une formation proposée.": "Un curso o una formación ofrecida.",
    "Un endroit : salle, monument, parking.": "Un lugar: sala, monumento, aparcamiento.",
    "Un espace vertical ou un filet de séparation": "Un espacio vertical o una línea de separación",
    "Un établissement où l’on se rend : boutique, cabinet, restaurant.": "Un establecimiento al que se acude: tienda, consulta, restaurante.",
    "Un formulaire dont les messages arrivent dans votre boîte mail": "Un formulario cuyos mensajes llegan a su buzón",
    "Un identifiant commence par une lettre et ne contient ni espace ni accent. Par exemple : tarifs, nos-services, contact2.": "Un identificador empieza por una letra y no contiene espacios ni acentos. Por ejemplo: tarifas, nuestros-servicios, contacto2.",
    "Un jour ou un groupe de jours, avec l’heure d’ouverture et de fermeture.": "Un día o un grupo de días, con la hora de apertura y de cierre.",
    "Un logiciel ou une application mobile.": "Un software o una aplicación móvil.",
    "Un mot sans espace, unique dans la page. Un lien pourra y conduire avec « #tarifs », et les scripts du site s’en servent pour retrouver ce bloc.": "Una palabra sin espacios, única en la página. Un enlace podrá llevar hasta él con «#tarifas», y los scripts del sitio la usan para localizar este bloque.",
    "Un nombre entier (3), un nombre décimal pour laisser deviner la suivante (1.15), ou « auto » pour suivre la largeur de chaque vue.": "Un número entero (3), un decimal para dejar entrever la siguiente (1.15), o «auto» para seguir el ancho de cada vista.",
    "Un poste à pourvoir.": "Un puesto vacante.",
    "Un pour l’accueil, deux pour la rubrique, et ainsi de suite.": "Uno para la portada, dos para la sección, y así sucesivamente.",
    "Un prix, une devise et une disponibilité.": "Un precio, una moneda y una disponibilidad.",
    "Un second nom sous lequel la chose est aussi connue.": "Un segundo nombre por el que también se conoce la cosa.",
    "Un service et la façon de le joindre.": "Un servicio y la manera de contactarlo.",
    "Un service proposé plutôt qu’un objet vendu.": "Un servicio ofrecido en lugar de un objeto vendido.",
    "Un texte de fond : billet, dossier, tribune.": "Un texto de fondo: entrada, reportaje, tribuna.",
    "Un titre accrocheur": "Un título que llama la atención",
    "Un titre cliquable qui déplie un texte : idéal pour une foire aux questions": "Un título en el que se pulsa para desplegar un texto: ideal para preguntas frecuentes",
    "Un titre et un texte éditables directement dans la page": "Un título y un texto que se editan directamente en la página",
    "Une à deux phrases, environ 160 caractères : c’est le texte affiché sous le titre dans les résultats de recherche.": "Una o dos frases, unos 160 caracteres: es el texto que aparece bajo el título en los resultados de búsqueda.",
    "Une adresse complète, telle qu’on l’écrit sur une enveloppe.": "Una dirección completa, tal como se escribe en un sobre.",
    "Une autre propriété, écrite à la main…": "Otra propiedad, escrita a mano…",
    "Une citation mise en avant avec son auteur": "Una cita destacada con su autor",
    "Une date à retenir : concert, portes ouvertes, formation.": "Una fecha a recordar: concierto, jornada de puertas abiertas, formación.",
    "Une entreprise, une association, une administration.": "Una empresa, una asociación, una administración.",
    "Une étape du fil d’Ariane : sa position, son nom et son adresse.": "Un paso de la ruta de navegación: su posición, su nombre y su dirección.",
    "Une étape du mode d’emploi.": "Un paso de las instrucciones.",
    "Une image avec sa légende et un lien optionnel": "Una imagen con su leyenda y un enlace opcional",
    "Une image décrite pour elle-même : auteur, licence, dimensions.": "Una imagen descrita por sí misma: autor, licencia, dimensiones.",
    "Une ligne de colonnes côte à côte, qui s’empilent sur mobile": "Una fila de columnas contiguas que se apilan en el móvil",
    "Une marche à suivre, étape par étape.": "Un procedimiento, paso a paso.",
    "Une note isolée, celle d’un avis.": "Una valoración aislada, la de una reseña.",
    "Une page de questions-réponses. Les moteurs les affichent dépliables.": "Una página de preguntas y respuestas. Los buscadores las muestran desplegables.",
    "Une page ordinaire du site : présentation, mentions légales, contact.": "Una página corriente del sitio: presentación, aviso legal, contacto.",
    "Une personne : auteur, dirigeant, artisan.": "Una persona: autor, directivo, artesano.",
    "Une photo qui représente la chose. Les moteurs préfèrent une image large, d’au moins 1200 pixels.": "Una foto que representa la cosa. Los buscadores prefieren una imagen ancha, de al menos 1200 píxeles.",
    "Une phrase qui marque les esprits.": "Una frase que se recuerda.",
    "Une question et sa réponse.": "Una pregunta y su respuesta.",
    "Une recette de cuisine, avec ses ingrédients et ses étapes.": "Una receta de cocina, con sus ingredientes y sus pasos.",
    "Une somme et sa devise.": "Un importe y su moneda.",
    "Une valeur avec son unité : un poids, une longueur.": "Un valor con su unidad: un peso, una longitud.",
    "Une vidéo hébergée ou intégrée dans la page.": "Un vídeo alojado o integrado en la página.",
    "Unité": "Unidad",
    "Utiliser ce fichier": "Usar este archivo",
    "Utiliser ces fichiers": "Usar estos archivos",
    "Valeur": "Valor",
    "Valeurs nutritionnelles": "Información nutricional",
    "Veigné": "Veigné",
    "Vendeur": "Vendedor",
    "Vendredi": "Viernes",
    "Vérification des quotas…": "Comprobando las cuotas…",
    "Vérifier la fiche": "Comprobar la ficha",
    "Version enregistrée": "Versión guardada",
    "Version publiée uniquement en": "Versión publicada únicamente en",
    "Versions": "Versiones",
    "Vertical": "Vertical",
    "Vidéo": "Vídeo",
    "Vider": "Vaciar",
    "Videz ce champ pour la retirer.": "Vacíe este campo para quitarla.",
    "Ville": "Ciudad",
    "Vintage": "Vintage",
    "Voile sombre (0 à 100)": "Velo oscuro (0 a 100)",
    "Votre médiathèque est pleine. Supprimez des fichiers ou d’anciennes versions pour en ajouter.": "Su biblioteca está llena. Elimine archivos o versiones antiguas para añadir más.",
    "Votre référence interne, celle du bon de commande.": "Su referencia interna, la del pedido.",
    "Vous modifiez": "Está editando",
    "Vue": "Vista",
    "vue n’a pas d’image et ne montrerait rien sur le site. La retirer ?": "vista no tiene imagen y no mostraría nada en el sitio. ¿Quitarla?",
    "Vues affichées en même temps": "Vistas mostradas a la vez",
    "vues n’ont pas d’image et ne montreraient rien sur le site. Les retirer ?": "vistas no tienen imagen y no mostrarían nada en el sitio. ¿Quitarlas?",
    "Widget HTML": "Widget HTML",
    "YouTube, Vimeo, Dailymotion ou toute autre adresse intégrable": "YouTube, Vimeo, Dailymotion o cualquier otra dirección integrable",
    "Zone desservie": "Zona atendida",
    "Zone livrée": "Zona de entrega",
    "Zoom (1 = monde, 19 = rue)": "Zoom (1 = mundo, 19 = calle)",
    "Zoom à la molette de la souris": "Zoom con la rueda del ratón"
});
/* — ONLC : fin des chaînes des plugins — */
