/**
 * Paquet de langue « nl_NL » — Nederlands.
 *
 * Produit par tools/openmoji/build-i18n.js. Le cœur de l'éditeur ne livre pas de paquet pour
 * cette langue ; celui-ci ne porte donc que les chaînes des plugins ONLC.
 */

/* — ONLC : début des chaînes des plugins — */
hugerte.addI18n("nl_NL", {
    "— choisir —": "— kiezen —",
    "— Choisir une ancre —": "— Een anker kiezen —",
    "⚠️ DESTRUCTION": "⚠️ VERNIETIGING",
    "1 vue": "1 weergave",
    "1:1 (carré)": "1:1 (vierkant)",
    "10 rue de la Paix, Paris": "Damrak 10, Amsterdam",
    "16:9 (paysage)": "16:9 (liggend)",
    "2 à 3 jours ouvrés": "2 tot 3 werkdagen",
    "200 g de farine": "200 g bloem",
    "21:9 (cinéma)": "21:9 (bioscoop)",
    "240 calories": "240 calorieën",
    "26 rue de la Roquille": "Roquillestraat 26",
    "3000 millisecondes valent trois secondes. En dessous de 2000, la plupart des visiteurs n’ont pas le temps de lire.": "3000 milliseconden zijn drie seconden. Onder de 2000 heeft de meeste bezoekers geen tijd om te lezen.",
    "4 parts": "4 porties",
    "61 rue du Château d’Eau, 33000 Bordeaux": "Grote Markt 1, 2000 Antwerpen",
    "9:16 (vertical)": "9:16 (staand)",
    "À l’emplacement du curseur": "Op de plaats van de cursor",
    "À n’activer que sur un diaporama qui occupe l’écran : sinon la molette cesse de faire défiler la page dès qu’on passe dessus.": "Alleen inschakelen op een diavoorstelling die het scherm vult: anders stopt het wiel met het scrollen van de pagina zodra men erover beweegt.",
    "À partir de": "Vanaf",
    "À renseigner": "In te vullen",
    "Abonnement annuel": "Jaarabonnement",
    "Accessible sans payer": "Gratis toegankelijk",
    "Acheter": "Kopen",
    "Action javascript au clic": "Javascript-actie bij klikken",
    "Actions": "Acties",
    "Actuelle": "Huidige",
    "Adresse": "Adres",
    "Adresse à laquelle les messages du formulaire seront envoyés.": "Adres waarnaar de berichten van het formulier worden gestuurd.",
    "Adresse de l’agenda": "Adres van de agenda",
    "Adresse de l’événement": "Adres van het evenement",
    "Adresse de l’image": "Adres van de afbeelding",
    "Adresse de la page": "Adres van de pagina",
    "Adresse de la vidéo": "Adres van de video",
    "Adresse du fichier": "Adres van het bestand",
    "Adresse du fichier vidéo": "Adres van het videobestand",
    "Adresse du lecteur intégré": "Adres van de ingesloten speler",
    "Adresse du lien": "Adres van de link",
    "Adresse du lieu": "Adres van de locatie",
    "Adresse e-mail": "E-mailadres",
    "Adresse personnalisée…": "Aangepast adres…",
    "Adresse postale": "Postadres",
    "Affichage": "Weergave",
    "Affiche du code sans le formater": "Toont code precies zoals ze geschreven is",
    "Affiche un PDF directement dans la page, page après page": "Toont een pdf rechtstreeks in de pagina, bladzijde na bladzijde",
    "Affiche une autre page web à l’intérieur de la vôtre": "Toont een andere webpagina binnen de uwe",
    "Afficher comme un visiteur": "Tonen als bezoeker",
    "Afficher les flèches précédent / suivant": "Pijlen vorige / volgende tonen",
    "Afficher les intitulés sur les vignettes": "Bijschriften op de miniaturen tonen",
    "Afficher les outils de blocs": "Blokgereedschap tonen",
    "Afficher les points de position": "Positiestippen tonen",
    "Afficher une barre de défilement": "Een schuifbalk tonen",
    "Agenda": "Agenda",
    "Agenda partagé": "Gedeelde agenda",
    "Agrandir": "Vergroten",
    "Ajoute du vide entre deux blocs, hauteur réglable": "Voegt instelbare lege ruimte toe tussen twee blokken",
    "Ajoutées": "Toegevoegd",
    "Ajouter": "Toevoegen",
    "Ajouter à la page": "Aan de pagina toevoegen",
    "Ajouter à mon calendrier": "Aan mijn agenda toevoegen",
    "Ajouter des colonnes": "Kolommen toevoegen",
    "Ajouter des colonnes...": "Kolommen toevoegen...",
    "Ajouter des images à la fin…": "Afbeeldingen achteraan toevoegen…",
    "Ajouter des images au début…": "Afbeeldingen vooraan toevoegen…",
    "Ajouter des images…": "Afbeeldingen toevoegen…",
    "Ajouter un bloc": "Een blok toevoegen",
    "Ajouter un bloc à la fin": "Een blok achteraan toevoegen",
    "Ajouter un bloc après": "Een blok erna toevoegen",
    "Ajouter un bloc au début": "Een blok vooraan toevoegen",
    "Ajouter un bloc avant": "Een blok ervoor toevoegen",
    "Ajouter un bloc...": "Een blok toevoegen...",
    "Ajouter un espace vertical de la hauteur de votre choix": "Verticale ruimte toevoegen met de hoogte van uw keuze",
    "Ajouter un palier": "Een breekpunt toevoegen",
    "Ajouter un rendez-vous": "Een afspraak toevoegen",
    "Ajouter une classe": "Een klasse toevoegen",
    "Ajouter une colonne": "Een kolom toevoegen",
    "Ajouter une configuration": "Een configuratie toevoegen",
    "Ajouter une description pour les moteurs…": "Een beschrijving voor zoekmachines toevoegen…",
    "Ajouter une propriété…": "Een eigenschap toevoegen…",
    "Ajouter une valeur": "Een waarde toevoegen",
    "Ajouter une vue vide": "Een lege weergave toevoegen",
    "Ajoutez au moins une image à la galerie": "Voeg minstens één afbeelding aan de galerij toe",
    "Ajustée à la taille de l'écran": "Aangepast aan de schermgrootte",
    "Alignement": "Uitlijning",
    "Ancre dans la page": "Anker op deze pagina",
    "Angle (°)": "Hoek (°)",
    "Année précédente": "Vorig jaar",
    "Année suivante": "Volgend jaar",
    "Annulé": "Geannuleerd",
    "Annuler": "Annuleren",
    "Aperçu comme un visiteur": "Voorbeeld als bezoeker",
    "Aperçu comme un visiteur...": "Voorbeeld als bezoeker...",
    "Aperçu de la page": "Voorbeeld van de pagina",
    "Apparence": "Uiterlijk",
    "Application": "Toepassing",
    "Arrondi": "Afgerond",
    "Article": "Artikel",
    "Article de presse": "Nieuwsartikel",
    "Article non renseigné": "Item niet ingevuld",
    "Assistance technique": "Technische ondersteuning",
    "Au format international, indicatif compris.": "In internationaal formaat, landnummer inbegrepen.",
    "Au format ISO 8601 : PT20M vaut 20 minutes, PT1H30M une heure et demie.": "In ISO 8601-formaat: PT20M betekent 20 minuten, PT1H30M anderhalf uur.",
    "Au format ISO 8601 : PT2M30S vaut 2 minutes 30.": "In ISO 8601-formaat: PT2M30S betekent 2 minuten 30 seconden.",
    "Au-delà de cette date, les moteurs cessent d’afficher le prix.": "Na deze datum tonen zoekmachines de prijs niet meer.",
    "Aucun code pour le moment.": "Nog geen code.",
    "Aucun fichier choisi.": "Geen bestand gekozen.",
    "Aucun fichier ne correspond à cette recherche.": "Geen enkel bestand komt overeen met deze zoekopdracht.",
    "Aucun lieu ne correspond. Essayez une adresse plus simple, ou entrez les coordonnées à la main.": "Geen enkele locatie komt overeen. Probeer een eenvoudiger adres, of voer de coördinaten met de hand in.",
    "Aucun palier : le diaporama montre le même nombre de vues sur tous les écrans.": "Geen breekpunten: de diavoorstelling toont op elk scherm evenveel weergaven.",
    "Aucun rendez-vous pour ce mois. Ajoutez-en un pour le voir apparaître dans la grille.": "Geen afspraken deze maand. Voeg er een toe om die in het raster te zien verschijnen.",
    "Aucune": "Geen",
    "Aucune — visible par tous": "Geen — zichtbaar voor iedereen",
    "Aucune adresse renseignée": "Geen adres opgegeven",
    "Aucune classe du site ne commence ainsi. Vous pouvez tout de même l’ajouter.": "Geen enkele klasse van de site begint zo. U kunt ze toch toevoegen.",
    "Aucune classe pour l’instant.": "Nog geen klasse.",
    "Aucune description": "Geen beschrijving",
    "Aucune feuille de style de site n’est déclarée : écrivez le nom de la classe à la main.": "Er is geen stijlblad van de site opgegeven: schrijf de naam van de klasse met de hand.",
    "Aucune image choisie.": "Geen afbeelding gekozen.",
    "Aucune image pour l’instant. Cliquez sur « Ajouter des images… » pour en choisir.": "Nog geen afbeeldingen. Klik op « Afbeeldingen toevoegen… » om er te kiezen.",
    "Aucune propriété renseignée pour l’instant.": "Nog geen eigenschap ingevuld.",
    "Auteur": "Auteur",
    "Autre nom": "Andere naam",
    "autres : continuez à écrire pour les filtrer.": "meer: blijf typen om ze te filteren.",
    "Autres pages qui parlent de cette chose": "Andere pagina's over dit ding",
    "Avancé": "Geavanceerd",
    "Avancer à la molette de la souris": "Vooruit met het muiswiel",
    "Avancer avec les flèches du clavier": "Vooruit met de pijltjestoetsen",
    "Avancer tout seul": "Vanzelf doorgaan",
    "Avant retouche": "Voor bewerking",
    "Avec empattement": "Met schreef",
    "Avis": "Beoordeling",
    "Balise « div ». L’identifiant et les classes voyagent avec le bloc : ils sont écrits tels quels dans la page publiée.": "« div »-tag. De identificatie en de klassen reizen mee met het blok: ze worden onveranderd in de gepubliceerde pagina geschreven.",
    "Bandeau d’introduction avec titre, texte et bouton": "Openingsbanner met titel, tekst en knop",
    "Barre de progression": "Voortgangsbalk",
    "Bas centre": "Onder midden",
    "Bas droite": "Onder rechts",
    "Bas gauche": "Onder links",
    "Billet de blog": "Blogbericht",
    "Billetterie": "Kaartverkoop",
    "Bloc de texte": "Tekstblok",
    "Bloc prédéfini": "Kant-en-klaar blok",
    "Blocs et éléments": "Blokken en elementen",
    "Blocs et éléments du site": "Blokken en elementen van de site",
    "Blocs et éléments du site...": "Blokken en elementen van de site...",
    "Blocs prédéfinis": "Kant-en-klare blokken",
    "Blocs prédéfinis...": "Kant-en-klare blokken...",
    "boulangerie, pain bio, Bordeaux": "bakkerij, biologisch brood, Gent",
    "Bouton": "Knop",
    "Bouton d’appel à l’action": "Actieknop",
    "Bouton de paiement PayPal": "PayPal-betaalknop",
    "Bouton ombré": "Knop met schaduw",
    "Bouton, vidéo, carte…": "Knop, video, kaart…",
    "Bouton, vidéo, menu, contact…": "Knop, video, menu, contact…",
    "Boutons de partage": "Deelknoppen",
    "Boutons de partage (minuscules)": "Deelknoppen (piepklein)",
    "Boutons de partage (petits)": "Deelknoppen (klein)",
    "Calendrier du mois": "Maandkalender",
    "Calories": "Calorieën",
    "Candidatures jusqu’au": "Sollicitaties tot",
    "Carte": "Kaart",
    "Carte déplaçable (Leaflet)": "Verschuifbare kaart (Leaflet)",
    "Carte déplaçable par le visiteur": "Bezoekers kunnen de kaart verschuiven en zoomen",
    "Cartes empilées": "Gestapelde kaarten",
    "Cascade (rangées justifiées)": "Cascade (uitgevulde rijen)",
    "Catégorie": "Categorie",
    "Ce diaporama n’a aucune vue. Ajoutez-en une pour qu’il montre quelque chose.": "Deze diavoorstelling heeft geen enkele weergave. Voeg er een toe zodat ze iets toont.",
    "Ce diaporama n’a pas de réglages dans la page : aucun appel « new Swiper(…) » ne le désigne. Ses images restent modifiables.": "Deze diavoorstelling heeft geen instellingen in de pagina: geen enkele aanroep « new Swiper(…) » verwijst ernaar. Haar afbeeldingen blijven bewerkbaar.",
    "Ce dossier est vide. Déposez des fichiers ici, ou utilisez « Téléverser… ».": "Deze map is leeg. Zet hier bestanden neer, of gebruik « Uploaden… ».",
    "Ce qu’il faut faire": "Wat er te doen staat",
    "Ce que contient une portion.": "Wat één portie bevat.",
    "Ce que le produit coûte et s’il est en stock. C’est ce bloc qui fait apparaître le prix dans Google.": "Wat het product kost en of het op voorraad is. Dit blok laat de prijs in Google verschijnen.",
    "Ce que montre l’image, en une phrase": "Wat de afbeelding toont, in één zin",
    "Ce qui est évalué": "Wat beoordeeld wordt",
    "Ce type de fichier n’est pas accepté": "Dit bestandstype wordt niet aanvaard",
    "Centre": "Midden",
    "Centré": "Gecentreerd",
    "Centrer la vue courante": "De huidige weergave centreren",
    "Ces propriétés sont exigées et restent vides :": "Deze eigenschappen zijn verplicht en blijven leeg:",
    "Cet élément n’est pas reconnu par l’éditeur : il sera réécrit tel quel dans la page.": "De editor herkent dit element niet: het wordt onveranderd terug in de pagina geschreven.",
    "Cette action est définitive.": "Dit is definitief.",
    "Cette action ne peut pas être annulée.": "Dit kan niet ongedaan worden gemaakt.",
    "Cette page contenait plusieurs fiches de référencement. Une seule a été conservée : les moteurs de recherche n’en lisent qu’une, et choisissent au hasard quand il y en a plusieurs.": "Deze pagina bevatte meerdere zoekmachinefiches. Slechts één is bewaard: zoekmachines lezen er maar één, en kiezen willekeurig wanneer er meerdere zijn.",
    "Cette valeur est publiée dans toutes les langues. Choisissez une langue pour en écrire une version qui ne paraîtra que dans celle-là.": "Deze waarde wordt in alle talen gepubliceerd. Kies een taal om er een versie van te schrijven die alleen in die taal verschijnt.",
    "Cette vue contient autre chose que des images. Elle se modifie directement dans la page.": "Deze weergave bevat iets anders dan afbeeldingen. Ze wordt rechtstreeks in de pagina bewerkt.",
    "Cette vue ne contient pas qu’une image — plusieurs images, ou une mise en page. Elle est déplaçable, mais son contenu n’est pas réécrit.": "Deze weergave bevat niet één enkele afbeelding: er zijn er meerdere, of er is een opmaak. Ze kan verplaatst worden, maar haar inhoud wordt nooit herschreven.",
    "Changer cet emoji": "Deze emoji wijzigen",
    "Changer cette icône": "Dit pictogram wijzigen",
    "Changer cette image": "Deze afbeelding wijzigen",
    "Changer de type de contenu…": "Van inhoudstype veranderen…",
    "Chaque palier s’applique à partir de la largeur indiquée, et jusqu’au palier suivant. En dessous du premier palier, ce sont les réglages de l’onglet « Affichage » qui s’appliquent.": "Elk breekpunt geldt vanaf de aangegeven breedte, tot aan het volgende breekpunt. Onder het eerste breekpunt gelden de instellingen van het tabblad « Weergave ».",
    "Chaque version d’un fichier compte pour un fichier.": "Elke versie van een bestand telt als één bestand.",
    "Chaque vue est une image du diaporama. L’ordre de la liste est celui du défilement.": "Elke weergave is een afbeelding van de diavoorstelling. De volgorde van de lijst is die van het doorlopen.",
    "Chargement asynchrone (async)": "Asynchroon laden (async)",
    "Chargement du dossier…": "De map wordt geladen…",
    "Chasse fixe": "Vaste breedte",
    "Chemin du dossier": "Pad van de map",
    "Choisir cette image dans la médiathèque": "Deze afbeelding in de mediabibliotheek kiezen",
    "Choisir la disposition des colonnes": "De kolomindeling kiezen",
    "Choisir ou téléverser un média…": "Een bestand kiezen of uploaden…",
    "Choisir un fichier dans l’explorateur de médias": "Een bestand kiezen in de mediabibliotheek",
    "Choisir un fichier…": "Een bestand kiezen…",
    "Choisir une image dans la médiathèque ou en téléverser une": "Een afbeelding in de bibliotheek kiezen of er een uploaden",
    "Choisir une image…": "Een afbeelding kiezen…",
    "Choisir…": "Kiezen…",
    "Choisissez d’abord ce que décrit cette page : sans type de contenu, les moteurs ne savent pas quoi faire de la fiche.": "Kies eerst wat deze pagina beschrijft: zonder inhoudstype weten zoekmachines niet wat ze met de fiche aan moeten.",
    "Choisissez l’élément à insérer": "Kies het element dat u wilt invoegen",
    "Choisissez le bloc à ajouter": "Kies het blok dat u wilt toevoegen",
    "Choisissez le bloc à insérer": "Kies het blok dat u wilt invoegen",
    "Choisissez le bon lieu dans la liste :": "Kies de juiste locatie in de lijst:",
    "Choisissez le fichier PDF à afficher": "Kies het pdf-bestand dat u wilt tonen",
    "Choisissez le mois dans la grille, ou laissez « Mois en cours » pour un calendrier qui se met à jour tout seul.": "Kies de maand in het raster, of laat « Huidige maand » staan voor een kalender die zichzelf bijwerkt.",
    "Choisissez un pdf dans votre médiathèque, ou donnez l’adresse d’un fichier hébergé ailleurs.": "Kies een pdf in uw mediabibliotheek, of geef het adres op van een bestand dat elders staat.",
    "Choisissez une image": "Kies een afbeelding",
    "Choisissez une image avant d'enregistrer.": "Kies een afbeelding voordat u opslaat.",
    "Choisissez une image dans votre médiathèque, ou donnez l’adresse d’une image hébergée ailleurs.": "Kies een afbeelding in uw mediabibliotheek, of geef het adres op van een afbeelding die elders staat.",
    "Chose": "Ding",
    "Cinq par défaut. À préciser si votre échelle est différente.": "Standaard vijf. Geef het op als uw schaal anders is.",
    "Citation": "Citaat",
    "Classe ajoutée à la page en cours de consultation.": "Klasse toegevoegd aan de pagina die bekeken wordt.",
    "Classe CSS contenant": "CSS-klasse van de omhulling",
    "Classe CSS du bouton": "CSS-klasse van de knop",
    "Classe CSS élément": "CSS-klasse van het element",
    "Classe CSS élément actif": "CSS-klasse van het huidige element",
    "Classe posée sur chaque page du menu.": "Klasse op elke pagina van het menu.",
    "Classe posée sur la liste qui entoure les pages.": "Klasse op de lijst rond de pagina's.",
    "Classes CSS": "CSS-klassen",
    "Classes de la feuille de style du site et des autres blocs de la page.": "Klassen uit het stijlblad van de site en uit de andere blokken van de pagina.",
    "Classes du site.": "Klassen van de site.",
    "Clignotant": "Knipperend",
    "Cliquez pour sélectionner ce bloc, puis « Modifier le bloc » pour le régler.": "Klik om dit blok te selecteren, en dan op « Het blok bewerken » om het in te stellen.",
    "Cliquez sur un emoji pour l’insérer. Les dessins sont ceux d’OpenMoji : ils s’affichent de la même façon sur tous les appareils.": "Klik op een emoji om die in te voegen. De tekeningen komen van OpenMoji: ze zien er op elk apparaat hetzelfde uit.",
    "Cliquez sur un fichier pour voir ses informations et les actions possibles. Un double clic le choisit directement.": "Klik op een bestand om de gegevens en de mogelijke acties te zien. Een dubbelklik kiest het meteen.",
    "Cliquez sur une icône pour l’insérer. Elle prend la taille et la couleur du texte qui l’entoure.": "Klik op een pictogram om het in te voegen. Het neemt de grootte en de kleur van de omringende tekst over.",
    "Cochez les réseaux à proposer. Si vous n’en cochez aucun, tous seront affichés.": "Vink de netwerken aan die u wilt aanbieden. Vinkt u er geen aan, dan worden ze allemaal getoond.",
    "Code court": "Shortcode",
    "Code de la formation": "Cursuscode",
    "Code HTML": "HTML-code",
    "Code JavaScript": "JavaScript-code",
    "Code non reconnu : il sera réécrit tel quel dans la page.": "Niet-herkende code: die wordt onveranderd terug in de pagina geschreven.",
    "Code postal": "Postcode",
    "Code source": "Broncode",
    "Code source HTML": "HTML-broncode",
    "Code source HTML...": "HTML-broncode...",
    "Code-barres (EAN 13)": "Streepjescode (EAN 13)",
    "Colle un code d’intégration fourni par un service tiers": "Plakt een insluitcode van een andere dienst",
    "Comment passer commande ?": "Hoe plaats ik een bestelling?",
    "Commerce": "Handel",
    "Commerce de proximité": "Buurtwinkel",
    "Commercial": "Verkoop",
    "Compléter les langues manquantes": "De ontbrekende talen aanvullen",
    "Compte PayPal du vendeur": "PayPal-rekening van de verkoper",
    "Conditions de livraison": "Leveringsvoorwaarden",
    "Conseillées": "Aanbevolen",
    "Construction de l’aperçu…": "Het voorbeeld wordt opgebouwd…",
    "Contenu": "Inhoud",
    "Contenu libre :": "Vrije inhoud:",
    "Contenus": "Inhoud",
    "Contour": "Omtrek",
    "Coordonnées géographiques": "Geografische coördinaten",
    "Copie…": "Bezig met kopiëren…",
    "Copier": "Kopiëren",
    "Copier vers": "Kopiëren naar",
    "Copier vers…": "Kopiëren naar…",
    "Coque de carte Renault": "Hoesje voor Renault-kaartsleutel",
    "Couleur": "Kleur",
    "Couleur d’accentuation": "Accentkleur",
    "Couleur de fond": "Achtergrondkleur",
    "Couleur de l’ombre": "Kleur van de schaduw",
    "Couleur du filet": "Kleur van de lijn",
    "Couleur du texte": "Tekstkleur",
    "Création…": "Bezig met aanmaken…",
    "Créer": "Aanmaken",
    "Créer une image": "Een afbeelding maken",
    "CSS personnalisé (appliqué au bloc image)": "Aangepaste CSS (toegepast op het afbeeldingsblok)",
    "Cube": "Kubus",
    "Cuisine": "Keuken",
    "Date": "Datum",
    "Date de création": "Oprichtingsdatum",
    "Date de début": "Begindatum",
    "Date de dernière mise à jour": "Datum van laatste bijwerking",
    "Date de fin": "Einddatum",
    "Date de mise en ligne": "Datum van publicatie online",
    "Date de publication": "Publicatiedatum",
    "De « € » à « €€€€ », ou une fourchette : « 15 € – 40 € ».": "Van « € » tot « €€€€ », of een vork: « € 15 – € 40 ».",
    "Début": "Begin",
    "Débutant": "Beginner",
    "Décrire la page pour les moteurs (microdonnées)…": "De pagina beschrijven voor zoekmachines (microdata)…",
    "Décrivent le contenu de cette page pour les moteurs de recherche. Rien n’en paraît sur le site.": "Beschrijven de inhoud van deze pagina voor zoekmachines. Niets ervan verschijnt op de site.",
    "Décrivez votre offre en une phrase.": "Beschrijf uw aanbod in één zin.",
    "Défilant": "Schuivend",
    "Défilement": "Doorlopen",
    "Défilement libre, sans s’aligner sur une vue": "Vrij doorlopen, zonder op een weergave uit te lijnen",
    "Définir la langue": "De taal instellen",
    "Définir la langue de ce bloc": "De taal van dit blok instellen",
    "Définir la langue de la sélection": "De taal van de selectie instellen",
    "Dégradé : angle (°)": "Verloop: hoek (°)",
    "Dégradé : arrivée": "Verloop: eindpunt",
    "Dégradé : couleur d’arrivée": "Verloop: eindkleur",
    "Dégradé : couleur de départ": "Verloop: beginkleur",
    "Dégradé : départ": "Verloop: beginpunt",
    "Délai annoncé": "Aangekondigde termijn",
    "Déplacé en ligne": "Online verplaatst",
    "Déplacement…": "Bezig met verplaatsen…",
    "Déplacer": "Verplaatsen",
    "Déplacer cette vue": "Deze weergave verplaatsen",
    "Déplacer le bloc": "Het blok verplaatsen",
    "Déplacer vers": "Verplaatsen naar",
    "Déplacer vers…": "Verplaatsen naar…",
    "Déplié au chargement de la page": "Uitgeklapt bij het laden van de pagina",
    "Déplier": "Uitklappen",
    "Déposez vos fichiers pour les téléverser": "Zet uw bestanden neer om ze te uploaden",
    "Dernière vérification": "Laatst nagekeken",
    "Descendre": "Omlaag",
    "Descendre cette vue": "Deze weergave omlaag",
    "Descendre le bloc": "Het blok omlaag",
    "Description": "Beschrijving",
    "Description de la page": "Beschrijving van de pagina",
    "Description pour les moteurs de recherche": "Beschrijving voor zoekmachines",
    "Dessert": "Nagerecht",
    "Dessiner une image…": "Een afbeelding tekenen…",
    "Devise": "Munteenheid",
    "Diaporama": "Diavoorstelling",
    "Diaporama...": "Diavoorstelling...",
    "Dimanche": "Zondag",
    "Dimension": "Afmeting",
    "Disponibilité": "Beschikbaarheid",
    "Disposition": "Indeling",
    "Disposition des colonnes": "Kolomindeling",
    "Document PDF": "Pdf-document",
    "Dollar américain (USD)": "Amerikaanse dollar (USD)",
    "Dollar canadien (CAD)": "Canadese dollar (CAD)",
    "Dossier de destination": "Doelmap",
    "Dossier parent": "Bovenliggende map",
    "Droite": "Rechts",
    "Dupliquer cet élément": "Dit element dupliceren",
    "Dupliquer la ligne": "De rij dupliceren",
    "Dupliquer le bloc": "Het blok dupliceren",
    "Durée": "Duur",
    "Durée d’un cycle (secondes)": "Duur van één cyclus (seconden)",
    "Durée totale": "Totale duur",
    "E-mail destinataire": "E-mail van de ontvanger",
    "Écrans": "Schermen",
    "Écrire dans toutes les langues": "In alle talen schrijven",
    "Éditeur": "Uitgever",
    "Effet de transition": "Overgangseffect",
    "Élargir la colonne": "De kolom verbreden",
    "élément": "element",
    "Élément de liste": "Lijstitem",
    "éléments": "elementen",
    "Éléments du site": "Elementen van de site",
    "Éléments du site...": "Elementen van de site...",
    "Emoji ou icône": "Emoji of pictogram",
    "Emojis": "Emoji's",
    "Emojis et icônes": "Emoji's en pictogrammen",
    "Emojis et icônes...": "Emoji's en pictogrammen...",
    "Emojis seuls": "Alleen emoji's",
    "Emojis seuls...": "Alleen emoji's...",
    "Emplacement dans la page": "Plaats in de pagina",
    "Emplacements": "Locaties",
    "Employeur": "Werkgever",
    "En ligne": "Online",
    "En rupture": "Niet op voorraad",
    "En savoir plus": "Meer weten",
    "En stock": "Op voorraad",
    "En-tête de la page (<head>)": "Kop van de pagina (<head>)",
    "Encadré": "Omkaderd",
    "Endommagé": "Beschadigd",
    "Enregistrer": "Opslaan",
    "Énumération dont l’ordre compte : étapes, classement": "Een lijst waarin de volgorde telt: stappen, rangschikking",
    "Énumération sans ordre particulier": "Een lijst zonder bepaalde volgorde",
    "Épuisé": "Uit productie",
    "Espace": "Ruimte",
    "Espace entre les vignettes (px)": "Ruimte tussen de miniaturen (px)",
    "Espace entre les vues (pixels)": "Ruimte tussen de weergaven (pixels)",
    "Espace vertical": "Verticale ruimte",
    "Étape": "Stap",
    "Étapes": "Stappen",
    "Étapes du chemin": "Stappen van het pad",
    "État": "Staat",
    "État du produit": "Staat van het product",
    "Euro (EUR)": "Euro (EUR)",
    "Événement": "Evenement",
    "Événement non renseigné": "Evenement niet ingevuld",
    "Événements": "Evenementen",
    "Exécution différée (defer)": "Uitgestelde uitvoering (defer)",
    "Exigé": "Verplicht",
    "Explorateur de fichiers": "Bestandsverkenner",
    "Explorateur de fichiers...": "Bestandsverkenner...",
    "Facturation": "Facturatie",
    "Faire glisser au doigt ou à la souris": "Slepen met de vinger of de muis",
    "Fermer": "Sluiten",
    "Fermeture": "Sluiting",
    "Fichier": "Bestand",
    "Fichier de l’image": "Bestand van de afbeelding",
    "Fichier externe (src)": "Extern bestand (src)",
    "Fichier PDF": "Pdf-bestand",
    "fichier(s)": "bestand(en)",
    "fichiers": "bestanden",
    "fichiers sélectionnés": "geselecteerde bestanden",
    "Fil d’Ariane": "Kruimelpad",
    "Filet": "Lijn",
    "Filet simple": "Enkele lijn",
    "Fin": "Einde",
    "Fin de la page (avant </body>)": "Einde van de pagina (voor </body>)",
    "Fonction": "Functie",
    "Fondu": "Vervaging",
    "Format proportionnel": "Evenredige verhouding",
    "Formation": "Opleiding",
    "Forme des points": "Vorm van de stippen",
    "Formulaire de contact": "Contactformulier",
    "Formulaire de réservation": "Reserveringsformulier",
    "Formulaires": "Formulieren",
    "Fourchette de prix": "Prijsvork",
    "Fournitures": "Benodigdheden",
    "Frais de port": "Verzendkosten",
    "Frais, délais et zone de livraison.": "Kosten, termijnen en leveringsgebied.",
    "Franc suisse (CHF)": "Zwitserse frank (CHF)",
    "Français": "Frans",
    "Française": "Frans",
    "Fuseau horaire": "Tijdzone",
    "Galerie d’images": "Afbeeldingsgalerij",
    "Gauche": "Links",
    "Général": "Algemeen",
    "Gérant": "Zaakvoerder",
    "Glissement (par défaut)": "Schuiven (standaard)",
    "Grande": "Groot",
    "Grille de cellules pour présenter des données": "Een raster van cellen om gegevens te presenteren",
    "Haut centre": "Boven midden",
    "Haut droite": "Boven rechts",
    "Haut gauche": "Boven links",
    "Hauteur": "Hoogte",
    "Hauteur (pixels)": "Hoogte (pixels)",
    "Hauteur de la carte": "Hoogte van de kaart",
    "Hauteur de la zone de lecture": "Hoogte van het leesvenster",
    "Hauteur du séparateur": "Hoogte van de scheiding",
    "Hauteur fixe": "Vaste hoogte",
    "Hauteur maximale (px)": "Maximale hoogte (px)",
    "Hero": "Hero",
    "Heure": "Tijd",
    "Heure de début": "Begintijd",
    "Heure de fin": "Eindtijd",
    "Horaires d’ouverture": "Openingsuren",
    "Horizontal": "Horizontaal",
    "https://exemple.tld/photo.jpg": "https://voorbeeld.tld/foto.jpg",
    "Icônes": "Pictogrammen",
    "Icônes seules": "Alleen pictogrammen",
    "Icônes seules...": "Alleen pictogrammen...",
    "Identifiant (ancre)": "Identificatie (anker)",
    "Identifiant du bloc, utilisable comme ancre": "Identificatie van het blok, bruikbaar als anker",
    "Identifiant et classes du bloc": "Identificatie en klassen van het blok",
    "Identité": "Identiteit",
    "Il ne reste de la place que pour": "Er is nog maar plaats voor",
    "Image": "Afbeelding",
    "Image d’aperçu": "Voorbeeldafbeelding",
    "Image de fond": "Achtergrondafbeelding",
    "Image de la bibliothèque": "Afbeelding uit de bibliotheek",
    "Image principale": "Hoofdafbeelding",
    "Image...": "Afbeelding...",
    "Images": "Afbeeldingen",
    "Images de la galerie": "Afbeeldingen van de galerij",
    "Indiquez l’adresse de l’agenda": "Geef het adres van de agenda op",
    "Indiquez l’adresse de la page à intégrer": "Geef het adres op van de pagina die u wilt insluiten",
    "Indiquez l’adresse de la vidéo": "Geef het adres van de video op",
    "Indre-et-Loire": "Indre-et-Loire",
    "Ingrédients": "Ingrediënten",
    "Insérer des colonnes": "Kolommen invoegen",
    "Insérer ou modifier un lien": "Een link invoegen of bewerken",
    "Insérer ou modifier une image": "Een afbeelding invoegen of bewerken",
    "Insérer un emoji Unicode ou une icône Material Design": "Een Unicode-emoji of een pictogram invoegen",
    "Insérer un texte animé": "Een bewegende tekst invoegen",
    "Intègre un agenda public existant (Google Agenda, ICS…)": "Sluit een bestaande openbare agenda in (Google Agenda, ICS…)",
    "Intérim": "Tijdelijk",
    "Intervenant": "Uitvoerder",
    "Intitulé": "Bijschrift",
    "Intitulé affiché": "Getoond bijschrift",
    "Intitulé du poste": "Functietitel",
    "Jeudi": "Donderdag",
    "Jour": "Dag",
    "Jour du mois": "Dag van de maand",
    "L’adresse à laquelle cette chose est présentée. Le plus souvent, la page courante.": "Het adres waarop dit ding wordt gepresenteerd. Meestal de huidige pagina.",
    "L’adresse à laquelle l’événement se tient à distance.": "Het adres waarop het evenement op afstand plaatsvindt.",
    "L’adresse des conditions de réutilisation du contenu.": "Het adres van de hergebruiksvoorwaarden van de inhoud.",
    "L’adresse du compte PayPal qui recevra le paiement.": "Het adres van de PayPal-rekening die de betaling ontvangt.",
    "L’adresse que l’on met dans un cadre intégré, par exemple celle d’un lecteur YouTube.": "Het adres dat men in een ingesloten kader zet, bijvoorbeeld dat van een YouTube-speler.",
    "L’aperçu n’a pas pu être construit": "Het voorbeeld kon niet worden opgebouwd",
    "L’avis d’un client, avec sa note et son texte.": "De beoordeling van een klant, met de score en de tekst.",
    "l’élément": "het element",
    "L’image montrée avant la lecture.": "De afbeelding die vóór het afspelen wordt getoond.",
    "La chose dont ce contenu parle.": "Het ding waarover deze inhoud gaat.",
    "La grille d’un mois, avec vos rendez-vous inscrits jour par jour": "Het raster van een maand, met uw afspraken dag per dag ingeschreven",
    "La latitude et la longitude du lieu.": "De breedte- en lengtegraad van de locatie.",
    "La marque sous laquelle le produit est vendu.": "Het merk waaronder het product wordt verkocht.",
    "La mise en forme simple est acceptée : gras, liens, listes.": "Eenvoudige opmaak wordt aanvaard: vet, links, lijsten.",
    "La moyenne des avis et leur nombre.": "Het gemiddelde van de beoordelingen en hun aantal.",
    "La moyenne des avis. Ce sont les étoiles affichées sous le résultat.": "Het gemiddelde van de beoordelingen. Dit zijn de sterren die onder het resultaat worden getoond.",
    "La recherche d’adresse n’a pas abouti. Entrez les coordonnées à la main.": "Het zoeken op adres is mislukt. Voer de coördinaten met de hand in.",
    "La seconde ligne décrit l’image : elle est lue à voix haute par les lecteurs d’écran et reprise par les moteurs de recherche.": "De tweede regel beschrijft de afbeelding: schermlezers lezen die hardop voor en zoekmachines nemen die over.",
    "La section du site où l’article paraît : Actualités, Recettes, Juridique.": "De rubriek van de site waarin het artikel verschijnt: Nieuws, Recepten, Juridisch.",
    "La semaine commence le": "De week begint op",
    "Lâchez pour annuler.": "Laat los om te annuleren.",
    "Laissez vide pour afficher le bouton officiel de PayPal.": "Laat leeg om de officiële knop van PayPal te tonen.",
    "Langue": "Taal",
    "Langue du bloc": "Taal van het blok",
    "Langue du visiteur": "Taal van de bezoeker",
    "Langues": "Talen",
    "Langues de la page": "Talen van de pagina",
    "Langues parlées": "Gesproken talen",
    "Largeur": "Breedte",
    "Largeur (%, rem, vw...)": "Breedte (%, rem, vw...)",
    "Largeur (pixels)": "Breedte (pixels)",
    "Largeur du filet": "Breedte van de lijn",
    "Largeur en pixels": "Breedte in pixels",
    "Largeur maximale": "Maximale breedte",
    "Largeur maximale (px)": "Maximale breedte (px)",
    "Latitude": "Breedtegraad",
    "le bloc": "het blok",
    "Le bouton « Ajouter une configuration » en pose une, à la fin de la page, avec les commandes que son html contient déjà.": "De knop « Een configuratie toevoegen » plaatst er een aan het einde van de pagina, met de bedieningselementen die haar html al bevat.",
    "Le chemin qui mène à cette page depuis l’accueil.": "Het pad dat vanaf de startpagina naar deze pagina leidt.",
    "Le chemin qui mène à la page depuis l’accueil.": "Het pad dat vanaf de startpagina naar de pagina leidt.",
    "Le code ci-dessus est affiché tel quel dans l’éditeur ; il est publié sous sa forme active sur la page.": "De code hierboven wordt onveranderd in de editor getoond; op de pagina wordt hij in werkende vorm gepubliceerd.",
    "Le code de l’unité : GRM pour un gramme, KGM pour un kilogramme, CMT pour un centimètre.": "De code van de eenheid: GRM voor een gram, KGM voor een kilogram, CMT voor een centimeter.",
    "Le code de la langue du contenu : fr, en, nl.": "De taalcode van de inhoud: fr, en, nl.",
    "Le code du pays livré : FR, BE, NL.": "De code van het land van levering: FR, BE, NL.",
    "Le code du pays sur deux lettres : FR, BE, NL.": "De landcode van twee letters: FR, BE, NL.",
    "Le contenu des colonnes est conservé. Une disposition qui en compte moins ramène le contenu des colonnes en trop dans la dernière.": "De inhoud van de kolommen blijft behouden. Een indeling met minder kolommen brengt de inhoud van de overtollige kolommen onder in de laatste.",
    "Le corps de l’article. Facultatif : les moteurs le lisent déjà dans la page.": "De hoofdtekst van het artikel. Optioneel: zoekmachines lezen die al in de pagina.",
    "le dossier": "de map",
    "le fichier": "het bestand",
    "Le fichier dépasse la taille maximale autorisée": "Het bestand overschrijdt de toegestane maximumgrootte",
    "Le fichier dépasse le poids autorisé par votre offre": "Het bestand overschrijdt de grootte die uw abonnement toestaat",
    "Le fuseau dans lequel les heures ci-dessus sont exprimées.": "De tijdzone waarin de uren hierboven zijn uitgedrukt.",
    "Le jour de la dernière modification. Les moteurs s’en servent pour juger de la fraîcheur.": "De dag van de laatste wijziging. Zoekmachines gebruiken die om de actualiteit te beoordelen.",
    "Le jour où le contenu a été mis en ligne.": "De dag waarop de inhoud online is gezet.",
    "Le jour où le contenu a été relu et confirmé exact.": "De dag waarop de inhoud is nagelezen en juist bevonden.",
    "Le logo affiché dans les résultats de recherche. Au moins 112 pixels de côté.": "Het logo dat in de zoekresultaten wordt getoond. Minstens 112 pixels per zijde.",
    "Le logo enregistré dans les réglages de votre site": "Het logo dat in de instellingen van uw site is opgeslagen",
    "Le mois en cours, quel qu’il soit au moment de l’affichage.": "De huidige maand, welke die ook is op het ogenblik van weergave.",
    "Le nom déposé, tel qu’il figure au registre du commerce.": "De geregistreerde naam, zoals die in het handelsregister staat.",
    "Le nom du site, affiché par-dessus le logo": "De naam van de site, getoond over het logo",
    "Le nom sous lequel cette chose est connue. C’est ce que les moteurs affichent en titre.": "De naam waaronder dit ding bekend staat. Dat is wat zoekmachines als titel tonen.",
    "Le passage apparaît et disparaît. À employer avec mesure : un texte qui clignote se lit mal, et se remarque partout ailleurs sur la page.": "De passage verschijnt en verdwijnt. Spaarzaam gebruiken: knipperende tekst leest slecht en trekt de aandacht weg van de rest van de pagina.",
    "Le passage traverse son cadre, de droite à gauche. Il occupe alors toute la largeur disponible, comme un paragraphe.": "De passage beweegt door zijn kader, van rechts naar links. Hij neemt dan de volledige beschikbare breedte in, als een alinea.",
    "Le plugin des scripts n’est pas chargé : la configuration ne peut pas être ajoutée depuis ici. Écrivez-la dans le gabarit du site.": "De scriptsplug-in is niet geladen: de configuratie kan hiervandaan niet worden toegevoegd. Schrijf ze in het sjabloon van de site.",
    "Le résumé et les mots-clés affichés par Google — invisible sur la page": "De samenvatting en de trefwoorden die Google toont — onzichtbaar op de pagina",
    "le script": "het script",
    "Le site dans son ensemble. À poser sur la page d’accueil.": "De site in haar geheel. Te plaatsen op de startpagina.",
    "Le texte d’une réponse.": "De tekst van een antwoord.",
    "Le texte décrit l’image : il est lu à voix haute par les lecteurs d’écran et repris par les moteurs de recherche.": "De tekst beschrijft de afbeelding: schermlezers lezen hem hardop voor en zoekmachines nemen hem over.",
    "Le titre du contenu. Restez sous 110 caractères : au-delà, les moteurs le coupent.": "De titel van de inhoud. Blijf onder 110 tekens: daarboven kappen zoekmachines hem af.",
    "Le type le plus général : à n’employer que si aucun autre ne convient.": "Het meest algemene type: alleen te gebruiken als geen enkel ander past.",
    "Lecture automatique": "Automatisch afspelen",
    "Lecture en boucle": "Herhalen",
    "Légende": "Bijschrift",
    "Les classes de la feuille de style du site n’ont pas pu être lues : elle est servie par un autre domaine, qui n’en autorise pas la lecture. Écrivez le nom de la classe à la main.": "De klassen van het stijlblad van de site konden niet worden gelezen: het wordt door een ander domein geleverd, dat het lezen ervan niet toestaat. Schrijf de naam van de klasse met de hand.",
    "Les classes décident de l’allure du bloc. Celles qui sont proposées viennent de la feuille de style de votre site et des autres blocs de la page.": "De klassen bepalen het uiterlijk van het blok. De voorgestelde klassen komen uit het stijlblad van uw site en uit de andere blokken van de pagina.",
    "Les deux": "Beide",
    "Les effets autres que le glissement demandent leur module dans la page. Si le diaporama se fige après un changement d’effet, revenez au glissement.": "Andere effecten dan schuiven vragen hun module in de pagina. Blijft de diavoorstelling na een effectwissel hangen, keer dan terug naar schuiven.",
    "les microdonnées de cette page": "de microdata van deze pagina",
    "Les moteurs de recherche affichent un prix, des étoiles ou une date de concert quand la page le leur dit dans un langage qu’ils connaissent. Choisissez ce qui correspond le mieux — vous pourrez en changer.": "Zoekmachines tonen een prijs, sterren of een concertdatum wanneer de pagina het hun zegt in een taal die zij kennen. Kies wat het beste past — u kunt het later wijzigen.",
    "Les moteurs de recherche mettent à disposition un outil qui lit une page publiée et dit ce qu’ils y comprennent. Publiez d’abord la page, puis donnez-lui son adresse.": "Zoekmachines stellen een hulpmiddel ter beschikking dat een gepubliceerde pagina leest en zegt wat zij erin begrijpen. Publiceer eerst de pagina en geef er dan het adres van op.",
    "Les moteurs ignoreront la fiche tant qu’elles manqueront. L’enregistrer quand même ?": "Zoekmachines negeren de fiche zolang die ontbreken. Toch opslaan?",
    "Les mots se relaient à la même place. La place réservée est celle du plus long : le texte qui suit ne bouge pas quand ils changent.": "De woorden wisselen elkaar op dezelfde plek af. De gereserveerde ruimte is die van het langste woord: de tekst erna verspringt niet wanneer ze wisselen.",
    "Les propriétés marquées « Exigé » doivent être remplies pour que les moteurs acceptent la fiche. Les autres l’enrichissent.": "De eigenschappen met de vermelding « Verplicht » moeten ingevuld zijn opdat zoekmachines de fiche aanvaarden. De andere verrijken ze.",
    "Les propriétés marquées « Obligatoire » doivent être remplies pour que les moteurs acceptent la fiche. Les autres l’enrichissent.": "De eigenschappen met de vermelding « Verplicht » moeten ingevuld zijn opdat zoekmachines de fiche aanvaarden. De andere verrijken ze.",
    "Les rendez-vous d’avril": "De afspraken van april",
    "Licence": "Licentie",
    "Lien": "Link",
    "Lien du bouton": "Link van de knop",
    "Lien du site": "Link van de site",
    "Lien...": "Link...",
    "Lieu": "Locatie",
    "Lieu affiché": "Getoonde locatie",
    "Lieu choisi. Ajustez le zoom si nécessaire.": "Locatie gekozen. Pas de zoom aan indien nodig.",
    "Lieu de travail": "Werkplek",
    "Lieu en ligne": "Online locatie",
    "Lieu et date de rédaction": "Plaats en datum van schrijven",
    "Liste à puces": "Opsommingslijst",
    "Liste des pages de votre site": "De lijst van de pagina's van uw site",
    "Liste numérotée": "Genummerde lijst",
    "Livraison": "Levering",
    "Livre sterling (GBP)": "Pond sterling (GBP)",
    "Logo": "Logo",
    "Logo du site": "Logo van de site",
    "Longitude": "Lengtegraad",
    "Lundi": "Maandag",
    "Maçonnerie (colonnes)": "Metselwerk (kolommen)",
    "Maintenez enfoncé pendant {0} secondes.": "Houd {0} seconden ingedrukt.",
    "Maintenez le bouton enfoncé pour supprimer": "Houd de knop ingedrukt om te verwijderen",
    "Maintenu": "Gehandhaafd",
    "Mardi": "Dinsdag",
    "Marge extérieure (ex : 0 0 1rem)": "Buitenmarge (bv. 0 0 1rem)",
    "Marge intérieure (ex : .5rem 1rem)": "Binnenmarge (bv. .5rem 1rem)",
    "Marque": "Merk",
    "Matière": "Materiaal",
    "Matières grasses": "Vetgehalte",
    "maximum": "maximum",
    "Médias": "Media",
    "Médiathèque": "Mediabibliotheek",
    "Même onglet": "Zelfde tabblad",
    "Menu": "Menu",
    "menu, contact, partage…": "menu, contact, delen…",
    "Mercredi": "Woensdag",
    "Mesure": "Maat",
    "Met en avant une phrase, avec un filet sur le côté": "Licht een zin uit, met een lijn aan de zijkant",
    "Mettre à jour": "Bijwerken",
    "Microdonnées": "Microdata",
    "Microdonnées de la page": "Microdata van de pagina",
    "Microdonnées incomplètes": "Onvolledige microdata",
    "Milieu droite": "Midden rechts",
    "Milieu gauche": "Midden links",
    "Mise en avant": "Uitgelicht",
    "Mode d’emploi": "Handleiding",
    "Mode de participation": "Wijze van deelname",
    "Modifier cet élément": "Dit element bewerken",
    "Modifier dans Pixel•OnlineCreation": "Bewerken in Pixel•OnlineCreation",
    "Modifier la description pour les moteurs…": "De beschrijving voor zoekmachines bewerken…",
    "Modifier le bloc": "Het blok bewerken",
    "Modifier le diaporama": "De diavoorstelling bewerken",
    "Modifier le lien": "De link bewerken",
    "Modifier le script": "Het script bewerken",
    "Modifier le texte animé": "De bewegende tekst bewerken",
    "Modifier les microdonnées": "De microdata bewerken",
    "Modifier les microdonnées de la page…": "De microdata van de pagina bewerken…",
    "Modifier…": "Bewerken…",
    "Mois": "Maand",
    "Mois affiché": "Getoonde maand",
    "Mois en cours": "Huidige maand",
    "Montant": "Bedrag",
    "Monter": "Omhoog",
    "Monter cette vue": "Deze weergave omhoog",
    "Monter le bloc": "Het blok omhoog",
    "Mosaïque carrée": "Vierkant mozaïek",
    "Mots qui se relaient": "Woorden die elkaar afwisselen",
    "Mots qui se relaient (un par ligne)": "Woorden die elkaar afwisselen (één per regel)",
    "Mots-clés": "Trefwoorden",
    "Nature de la prestation": "Aard van de dienst",
    "Navigation": "Navigatie",
    "Ne pas supprimer": "Niet verwijderen",
    "Neuf": "Nieuw",
    "Neuf, d’occasion, reconditionné. Les moteurs l’affichent à côté du prix, et une place de marché peut le refuser s’il manque.": "Nieuw, tweedehands, gereviseerd. Zoekmachines tonen het naast de prijs, en een marktplaats kan de fiche weigeren als het ontbreekt.",
    "Niveau": "Niveau",
    "Niveau de prix": "Prijsniveau",
    "Nom": "Naam",
    "Nom d’une classe, par exemple text-center": "Naam van een klasse, bijvoorbeeld text-center",
    "Nom de famille": "Achternaam",
    "Nom de l’article": "Naam van het item",
    "Nom de l’événement": "Naam van het evenement",
    "Nom du dossier": "Naam van de map",
    "Nom du widget": "Naam van de widget",
    "Nom exact de la propriété schema.org, par exemple award :": "Exacte naam van de schema.org-eigenschap, bijvoorbeeld award:",
    "Nombre d’avis": "Aantal beoordelingen",
    "Nombre d’offres": "Aantal aanbiedingen",
    "Nombre de mots": "Aantal woorden",
    "Nombre de pages affichées (0 = toutes)": "Aantal getoonde pagina's (0 = alle)",
    "Non": "Nee",
    "Non pour un contenu réservé aux abonnés.": "Nee voor inhoud die aan abonnees is voorbehouden.",
    "Normale": "Normaal",
    "Nos bureaux": "Onze kantoren",
    "Note": "Score",
    "Note donnée": "Gegeven score",
    "Note maximale": "Hoogste score",
    "Note minimale": "Laagste score",
    "Note moyenne": "Gemiddelde score",
    "Nouveau dossier": "Nieuwe map",
    "Nouveau nom": "Nieuwe naam",
    "Nouvel onglet": "Nieuw tabblad",
    "Numéro d’identification": "Fiscaal identificatienummer",
    "Numéro de TVA": "Btw-nummer",
    "Numéro de vue": "Nummer van de weergave",
    "Numéro et rue": "Nummer en straat",
    "Occasion": "Tweedehands",
    "Œuvre": "Werk",
    "Offre": "Aanbod",
    "Offre d’emploi": "Vacature",
    "Ombre : couleur": "Schaduw: kleur",
    "Ombre : décalage horizontal": "Schaduw: horizontale verschuiving",
    "Ombre : décalage vertical": "Schaduw: verticale verschuiving",
    "Ombre : flou": "Schaduw: vervaging",
    "Ombre : X": "Schaduw: X",
    "Ombre : Y": "Schaduw: Y",
    "Ordinateur": "Computer",
    "Organisateur": "Organisator",
    "Organisation": "Organisatie",
    "Organisme": "Aanbieder",
    "Ou adresse d’une image en ligne (https://…)": "Of het adres van een online afbeelding (https://…)",
    "Oui": "Ja",
    "Outil de test des moteurs…": "Testhulpmiddel van de zoekmachines…",
    "Outils de blocs": "Blokgereedschap",
    "Outils nécessaires": "Benodigd gereedschap",
    "Ouverture": "Opening",
    "Ouvrir dans": "Openen in",
    "Ouvrir le lien": "De link openen",
    "Page actuelle (ancres)": "Huidige pagina (ankers)",
    "Page intégrée": "Ingesloten pagina",
    "Page intégrée (iframe)": "Ingesloten pagina (iframe)",
    "Page web": "Webpagina",
    "Page Wikipédia, profil Facebook, fiche Google : les adresses qui désignent la même chose ailleurs.": "Wikipedia-pagina, Facebook-profiel, Google-vermelding: de adressen die elders hetzelfde ding aanduiden.",
    "panier, téléphone, flèche…": "winkelmandje, telefoon, pijl…",
    "Paragraphe": "Alinea",
    "Paragraphe, image, colonnes…": "Alinea, afbeelding, kolommen…",
    "Parallaxe": "Parallax",
    "Pays": "Land",
    "Peintre carrossier": "Autospuiter",
    "Peinture automobile": "Autospuitwerk",
    "Personnalisé (adresse)": "Aangepast (adres)",
    "Personnalisées": "Aangepast",
    "Personne": "Persoon",
    "Perspective": "Coverflow",
    "Petite": "Klein",
    "Pixel•OnlineCreation, l’éditeur d’images": "Pixel•OnlineCreation, de afbeeldingseditor",
    "Pixels": "Pixels",
    "Plage d’ouverture": "Openingsperiode",
    "Plan OpenStreetMap": "OpenStreetMap-plattegrond",
    "Planning": "Planning",
    "Plein écran": "Volledig scherm",
    "Pleine largeur": "Volledige breedte",
    "Plusieurs offres pour le même produit : du moins cher au plus cher.": "Meerdere aanbiedingen voor hetzelfde product: van goedkoop naar duur.",
    "Plusieurs photos présentées en mosaïque, avec agrandissement au clic": "Meerdere foto's als mozaïek, met vergroting bij een klik",
    "Poids": "Gewicht",
    "Point de contact": "Contactpunt",
    "Points": "Stippen",
    "Police du site": "Lettertype van de site",
    "Portes ouvertes": "Opendeurdag",
    "Position sur l’image": "Positie op de afbeelding",
    "Pour combien de personnes": "Voor hoeveel personen",
    "Précommande": "Voorbestelling",
    "Prénom": "Voornaam",
    "Présentation": "Presentatie",
    "Presse": "Pers",
    "Prestataire": "Dienstverlener",
    "Prestation": "Dienst",
    "Principal": "Voornaamste",
    "Prix": "Prijs",
    "Prix et disponibilité": "Prijs en beschikbaarheid",
    "Prix le plus bas": "Laagste prijs",
    "Prix le plus haut": "Hoogste prijs",
    "Prix valable jusqu’au": "Prijs geldig tot",
    "Produit": "Product",
    "Proportions": "Beeldverhouding",
    "Proposer le téléchargement du fichier": "Het bestand ter download aanbieden",
    "propriété": "eigenschap",
    "Propriété écrite à la main : l’éditeur ne la connaît pas et ne peut donc pas la vérifier.": "Met de hand geschreven eigenschap: de editor kent ze niet en kan ze dus niet controleren.",
    "propriétés": "eigenschappen",
    "Propriétés de l’image": "Eigenschappen van de afbeelding",
    "Propriétés du bloc": "Eigenschappen van het blok",
    "Protéines": "Eiwitgehalte",
    "Que décrit cette page ?": "Wat beschrijft deze pagina?",
    "Quelques phrases qui décrivent la chose. Souvent reprise sous le titre dans les résultats.": "Enkele zinnen die het ding beschrijven. Vaak getoond onder de titel in de resultaten.",
    "Question": "Vraag",
    "Questions": "Vragen",
    "Questions fréquentes": "Veelgestelde vragen",
    "Qui a écrit ce contenu : une personne, ou l’entreprise elle-même.": "Wie deze inhoud heeft geschreven: een persoon, of het bedrijf zelf.",
    "Qui publie ce contenu — le plus souvent votre entreprise.": "Wie deze inhoud publiceert — meestal uw bedrijf.",
    "Quitter le plein écran": "Volledig scherm verlaten",
    "Raison sociale": "Maatschappelijke naam",
    "Rang": "Rangorde",
    "Rapport": "Verhouding",
    "Rapport largeur / hauteur": "Verhouding breedte / hoogte",
    "Recette": "Recept",
    "Recherche en cours…": "Bezig met zoeken…",
    "Rechercher": "Zoeken",
    "Rechercher dans ce dossier": "Zoeken in deze map",
    "Rechercher dans ce dossier…": "Zoeken in deze map…",
    "Rechercher un bloc": "Een blok zoeken",
    "Recommandé : un diaporama qui repart tout seul pendant qu’on le regarde est pénible, et empêche de revenir en arrière.": "Aanbevolen: een diavoorstelling die vanzelf opnieuw start terwijl men ernaar kijkt is hinderlijk, en belet terug te gaan.",
    "Reconditionné": "Gereviseerd",
    "Réduire": "Verkleinen",
    "Référence": "Referentie",
    "Référence (SKU)": "Referentie (SKU)",
    "Référence du fabricant": "Referentie van de fabrikant",
    "Référencement": "Zoekmachines",
    "Référencement de la page": "Zoekmachine-instellingen van de pagina",
    "Région ou département": "Regio of provincie",
    "Réglages": "Instellingen",
    "réglages retrouvés": "instellingen gevonden",
    "Relation (rel)": "Relatie (rel)",
    "Rémunération": "Verloning",
    "Rendez-vous du mois": "Afspraken van de maand",
    "Renommage…": "Bezig met hernoemen…",
    "Renommer": "Hernoemen",
    "Renommer le fichier": "Het bestand hernoemen",
    "Renommer…": "Hernoemen…",
    "Repartir au début après la dernière vue": "Opnieuw beginnen na de laatste weergave",
    "Replier": "Inklappen",
    "Réponse": "Antwoord",
    "Reporté": "Uitgesteld",
    "Réseaux sociaux": "Sociale netwerken",
    "Restauration…": "Bezig met herstellen…",
    "Restaurer": "Herstellen",
    "Retirer": "Verwijderen",
    "Retirer ce palier": "Dit breekpunt verwijderen",
    "Retirer cette image": "Deze afbeelding verwijderen",
    "Retirer cette valeur": "Deze waarde verwijderen",
    "Retirer cette vue": "Deze weergave verwijderen",
    "Retoucher cette image…": "Deze afbeelding bijwerken…",
    "Retoucher l’image…": "De afbeelding bijwerken…",
    "Retour à": "Terug naar",
    "Retournement": "Omslaan",
    "Rétrécir la colonne": "De kolom versmallen",
    "return confirm('Quitter la page ?')": "return confirm('Pagina verlaten?')",
    "Rien de renseigné": "Niets ingevuld",
    "Rien ne bouge pour qui a demandé à son système de réduire les animations : le texte reste alors lisible, arrêté.": "Er beweegt niets voor wie zijn systeem om minder beweging heeft gevraagd: de tekst blijft dan leesbaar, stil.",
    "Rubrique": "Rubriek",
    "Rubrique de l’édition papier": "Rubriek van de papieren editie",
    "S’arrêter dès que le visiteur y touche": "Stoppen zodra de bezoeker eraan komt",
    "Saisissez d’abord une adresse.": "Voer eerst een adres in.",
    "Saisissez une adresse et cliquez sur « Rechercher », ou entrez directement des coordonnées.": "Voer een adres in en klik op « Zoeken », of geef rechtstreeks coördinaten op.",
    "Samedi": "Zaterdag",
    "Sans bordure": "Zonder rand",
    "Sans empattement": "Schreefloos",
    "Sans le son": "Zonder geluid",
    "sans réglages dans la page": "geen instellingen in de pagina",
    "Sans symbole ni espace : 28 ou 28.50. La devise est indiquée à côté.": "Zonder symbool of spatie: 28 of 28.50. De munteenheid staat ernaast.",
    "Script JavaScript": "JavaScript-script",
    "Script JavaScript...": "JavaScript-script...",
    "script vide": "leeg script",
    "Secondaire": "Secundair",
    "Section de langue": "Taalsectie",
    "Sélectionner le bloc parent": "Het bovenliggende blok selecteren",
    "Sélectionnez du texte pour lui donner une langue": "Selecteer tekst om er een taal aan te geven",
    "Semaine": "Week",
    "Sens du défilement": "Richting van het doorlopen",
    "Séparateur": "Scheiding",
    "Séparateur réglable": "Instelbare scheiding",
    "Séparateur vertical": "Verticale scheiding",
    "Séparateur vertical...": "Verticale scheiding...",
    "Sépare visuellement deux parties de la page": "Scheidt twee delen van de pagina visueel",
    "Séparés par des virgules.": "Gescheiden door komma's.",
    "Séparés par des virgules. Ils décrivent le sujet, pas la page.": "Gescheiden door komma's. Ze beschrijven het onderwerp, niet de pagina.",
    "Service": "Dienst",
    "Service à contacter": "Te contacteren dienst",
    "Service client": "Klantendienst",
    "Site web": "Website",
    "Situe une adresse sur un plan OpenStreetMap": "Wijst een adres aan op een OpenStreetMap-plattegrond",
    "Sorte d’animation": "Soort beweging",
    "Sorte de lien": "Soort link",
    "Souligné": "Onderstreept",
    "Source (lien)": "Bron (link)",
    "sourire, cœur, drapeau…": "glimlach, hart, vlag…",
    "Sous-titre": "Ondertitel",
    "Sous-titre à l’intérieur d’une section": "Een tussenkop binnen een sectie",
    "Stage": "Stage",
    "Style": "Stijl",
    "Style CSS écrit à même le lien": "CSS-stijl rechtstreeks op de link geschreven",
    "Style du lien": "Stijl van de link",
    "Style du texte": "Stijl van de tekst",
    "Style prédéfini": "Kant-en-klare stijl",
    "Sujet": "Onderwerp",
    "Suppression dans {0} secondes": "Verwijderen over {0} seconden",
    "Suppression…": "Bezig met verwijderen…",
    "Supprimer": "Verwijderen",
    "Supprimer ce dossier": "Deze map verwijderen",
    "Supprimer cet élément": "Dit element verwijderen",
    "Supprimer la colonne": "De kolom verwijderen",
    "Supprimer la fiche": "De fiche verwijderen",
    "Supprimer la ligne et ses colonnes": "De rij en haar kolommen verwijderen",
    "Supprimer le bloc": "Het blok verwijderen",
    "Supprimer le lien": "De link verwijderen",
    "Supprimer le script": "Het script verwijderen",
    "Supprimer le séparateur": "De scheiding verwijderen",
    "Supprimer les microdonnées": "De microdata verwijderen",
    "Sur commande": "Op bestelling",
    "Sur place": "Ter plaatse",
    "Survolez le bloc puis cliquez sur « Modifier le diaporama » pour changer les vues et le défilement.": "Beweeg over het blok en klik dan op « De diavoorstelling bewerken » om de weergaven en het doorlopen te wijzigen.",
    "Système": "Besturingssysteem",
    "Tableau": "Tabel",
    "Tablette": "Tablet",
    "Taille": "Grootte",
    "Taille d’une portion": "Grootte van een portie",
    "Taille des vignettes (px)": "Grootte van de miniaturen (px)",
    "Taille du texte (ex : 1.5rem)": "Tekstgrootte (bv. 1.5rem)",
    "Tailles rapides": "Snelle formaten",
    "Tarif": "Tarief",
    "tarifs": "tarieven",
    "Téléphone": "Telefoon",
    "Téléversement…": "Bezig met uploaden…",
    "Téléverser…": "Uploaden…",
    "Temps d’arrêt sur chaque vue (millisecondes)": "Pauze op elke weergave (milliseconden)",
    "Temps de cuisson": "Bereidingstijd",
    "Temps de préparation": "Voorbereidingstijd",
    "Temps partiel": "Deeltijds",
    "Temps plein": "Voltijds",
    "Texte": "Tekst",
    "Texte à afficher": "Weer te geven tekst",
    "Texte affiché par-dessus l’image": "Tekst getoond over de afbeelding",
    "Texte alternatif": "Alternatieve tekst",
    "Texte alternatif (lu par les lecteurs d’écran)": "Alternatieve tekst (voorgelezen door schermlezers)",
    "Texte animé": "Bewegende tekst",
    "Texte animé...": "Bewegende tekst...",
    "Texte de l’article": "Tekst van het artikel",
    "Texte de l’avis": "Tekst van de beoordeling",
    "Texte de l’épingle": "Tekst van de speld",
    "Texte de la réponse": "Tekst van het antwoord",
    "Texte de remplacement": "Alternatieve tekst",
    "Texte déplié": "Uitgeklapte tekst",
    "Texte déployable": "Uitklapbare tekst",
    "Texte du bouton": "Tekst van de knop",
    "Texte par-dessus": "Tekst erover",
    "Titre": "Titel",
    "Titre (accessibilité)": "Titel (toegankelijkheid)",
    "Titre affiché": "Getoonde titel",
    "Titre affiché au survol": "Titel getoond bij aanwijzen",
    "Titre cliquable": "Aanklikbare titel",
    "Titre de niveau 2": "Kop niveau 2",
    "Titre de niveau 3": "Kop niveau 3",
    "Titre du lien": "Titel van de link",
    "Titre du lien (bulle d’aide au survol)": "Titel van de link (tooltip bij aanwijzen)",
    "Titre du site avec son logo": "Naam van de site met haar logo",
    "Titre principal d’une section": "De hoofdkop van een sectie",
    "Tours, 14 mars 2026": "Utrecht, 14 maart 2026",
    "Tous": "Alle",
    "Tous les réseaux": "Alle netwerken",
    "Tout ce qu’il contient sera perdu.": "Alles wat ze bevat gaat verloren.",
    "Tout détruire": "Alles vernietigen",
    "Toutes": "Alle",
    "Toutes les langues": "Alle talen",
    "Toutes ses versions seront perdues.": "Al zijn versies gaan verloren.",
    "Trait horizontal": "Horizontale lijn",
    "Travailler dans une seule langue": "In één enkele taal werken",
    "Type": "Type",
    "Type de contrat": "Contracttype",
    "Type de cuisine": "Soort keuken",
    "type inconnu": "onbekend type",
    "Type MIME": "MIME-type",
    "Types acceptés": "Aanvaarde types",
    "Typographie": "Lettertype",
    "Un article à vendre : son prix, sa disponibilité, ses avis.": "Een artikel te koop: de prijs, de beschikbaarheid, de beoordelingen.",
    "Un article d’actualité, daté et signé.": "Een nieuwsartikel, gedateerd en ondertekend.",
    "Un article publié au fil de l’eau sur un blog.": "Een artikel dat gaandeweg op een blog verschijnt.",
    "Un bloc de texte courant": "Een gewoon tekstblok",
    "Un bouton « Acheter » qui ouvre le paiement PayPal": "Een knop « Kopen » die de PayPal-betaling opent",
    "Un bouton qui enregistre votre événement dans l’agenda du visiteur": "Een knop die uw evenement in de agenda van de bezoeker opslaat",
    "Un bouton qui met en avant l’action principale": "Een knop die de belangrijkste actie uitlicht",
    "Un code qui désigne cette chose sans ambiguïté : référence interne, numéro de catalogue.": "Een code die dit ding ondubbelzinnig aanduidt: interne referentie, catalogusnummer.",
    "Un contenu créé : texte, image, vidéo, logiciel.": "Gemaakte inhoud: tekst, afbeelding, video, software.",
    "Un cours ou une formation proposée.": "Een aangeboden cursus of opleiding.",
    "Un endroit : salle, monument, parking.": "Een plek: zaal, monument, parking.",
    "Un espace vertical ou un filet de séparation": "Verticale ruimte, of een scheidingslijn",
    "Un établissement où l’on se rend : boutique, cabinet, restaurant.": "Een zaak waar men naartoe gaat: winkel, praktijk, restaurant.",
    "Un formulaire dont les messages arrivent dans votre boîte mail": "Een formulier waarvan de berichten in uw mailbox belanden",
    "Un identifiant commence par une lettre et ne contient ni espace ni accent. Par exemple : tarifs, nos-services, contact2.": "Een identificatie begint met een letter en bevat geen spatie of accent. Bijvoorbeeld: tarieven, onze-diensten, contact2.",
    "Un jour ou un groupe de jours, avec l’heure d’ouverture et de fermeture.": "Een dag of een groep dagen, met het openings- en sluitingsuur.",
    "Un logiciel ou une application mobile.": "Een programma of een mobiele toepassing.",
    "Un mot sans espace, unique dans la page. Un lien pourra y conduire avec « #tarifs », et les scripts du site s’en servent pour retrouver ce bloc.": "Eén woord zonder spatie, uniek in de pagina. Een link kan er met « #tarieven » naartoe leiden, en de scripts van de site gebruiken het om dit blok terug te vinden.",
    "Un nombre entier (3), un nombre décimal pour laisser deviner la suivante (1.15), ou « auto » pour suivre la largeur de chaque vue.": "Een geheel getal (3), een decimaal getal om de volgende te laten vermoeden (1.15), of « auto » om de breedte van elke weergave te volgen.",
    "Un poste à pourvoir.": "Een openstaande functie.",
    "Un pour l’accueil, deux pour la rubrique, et ainsi de suite.": "Eén voor de startpagina, twee voor de rubriek, enzovoort.",
    "Un prix, une devise et une disponibilité.": "Een prijs, een munteenheid en een beschikbaarheid.",
    "Un second nom sous lequel la chose est aussi connue.": "Een tweede naam waaronder het ding ook bekend staat.",
    "Un service et la façon de le joindre.": "Een dienst en hoe die te bereiken is.",
    "Un service proposé plutôt qu’un objet vendu.": "Een aangeboden dienst eerder dan een verkocht voorwerp.",
    "Un texte de fond : billet, dossier, tribune.": "Een diepgaande tekst: bijdrage, dossier, opiniestuk.",
    "Un titre accrocheur": "Een pakkende titel",
    "Un titre cliquable qui déplie un texte : idéal pour une foire aux questions": "Een aanklikbare titel die een tekst uitklapt: ideaal voor een vragenlijst",
    "Un titre et un texte éditables directement dans la page": "Een titel en een tekst die rechtstreeks in de pagina bewerkt worden",
    "Une à deux phrases, environ 160 caractères : c’est le texte affiché sous le titre dans les résultats de recherche.": "Eén tot twee zinnen, ongeveer 160 tekens: dat is de tekst die onder de titel in de zoekresultaten verschijnt.",
    "Une adresse complète, telle qu’on l’écrit sur une enveloppe.": "Een volledig adres, zoals men het op een envelop schrijft.",
    "Une autre propriété, écrite à la main…": "Een andere eigenschap, met de hand geschreven…",
    "Une citation mise en avant avec son auteur": "Een uitgelicht citaat met de auteur ervan",
    "Une date à retenir : concert, portes ouvertes, formation.": "Een datum om te onthouden: concert, opendeurdag, opleiding.",
    "Une entreprise, une association, une administration.": "Een bedrijf, een vereniging, een overheidsdienst.",
    "Une étape du fil d’Ariane : sa position, son nom et son adresse.": "Een stap van het kruimelpad: de positie, de naam en het adres.",
    "Une étape du mode d’emploi.": "Een stap van de handleiding.",
    "Une image avec sa légende et un lien optionnel": "Een afbeelding met haar bijschrift en een optionele link",
    "Une image décrite pour elle-même : auteur, licence, dimensions.": "Een afbeelding op zichzelf beschreven: auteur, licentie, afmetingen.",
    "Une ligne de colonnes côte à côte, qui s’empilent sur mobile": "Een rij kolommen naast elkaar, die op mobiel onder elkaar komen",
    "Une marche à suivre, étape par étape.": "Een werkwijze, stap voor stap.",
    "Une note isolée, celle d’un avis.": "Een losse score, die van één beoordeling.",
    "Une page de questions-réponses. Les moteurs les affichent dépliables.": "Een pagina met vragen en antwoorden. Zoekmachines tonen ze uitklapbaar.",
    "Une page ordinaire du site : présentation, mentions légales, contact.": "Een gewone pagina van de site: voorstelling, wettelijke vermeldingen, contact.",
    "Une personne : auteur, dirigeant, artisan.": "Een persoon: auteur, bestuurder, vakman.",
    "Une photo qui représente la chose. Les moteurs préfèrent une image large, d’au moins 1200 pixels.": "Een foto die het ding voorstelt. Zoekmachines verkiezen een brede afbeelding, van minstens 1200 pixels.",
    "Une phrase qui marque les esprits.": "Een zin die men onthoudt.",
    "Une question et sa réponse.": "Een vraag en haar antwoord.",
    "Une recette de cuisine, avec ses ingrédients et ses étapes.": "Een kookrecept, met de ingrediënten en de stappen.",
    "Une somme et sa devise.": "Een bedrag en de munteenheid.",
    "Une valeur avec son unité : un poids, une longueur.": "Een waarde met haar eenheid: een gewicht, een lengte.",
    "Une vidéo hébergée ou intégrée dans la page.": "Een video die in de pagina staat of erin is ingesloten.",
    "Unité": "Eenheid",
    "Utiliser ce fichier": "Dit bestand gebruiken",
    "Utiliser ces fichiers": "Deze bestanden gebruiken",
    "Valeur": "Waarde",
    "Valeurs nutritionnelles": "Voedingswaarden",
    "Veigné": "Veigné",
    "Vendeur": "Verkoper",
    "Vendredi": "Vrijdag",
    "Vérification des quotas…": "Bezig met het nakijken van de quota…",
    "Vérifier la fiche": "De fiche nakijken",
    "Version": "Versie",
    "Version enregistrée": "Opgeslagen versie",
    "Version publiée uniquement en": "Versie enkel gepubliceerd in",
    "Versions": "Versies",
    "Vertical": "Verticaal",
    "Vidéo": "Video",
    "Vider": "Leegmaken",
    "Videz ce champ pour la retirer.": "Maak dit veld leeg om ze te verwijderen.",
    "Ville": "Stad",
    "Vintage": "Vintage",
    "Voile sombre (0 à 100)": "Donkere sluier (0 tot 100)",
    "Votre médiathèque est pleine. Supprimez des fichiers ou d’anciennes versions pour en ajouter.": "Uw mediabibliotheek is vol. Verwijder bestanden of oude versies om er toe te voegen.",
    "Votre référence interne, celle du bon de commande.": "Uw interne referentie, die van de bestelbon.",
    "Vous modifiez": "U bewerkt",
    "Vue": "Weergave",
    "vue n’a pas d’image et ne montrerait rien sur le site. La retirer ?": "weergave heeft geen afbeelding en zou niets op de site tonen. Verwijderen?",
    "Vues affichées en même temps": "Weergaven die tegelijk worden getoond",
    "vues n’ont pas d’image et ne montreraient rien sur le site. Les retirer ?": "weergaven hebben geen afbeelding en zouden niets op de site tonen. Verwijderen?",
    "Widget HTML": "HTML-widget",
    "YouTube, Vimeo, Dailymotion ou toute autre adresse intégrable": "YouTube, Vimeo, Dailymotion of elk ander insluitbaar adres",
    "Zone desservie": "Bediend gebied",
    "Zone livrée": "Leveringsgebied",
    "Zoom (1 = monde, 19 = rue)": "Zoom (1 = wereld, 19 = straat)",
    "Zoom à la molette de la souris": "Zoomen met het muiswiel"
});
/* — ONLC : fin des chaînes des plugins — */
