import { Type } from '@ephox/katamari';

import Editor from 'hugerte/core/api/Editor';
import { EditorOptions } from 'hugerte/core/api/OptionTypes';

export interface UserIconEntry {
  readonly name: string;
  readonly keywords?: string | string[];
  readonly category?: string;
}

export interface UserEmojiEntry {
  readonly char: string;
  readonly keywords?: string[];
  readonly category?: string;
}

const option: {
  <K extends keyof EditorOptions>(name: K): (editor: Editor) => EditorOptions[K];
  <T>(name: string): (editor: Editor) => T;
} = (name: string) => (editor: Editor) =>
  editor.options.get(name);

// The emoji database is generated by the `grunt emoji` task and shared with the emoticons plugin
const DEFAULT_EMOJI_ID = 'hugerte.plugins.emoticons';

const register = (editor: Editor, pluginUrl: string): void => {
  const registerOption = editor.options.register;

  registerOption('onlc_icons_emoji_database_url', {
    processor: 'string',
    default: `${pluginUrl}/js/emojis.js`
  });

  registerOption('onlc_icons_emoji_database_id', {
    processor: 'string',
    default: DEFAULT_EMOJI_ID
  });

  registerOption('onlc_icons_emoji_append', {
    processor: 'object',
    default: {}
  });

  // Le jeu d'icônes intégré est celui de Material Design : désactivez-le pour n'utiliser que
  // le catalogue fourni par `onlc_icons_material_url` (FontAwesome par exemple).
  registerOption('onlc_icons_builtin', {
    processor: 'boolean',
    default: true
  });

  registerOption('onlc_icons_material_url', {
    processor: 'string',
    default: ''
  });

  registerOption('onlc_icons_material_append', {
    processor: (value) => {
      const valid = Type.isArrayOf(value, Type.isObject);
      return valid ? { value, valid } : { valid: false, message: 'Must be an array of objects.' };
    },
    default: []
  });

  registerOption('onlc_icons_stylesheet_url', {
    processor: 'string',
    default: 'https://fonts.googleapis.com/icon?family=Material+Icons'
  });

  registerOption('onlc_icons_class', {
    processor: 'string',
    default: 'material-icons'
  });

  // 'ligature' renders `<span class="material-icons">home</span>`,
  // 'class' renders `<i class="mdi mdi-home"></i>`
  registerOption('onlc_icons_output', {
    processor: (value) => {
      const valid = value === 'ligature' || value === 'class';
      return valid ? { value, valid } : { valid: false, message: 'Must be "ligature" or "class".' };
    },
    default: 'ligature'
  });

  registerOption('onlc_icons_class_prefix', {
    processor: 'string',
    default: 'mdi mdi-'
  });

  registerOption('onlc_icons_emoji_trigger', {
    processor: 'string',
    default: ':'
  });

  registerOption('onlc_icons_icon_trigger', {
    processor: 'string',
    default: '::'
  });

  registerOption('onlc_icons_results_limit', {
    processor: 'number',
    default: 300
  });
};

const getEmojiDatabaseUrl = option<string>('onlc_icons_emoji_database_url');
const getEmojiDatabaseId = option<string>('onlc_icons_emoji_database_id');
const getAppendedEmoji = option<Record<string, UserEmojiEntry>>('onlc_icons_emoji_append');
const useBuiltinIcons = option<boolean>('onlc_icons_builtin');
const getMaterialUrl = option<string>('onlc_icons_material_url');
const getAppendedIcons = option<UserIconEntry[]>('onlc_icons_material_append');
const getStylesheetUrl = option<string>('onlc_icons_stylesheet_url');
const getIconClass = option<string>('onlc_icons_class');
const getOutputMode = option<'ligature' | 'class'>('onlc_icons_output');
const getClassPrefix = option<string>('onlc_icons_class_prefix');
const getEmojiTrigger = option<string>('onlc_icons_emoji_trigger');
const getIconTrigger = option<string>('onlc_icons_icon_trigger');
const getResultsLimit = option<number>('onlc_icons_results_limit');

export {
  register,
  getEmojiDatabaseUrl,
  getEmojiDatabaseId,
  getAppendedEmoji,
  useBuiltinIcons,
  getMaterialUrl,
  getAppendedIcons,
  getStylesheetUrl,
  getIconClass,
  getOutputMode,
  getClassPrefix,
  getEmojiTrigger,
  getIconTrigger,
  getResultsLimit
};
