import { Arr, Type } from '@ephox/katamari';

import Editor from 'hugerte/core/api/Editor';
import { EditorOptions } from 'hugerte/core/api/OptionTypes';

export interface UserIconEntry {
  readonly name: string;
  readonly keywords?: string | string[];
  readonly category?: string;
  readonly family?: string;
  readonly style?: string;
}

export interface UserEmojiEntry {
  readonly char: string;
  readonly keywords?: string[];
  readonly category?: string;
}

const option: {
  <K extends keyof EditorOptions>(name: K): (editor: Editor) => EditorOptions[K];
  <T>(name: string): (editor: Editor) => T;
} = (name: string) => (editor: Editor) =>
  editor.options.get(name);

// The emoji database is generated by the `grunt emoji` task and shared with the emoticons plugin
const DEFAULT_EMOJI_ID = 'hugerte.plugins.emoticons';

const knownFamilies = [ 'material', 'fontawesome' ];

const register = (editor: Editor, pluginUrl: string): void => {
  const registerOption = editor.options.register;

  // `editor.suffix` vaut `.min` quand l'éditeur a été chargé sous son nom minifié : les
  // dictionnaires suivent alors le reste du paquet, au lieu d'imposer au CDN de servir aussi
  // la version lisible d'un fichier de 190 Ko.
  registerOption('onlc_icons_emoji_database_url', {
    processor: 'string',
    default: `${pluginUrl}/js/emojis${editor.suffix}.js`
  });

  registerOption('onlc_icons_emoji_database_id', {
    processor: 'string',
    default: DEFAULT_EMOJI_ID
  });

  registerOption('onlc_icons_emoji_append', {
    processor: 'object',
    default: {}
  });

  /**
   * Familles d'icônes proposées. Les deux polices sont embarquées dans le plugin ; retirez une
   * entrée pour ne pas la charger du tout — ni sa feuille de styles, ni son catalogue.
   */
  registerOption('onlc_icons_families', {
    processor: (value) => {
      const valid = Type.isArrayOf(value, Type.isString) &&
        Arr.forall(value as string[], (entry) => Arr.contains(knownFamilies, entry));
      return valid ? { value, valid } : { valid: false, message: 'Must be an array of "material" and/or "fontawesome".' };
    },
    default: knownFamilies
  });

  registerOption('onlc_icons_material_url', {
    processor: 'string',
    default: ''
  });

  registerOption('onlc_icons_material_append', {
    processor: (value) => {
      const valid = Type.isArrayOf(value, Type.isObject);
      return valid ? { value, valid } : { valid: false, message: 'Must be an array of objects.' };
    },
    default: []
  });

  // Feuille de styles supplémentaire, pour une police d'icônes maison.
  registerOption('onlc_icons_stylesheet_url', {
    processor: 'string',
    default: ''
  });

  registerOption('onlc_icons_class', {
    processor: 'string',
    default: 'material-icons'
  });

  registerOption('onlc_icons_class_prefix', {
    processor: 'string',
    default: 'fa-solid fa-'
  });

  /* Emojis dessinés ------------------------------------------------------- */

  // Dossier des dessins OpenMoji. Le site publié doit servir les mêmes fichiers à cette adresse.
  registerOption('onlc_icons_openmoji_url', {
    processor: 'string',
    default: `${pluginUrl}/openmoji`
  });

  registerOption('onlc_icons_openmoji_index_url', {
    processor: 'string',
    default: `${pluginUrl}/js/openmoji${editor.suffix}.js`
  });

  // Transforme automatiquement les emojis tapés ou collés en dessins OpenMoji.
  registerOption('onlc_icons_rewrite_emoji', {
    processor: 'boolean',
    default: true
  });

  registerOption('onlc_icons_emoji_trigger', {
    processor: 'string',
    default: ':'
  });

  registerOption('onlc_icons_icon_trigger', {
    processor: 'string',
    default: '::'
  });

  registerOption('onlc_icons_results_limit', {
    processor: 'number',
    default: 300
  });
};

const getEmojiDatabaseUrl = option<string>('onlc_icons_emoji_database_url');
const getEmojiDatabaseId = option<string>('onlc_icons_emoji_database_id');
const getAppendedEmoji = option<Record<string, UserEmojiEntry>>('onlc_icons_emoji_append');
const getFamilies = option<string[]>('onlc_icons_families');
const getMaterialUrl = option<string>('onlc_icons_material_url');
const getAppendedIcons = option<UserIconEntry[]>('onlc_icons_material_append');
const getStylesheetUrl = option<string>('onlc_icons_stylesheet_url');
const getIconClass = option<string>('onlc_icons_class');
const getClassPrefix = option<string>('onlc_icons_class_prefix');
const getOpenMojiUrl = option<string>('onlc_icons_openmoji_url');
const getOpenMojiIndexUrl = option<string>('onlc_icons_openmoji_index_url');
const shouldRewriteEmoji = option<boolean>('onlc_icons_rewrite_emoji');
const getEmojiTrigger = option<string>('onlc_icons_emoji_trigger');
const getIconTrigger = option<string>('onlc_icons_icon_trigger');
const getResultsLimit = option<number>('onlc_icons_results_limit');

export {
  register,
  knownFamilies,
  getEmojiDatabaseUrl,
  getEmojiDatabaseId,
  getAppendedEmoji,
  getFamilies,
  getMaterialUrl,
  getAppendedIcons,
  getStylesheetUrl,
  getIconClass,
  getClassPrefix,
  getOpenMojiUrl,
  getOpenMojiIndexUrl,
  shouldRewriteEmoji,
  getEmojiTrigger,
  getIconTrigger,
  getResultsLimit
};
